_SCRIPT_LABEL = "Script:"
_REMOVE_SELECTED = "Remove selected"
_SELECT_SCRIPT = "Select script"
_TOKEN_LABEL = "Token:"
_HOST_LABEL = "Host:"
_PORT_LABEL = "Port:"
_STOP_HOST = "Stop host"
_CLEAR_ALL = "Clear all"

english_word_dict = {
    # Main
    "application_name": "AutoControlGUI",

    # Tabs
    "tab_auto_click": "Auto Click",
    "tab_screenshot": "Screenshot",
    "tab_image_detect": "Image Detection",
    "tab_record": "Record / Playback",
    "tab_script": "Script Executor",
    "tab_script_builder": "Script Builder",
    "tab_recording_editor": "Recording Editor",
    "tab_window_manager": "Windows",
    "tab_scheduler": "Scheduler",
    "tab_socket_server": "Socket Server",
    "tab_live_hud": "Live HUD",
    "tab_hotkeys": "Hotkeys",
    "tab_triggers": "Triggers",
    "tab_plugins": "Plugins",
    "tab_screen_record": "Screen Recording",
    "tab_shell": "Shell Command",
    "tab_report": "Report",
    "tab_run_history": "Run History",
    "tab_accessibility": "Accessibility",
    "tab_vlm": "AI Locator",
    "tab_ocr_reader": "OCR Reader",
    "tab_variables": "Variables",
    "tab_llm_planner": "LLM Planner",
    "tab_remote_desktop": "Remote Desktop",
    "tab_rest_api": "REST API",
    "tab_admin_console": "Admin Console",
    "tab_audit_log": "Audit Log",
    "tab_inspector": "Packet Inspector",
    "tab_usb_devices": "USB Devices",
    "tab_diagnostics": "Diagnostics",

    # Diagnostics tab
    "diag_run": "Run diagnostics",
    "diag_summary_ok": "All {count} checks passed.",
    "diag_summary_failed": "{failed} of {count} checks failed.",
    "diag_col_name": "Check",
    "diag_col_severity": "Severity",
    "diag_col_status": "Status",
    "diag_col_detail": "Detail",
    "diag_status_ok": "OK",
    "diag_status_fail": "FAIL",

    # USB devices tab
    "usb_backend_label": "Backend:",
    "usb_refresh": "Refresh",
    "usb_col_vid": "VID",
    "usb_col_pid": "PID",
    "usb_col_manufacturer": "Manufacturer",
    "usb_col_product": "Product",
    "usb_col_serial": "Serial",
    "usb_col_location": "Bus / Location",
    "usb_auto_refresh": "Auto-refresh + watch hotplug",
    "usb_events_idle": "Hotplug watcher: no changes since last refresh.",
    "usb_events_recent": "Recent hotplug events: {text}",

    # USB passthrough ACL prompt dialog
    "usb_prompt_title": "USB device claim request",
    "usb_prompt_intro": "A remote viewer is asking to claim a USB device on this host. Allow only if you recognise the request.",
    "usb_prompt_vendor": "Vendor ID:",
    "usb_prompt_product": "Product ID:",
    "usb_prompt_serial": "Serial:",
    "usb_prompt_viewer": "Viewer ID:",
    "usb_prompt_remember": "Remember this decision (write a permanent ACL rule)",
    "usb_prompt_allow": "Allow",
    "usb_prompt_deny": "Deny",
    "tab_usb_browser": "USB Browser",

    # USB browser (viewer-side)
    "usb_browser_target_group": "Remote host",
    "usb_browser_url": "REST URL:",
    "usb_browser_token": "Bearer token:",
    "usb_browser_fetch": "Fetch devices",
    "usb_browser_open": "Open selected",
    "usb_browser_fetching": "Fetching…",
    "usb_browser_fetched": "Fetched {count} devices.",
    "usb_browser_fetch_failed": "Fetch failed: {error}",
    "usb_browser_col_vid": "VID",
    "usb_browser_col_pid": "PID",
    "usb_browser_col_manufacturer": "Manufacturer",
    "usb_browser_col_product": "Product",
    "usb_browser_col_serial": "Serial",
    "usb_browser_open_select_first": "Select a row first.",
    "usb_browser_open_unwired": "Open requires a WebRTC usb DataChannel; not yet wired in this build.",

    # Inspector tab
    "inspector_metrics_group": "Rolling metrics",
    "inspector_summary_text": "{count} samples over {window:.1f}s",
    "inspector_metric_rtt_ms": "RTT (ms)",
    "inspector_metric_fps": "Frames per second",
    "inspector_metric_bitrate_kbps": "Bitrate (kbps)",
    "inspector_metric_packet_loss_pct": "Packet loss (%)",
    "inspector_metric_jitter_ms": "Jitter (ms)",
    "inspector_refresh": "Refresh",
    "inspector_reset": "Reset",
    "inspector_col_age": "Age",

    # Audit log tab
    "audit_filter_group": "Filter",
    "audit_filter_type": "Event type:",
    "audit_filter_host": "Host id:",
    "audit_filter_limit": "Limit:",
    "audit_refresh": "Refresh",
    "audit_verify": "Verify chain",
    "audit_clear": "Clear log",
    "audit_clear_confirm": "Wipe every audit row? This cannot be undone.",
    "audit_clear_done": "Cleared {count} audit rows.",
    "audit_verify_ok": "Chain OK ({total} rows).",
    "audit_verify_broken": "Chain broken at row id {row_id} of {total}.",
    "audit_col_ts": "Timestamp",
    "audit_col_type": "Event",
    "audit_col_host": "Host id",
    "audit_col_viewer": "Viewer id",
    "audit_col_detail": "Detail",

    # Admin console tab
    "admin_add_group": "Register host",
    "admin_add": "Add",
    "admin_remove": _REMOVE_SELECTED,
    "admin_refresh": "Poll all",
    "admin_label": "Label:",
    "admin_url": "Base URL:",
    "admin_token": _TOKEN_LABEL,
    "admin_broadcast_group": "Broadcast",
    "admin_actions_label": "Actions JSON (sent to every host):",
    "admin_broadcast_run": "Run on all hosts",
    "admin_results_label": "Per-host results:",
    "admin_col_label": "Label",
    "admin_col_url": "URL",
    "admin_col_health": "Health",
    "admin_col_latency": "Latency",
    "admin_col_jobs": "Jobs",
    "admin_health_ok": "OK",
    "admin_health_down": "DOWN",

    # REST API tab
    "rest_config_group": "REST API config",
    "rest_status_group": "REST API status",
    "rest_host": _HOST_LABEL,
    "rest_port": _PORT_LABEL,
    "rest_token": _TOKEN_LABEL,
    "rest_token_ph": "leave blank to auto-generate",
    "rest_enable_audit": "Write audit log",
    "rest_start": "Start",
    "rest_stop": "Stop",
    "rest_copy_url": "Copy URL",
    "rest_copy_token": "Copy token",
    "rest_url": "URL:",
    "rest_active_token": "Bearer token:",
    "rest_running": "REST API is running.",
    "rest_stopped": "REST API is stopped.",
    "rest_config_export": "Export config",
    "rest_config_import": "Import config",
    "rest_config_export_done": "Wrote {count} files into {path}.",
    "rest_config_import_confirm": "Replace user config from this bundle? Existing files are renamed to .bak.<timestamp> first.",
    "rest_config_import_done": "Wrote {written} files; skipped {skipped}.",

    # Remote Desktop — WebRTC sub-tabs
    "rd_webrtc_host_tab": "WebRTC Host",
    "rd_webrtc_viewer_tab": "WebRTC Viewer",
    "rd_webrtc_config_group": "WebRTC config",
    "rd_webrtc_monitor_label": "Monitor index:",
    "rd_webrtc_generate_offer": "Generate offer",
    "rd_webrtc_offer_label": "Offer SDP (give this to the viewer):",
    "rd_webrtc_answer_input_label": "Paste viewer's answer SDP:",
    "rd_webrtc_paste_answer": "paste the answer SDP here",
    "rd_webrtc_apply_answer": "Apply answer",
    "rd_webrtc_stop_host": _STOP_HOST,
    "rd_webrtc_offer_input_label": "Paste host's offer SDP:",
    "rd_webrtc_paste_offer": "paste the offer SDP here",
    "rd_webrtc_create_answer": "Create answer",
    "rd_webrtc_stop_viewer": "Stop viewer",
    "rd_webrtc_answer_label": "Answer SDP (give this to the host):",
    "rd_webrtc_status_idle": "Idle",
    "rd_webrtc_state_label": "State:",
    "rd_webrtc_generating_offer": "Generating offer...",
    "rd_webrtc_offer_ready": "Offer ready - copy and send to viewer",
    "rd_webrtc_creating_answer": "Creating answer...",
    "rd_webrtc_answer_ready": "Answer ready - copy and send to host",
    "rd_webrtc_answer_applied": "Answer applied; waiting for viewer auth",
    "rd_webrtc_auth_ok": "Authenticated",
    "rd_webrtc_auth_fail": "Authentication failed",
    "rd_webrtc_token_required": "Token is required",
    "rd_webrtc_no_offer_yet": "Generate an offer first",
    "rd_webrtc_no_answer": "Paste the viewer's answer SDP first",
    "rd_webrtc_no_offer": "Paste the host's offer SDP first",
    "rd_webrtc_unavailable": (
        "WebRTC unavailable - install with pip install je_auto_control[webrtc]"
    ),
    "rd_webrtc_signaling_group": "Connect via signaling server (recommended)",
    "rd_webrtc_manual_group": "Manual SDP exchange (fallback)",
    "rd_webrtc_advanced_group": "Advanced (STUN / TURN)",
    "rd_webrtc_server_label": "Server URL:",
    "rd_webrtc_host_id_label": "Host ID:",
    "rd_webrtc_host_id_placeholder": "8-char ID shown on the host",
    "rd_webrtc_secret_label": "Server secret:",
    "rd_webrtc_regen_id": "New ID",
    "rd_webrtc_publish_via_server": "Publish & wait for viewer",
    "rd_webrtc_connect_via_server": "Connect to host",
    "rd_webrtc_stun_label": "STUN URL:",
    "rd_webrtc_turn_label": "TURN URL:",
    "rd_webrtc_turn_placeholder": "turn:turn.example.com:3478 (optional)",
    "rd_webrtc_turn_user_label": "TURN user:",
    "rd_webrtc_turn_cred_label": "TURN cred:",
    "rd_webrtc_publishing_offer": "Publishing offer; waiting for viewer answer...",
    "rd_webrtc_polling_offer": "Polling signaling server for the host's offer...",
    "rd_webrtc_pushing_answer": "Pushing answer to signaling server...",
    "rd_webrtc_waiting_auth": "Answer pushed; waiting for the host to accept",
    "rd_webrtc_pending_viewer_prompt": (
        "A viewer authenticated with the correct token. "
        "Allow them to control this machine?"
    ),
    "rd_webrtc_server_required": "Signaling server URL is required",
    "rd_webrtc_host_id_required": "Host ID is required",
    # Trust list / accept dialog
    "rd_webrtc_trusted_group": "Trusted viewers (auto-accept)",
    "rd_webrtc_remove_trusted": _REMOVE_SELECTED,
    "rd_webrtc_clear_trusted": _CLEAR_ALL,
    "rd_webrtc_clear_trust_confirm": "Remove every trusted viewer?",
    "rd_webrtc_pending_viewer_title": "Incoming viewer",
    "rd_webrtc_reject": "Reject",
    "rd_webrtc_accept_once": "Accept once",
    "rd_webrtc_accept_and_trust": "Accept && trust",
    # Address book
    "rd_webrtc_address_book_group": "Saved hosts",
    "rd_webrtc_connect_selected": "Connect",
    "rd_webrtc_save_current": "Save current",
    "rd_webrtc_remove_selected": "Remove",
    "rd_webrtc_no_address_selected": "Select a saved host first",
    "rd_webrtc_save_address_missing_fields": (
        "Server URL and Host ID are required to save an entry"
    ),
    # Polish: cursor / blanking / CAD
    "rd_webrtc_show_cursor": "Show cursor in stream",
    "rd_webrtc_blank_screen": "Blank local screen during session",
    "rd_webrtc_blanking_banner": "This screen is currently being viewed remotely",
    "rd_webrtc_send_cad": "Send Ctrl+Alt+Del",
    "rd_webrtc_cad_not_connected": "Connect first before sending Ctrl+Alt+Del",
    # (A) batch
    "rd_webrtc_read_only": "Read-only (drop viewer input)",
    "rd_webrtc_bandwidth_label": "Bandwidth:",
    "rd_webrtc_wake_on_lan": "Wake on LAN",
    "rd_webrtc_wol_mac_prompt": "Target MAC (AA:BB:CC:DD:EE:FF):",
    "rd_webrtc_wol_broadcast_prompt": "Broadcast address:",
    "rd_webrtc_wol_sent": "Magic packet sent",
    "rd_webrtc_start_recording": "Record session",
    "rd_webrtc_stop_recording": "Stop recording",
    "rd_webrtc_recording_save_as": "Save recording as",
    "rd_webrtc_recording_saved": "Recording saved: {path}",
    "rd_webrtc_stats_idle": "(no stats yet)",
    # (B) batch
    "rd_webrtc_hw_codec_label": "Hardware codec:",
    "rd_webrtc_hw_codec_off": "Off (libx264)",
    "rd_webrtc_hw_codec_off_status": "Hardware codec disabled (using libx264)",
    "rd_webrtc_hw_codec_active": "Hardware codec active: {codec}",
    "rd_webrtc_hw_codec_failed": "Hardware codec {codec} unavailable",
    "rd_webrtc_adaptive": "Adapt FPS to network (auto)",
    "rd_webrtc_sessions_count": "Connected viewers: {n}",
    "rd_webrtc_send_mic": "Send mic",
    "rd_webrtc_recv_mic": "Receive viewer mic (play locally)",
    "rd_webrtc_send_file": "Send file...",
    "rd_webrtc_file_sent": "Sent: {name}",
    "rd_webrtc_push_file": "Push file to viewers...",
    "rd_webrtc_no_viewers": "No connected viewers to push to",
    "rd_webrtc_push_done": "Pushed {name} to {n} viewer(s)",
    "rd_webrtc_file_received": "Received: {name}",
    # Remote files browser
    "rd_webrtc_remote_files_group": "Remote inbox files",
    "rd_webrtc_browse_refresh": "Refresh",
    "rd_webrtc_browse_pull": "Pull",
    "rd_webrtc_browse_delete": "Delete",
    "rd_webrtc_browse_col_name": "Name",
    "rd_webrtc_browse_col_size": "Size (bytes)",
    "rd_webrtc_browse_col_mtime": "Modified",
    "rd_webrtc_browse_delete_confirm": "Delete '{name}' from the host's inbox?",
    "rd_webrtc_browse_op_ok": "{name} OK",
    "rd_webrtc_browse_op_failed": "{name} failed: {error}",
    "rd_webrtc_browse_dnd_hint": "Drag files here to upload to the host's inbox.",
    "rd_webrtc_browse_copy_name": "Copy name",
    "rd_webrtc_browse_delete_many_confirm": "Delete {n} files from the host's inbox?",
    "rd_webrtc_upload_done": "Uploaded {n} file(s)",
    # Reverse screen share
    "rd_webrtc_accept_viewer_video": "Accept viewer's screen share",
    "rd_webrtc_share_my_screen": "Share my screen with the host",
    "rd_webrtc_viewer_screen_title": "Viewer screen",
    "rd_webrtc_accept_opus_audio": "Receive viewer Opus audio",
    "rd_webrtc_share_opus_mic": "Share my mic to host (Opus)",
    # KnownHosts dialog
    "rd_webrtc_manage_known_hosts": "Known hosts...",
    "rd_webrtc_known_hosts_title": "Known hosts",
    "rd_webrtc_kh_col_host": "Host ID",
    "rd_webrtc_kh_col_app_fp": "App fingerprint",
    "rd_webrtc_kh_col_dtls_fp": "DTLS fingerprint",
    "rd_webrtc_kh_forget": "Forget selected",
    "rd_webrtc_kh_clear_all": _CLEAR_ALL,
    "rd_webrtc_kh_close": "Close",
    "rd_webrtc_kh_clear_confirm": "Forget every known host?",
    "rd_webrtc_kh_copy_app": "Copy app fp",
    "rd_webrtc_kh_copy_dtls": "Copy DTLS fp",
    "rd_webrtc_kh_add": "Add manual entry",
    "rd_webrtc_kh_add_host_ph": "host_id (e.g. abcd1234)",
    "rd_webrtc_kh_add_app_ph": "app fingerprint (64 hex chars; optional)",
    "rd_webrtc_kh_add_dtls_ph": "DTLS fingerprint (AB:CD:...; optional)",
    "rd_webrtc_auto_reconnect": "Auto reconnect on drop",
    "rd_webrtc_reconnecting": "Reconnecting (attempt {n}/{max})...",
    "rd_webrtc_reconnect_giveup": "Reconnect attempts exhausted",
    "rd_webrtc_reconnect_max": "Max attempts:",
    "rd_webrtc_reconnect_delay": "Base delay:",
    "rd_webrtc_kh_import": "Import...",
    "rd_webrtc_kh_export": "Export...",
    "rd_webrtc_kh_import_bad": "Imported file is not a known-hosts JSON object",
    "rd_webrtc_kh_import_overwrite": "'{host}' already known. Overwrite?",
    "rd_webrtc_kh_import_done": "Imported {added}, skipped {skipped}",
    "rd_webrtc_quality_unknown": "No quality data yet",
    "rd_webrtc_quality_good": "Good (RTT < 80ms, loss < 1%)",
    "rd_webrtc_quality_fair": "Fair (RTT < 200ms, loss < 5%)",
    "rd_webrtc_quality_poor": "Poor (high RTT or loss)",
    "rd_webrtc_kh_col_last_seen": "Last seen",
    "rd_webrtc_sess_col_id": "Session",
    "rd_webrtc_sess_col_viewer": "Viewer ID",
    "rd_webrtc_sess_col_state": "State",
    "rd_webrtc_sess_col_connected": "Connected",
    "rd_webrtc_disconnect_selected": "Disconnect selected",
    "rd_webrtc_kh_stale_tip": "Last seen > 90 days ago — consider re-verifying",
    "rd_webrtc_kh_forget_stale": "Forget all stale",
    "rd_webrtc_kh_forget_stale_confirm": "Forget {n} stale entries?",
    "rd_webrtc_kh_no_stale": "No stale entries to forget",
    "rd_webrtc_sess_trust_viewer": "Trust this viewer",
    "rd_webrtc_sess_copy_id": "Copy session id",
    "rd_webrtc_favorite": "Add to favorites ★",
    "rd_webrtc_unfavorite": "Remove from favorites",
    "rd_webrtc_trust_import": "Import...",
    "rd_webrtc_trust_export": "Export...",
    "rd_webrtc_trust_import_done": "Imported {n} trusted viewer(s)",
    "rd_webrtc_my_fingerprint": "My fingerprint:",
    "rd_webrtc_copy_fingerprint": "Copy",
    "rd_webrtc_ab_export": "Export book...",
    "rd_webrtc_ab_import": "Import book...",
    "rd_webrtc_ab_clear": _CLEAR_ALL,
    "rd_webrtc_ab_clear_confirm": "Clear the entire address book?",
    "rd_webrtc_ab_import_done": "Imported {n} address-book entries",
    "rd_webrtc_tray_idle": "AutoControl host: idle",
    "rd_webrtc_tray_running": "AutoControl host: {n} viewer(s)",
    "rd_webrtc_tray_open": "Open window",
    "rd_webrtc_tray_stop": _STOP_HOST,
    "rd_webrtc_tray_quit": "Quit",
    "rd_webrtc_region_label": "Region (x,y,w,h):",
    "rd_webrtc_region_placeholder": "leave blank for full screen",
    "rd_webrtc_pick_region": "Pick region...",
    "rd_webrtc_monitor_all": "All monitors",
    "rd_webrtc_max_bitrate": "Max bitrate:",
    "rd_webrtc_ip_whitelist": "Auto-accept IP CIDRs:",
    "rd_webrtc_ip_whitelist_ph": "one CIDR per line, e.g. 192.168.1.0/24",
    "rd_webrtc_tag_filter": "Tag:",
    "rd_webrtc_tag_all": "All",
    "rd_webrtc_edit_tags": "Edit tags...",
    "rd_webrtc_tags_prompt": "Comma-separated tags:",
    "rd_webrtc_view_audit": "Audit log...",
    "rd_webrtc_audit_title": "Audit log",
    "rd_webrtc_audit_filter_type": "Type:",
    "rd_webrtc_audit_filter_type_ph": "auth_ok / auth_fail / file_received / ...",
    "rd_webrtc_audit_filter_host": _HOST_LABEL,
    "rd_webrtc_audit_refresh": "Refresh",
    "rd_webrtc_audit_col_ts": "Timestamp",
    "rd_webrtc_audit_col_type": "Event",
    "rd_webrtc_audit_col_host": "Host",
    "rd_webrtc_audit_col_viewer": "Viewer",
    "rd_webrtc_audit_col_detail": "Detail",
    "rd_webrtc_lan_browse": "LAN...",
    "rd_webrtc_lan_title": "LAN discovery",
    "rd_webrtc_lan_help": "Hosts broadcast on _autocontrol._tcp via mDNS.",
    "rd_webrtc_lan_col_host": "Host ID",
    "rd_webrtc_lan_col_ip": "IP",
    "rd_webrtc_lan_col_signaling": "Signaling URL",
    "rd_webrtc_lan_col_name": "mDNS name",
    "rd_webrtc_lan_use": "Use this",
    "rd_webrtc_host_voice": "Share my voice (host → viewers)",
    "rd_webrtc_pen_off": "Pen Off",
    "rd_webrtc_pen_on": "Pen On",
    "rd_webrtc_pen_clear": "Clear pen",
    "rd_webrtc_sync_group": "Folder sync",
    "rd_webrtc_sync_dir": "Local folder:",
    "rd_webrtc_sync_dir_ph": "directory to mirror to host's inbox",
    "rd_webrtc_sync_start": "Start sync",
    "rd_webrtc_sync_stop": "Stop sync",
    "rd_webrtc_sync_dir_required": "Pick a local folder first",
    "rd_webrtc_browse": "Browse...",

    # Auto Click Tab
    "interval_time": "Interval (ms):",
    "cursor_x": "Cursor X:",
    "cursor_y": "Cursor Y:",
    "mouse_button": "Mouse Button:",
    "keyboard_button": "Keyboard Key:",
    "click_type": "Click Type:",
    "single_click": "Single Click",
    "double_click": "Double Click",
    "input_method": "Input Method:",
    "mouse_radio": "Mouse",
    "keyboard_radio": "Keyboard",
    "repeat_until_stopped_radio": "Repeat until stopped",
    "repeat_radio": "Repeat",
    "times": "Times",
    "start": "Start",
    "stop": "Stop",
    "hotkey_label": "Hotkey (comma separated):",
    "hotkey_send": "Send Hotkey",
    "write_label": "Write Text:",
    "write_send": "Write",
    "mouse_scroll_label": "Scroll Value:",
    "scroll_direction_label": "Scroll Direction:",
    "scroll_send": "Scroll",
    "get_position": "Get Mouse Position",
    "current_position": "Current Position:",

    # Screenshot Tab
    "take_screenshot": "Take Screenshot",
    "save_screenshot": "Save Screenshot",
    "file_path_label": "File Path:",
    "browse": "Browse",
    "region_label": "Region (x1, y1, x2, y2):",
    "pick_region": "Pick Region",
    "crop_template": "Crop Template",
    "get_pixel_label": "Get Pixel Color",
    "pixel_x": "X:",
    "pixel_y": "Y:",
    "pixel_result": "Pixel Color:",
    "screen_size_label": "Screen Size:",
    "get_screen_size": "Get Screen Size",

    # Image Detection Tab
    "template_image": "Template Image:",
    "threshold_label": "Threshold (0.0~1.0):",
    "locate_image": "Locate Image",
    "locate_all": "Locate All",
    "locate_click": "Locate & Click",
    "detection_result": "Detection Result:",
    "draw_image_check": "Draw Detection",

    # Record / Playback Tab
    "start_record": "Start Record",
    "stop_record": "Stop Record",
    "playback": "Playback",
    "save_record": "Save to JSON",
    "load_record": "Load JSON",
    "record_status": "Status:",
    "record_idle": "Idle",
    "record_recording": "Recording...",
    "record_list_label": "Recorded Actions:",

    # Script Executor Tab
    "load_script": "Load Script (JSON)",
    "execute_script": "Execute",
    "execute_dir_label": "Execute Directory:",
    "execute_dir": "Execute All",
    "script_content": "Script Content:",
    "execution_result": "Execution Result:",

    # Screen Recording Tab
    "recorder_name": "Recorder Name:",
    "output_file": "Output File:",
    "codec_label": "Codec:",
    "fps_label": "FPS:",
    "resolution_label": "Resolution (WxH):",
    "start_screen_record": "Start Recording",
    "stop_screen_record": "Stop Recording",
    "screen_record_status": "Status:",

    # Shell Tab
    "shell_command_label": "Shell Command:",
    "execute_shell": "Execute",
    "shell_output": "Output:",
    "start_exe_label": "Executable Path:",
    "start_exe": "Start Executable",

    # Report Tab
    "report_name": "Report Name:",
    "generate_html_report": "Generate HTML Report",
    "generate_json_report": "Generate JSON Report",
    "generate_xml_report": "Generate XML Report",
    "enable_test_record": "Enable Test Record",
    "disable_test_record": "Disable Test Record",
    "test_record_status": "Test Record:",
    "report_result": "Result:",

    # Language
    "language_label": "Language:",

    # Hotkeys Tab
    "hk_combo_label": "Combo:",
    "hk_script_label": _SCRIPT_LABEL,
    "hk_bind": "Bind",
    "hk_remove_selected": _REMOVE_SELECTED,
    "hk_start_daemon": "Start daemon",
    "hk_stop_daemon": "Stop daemon",
    "hk_daemon_stopped": "Daemon stopped",
    "hk_daemon_running": "Daemon running",
    "hk_col_id": "ID",
    "hk_col_combo": "Combo",
    "hk_col_script": "Script",
    "hk_col_fired": "Fired",
    "hk_dialog_select_script": _SELECT_SCRIPT,

    # Triggers Tab
    "tr_script_label": _SCRIPT_LABEL,
    "tr_type_label": "Type:",
    "tr_repeat": "Repeat",
    "tr_add": "Add trigger",
    "tr_remove_selected": _REMOVE_SELECTED,
    "tr_start_engine": "Start engine",
    "tr_stop_engine": "Stop engine",
    "tr_engine_stopped": "Engine stopped",
    "tr_engine_running": "Engine running",
    "tr_type_image": "Image appears",
    "tr_type_window": "Window appears",
    "tr_type_pixel": "Pixel matches",
    "tr_type_file": "File changed",
    "tr_image_label": "Image:",
    "tr_threshold_label": "Threshold:",
    "tr_title_contains_label": "Title contains:",
    "tr_watch_label": "Watch path:",
    "tr_col_id": "ID",
    "tr_col_type": "Type",
    "tr_col_detail": "Detail",
    "tr_col_fired": "Fired",
    "tr_col_enabled": "Enabled",
    "tr_yes": "Yes",
    "tr_no": "No",
    "tr_dialog_select_script": _SELECT_SCRIPT,
    "tr_dialog_select_image": "Select image",
    "tr_dialog_select_file": "Select file to watch",

    # Plugins Tab
    "pl_dir_label": "Plugin dir:",
    "pl_load": "Load + register",
    "pl_no_loaded": "No plugins loaded",
    "pl_registered_label": "Registered commands:",
    "pl_dialog_plugin_dir": "Plugin directory",

    # Scheduler Tab
    "sch_script_label": _SCRIPT_LABEL,
    "sch_interval_label": "Every (s):",
    "sch_repeat": "Repeat",
    "sch_add": "Add",
    "sch_remove_selected": _REMOVE_SELECTED,
    "sch_start": "Start scheduler",
    "sch_stop": "Stop scheduler",
    "sch_status_running": "Scheduler running",
    "sch_status_stopped": "Scheduler stopped",
    "sch_col_job_id": "Job ID",
    "sch_col_script": "Script",
    "sch_col_interval": "Interval (s)",
    "sch_col_runs": "Runs",
    "sch_col_enabled": "Enabled",
    "sch_dialog_select_script": _SELECT_SCRIPT,

    # Socket / REST Tab
    "ss_tcp_group": "TCP socket server",
    "ss_rest_group": "REST API server",
    "ss_host_label": _HOST_LABEL,
    "ss_port_label": _PORT_LABEL,
    "ss_tcp_any_check": "Bind TCP to 0.0.0.0 (exposes to network)",
    "ss_rest_any_check": "Bind REST to 0.0.0.0 (exposes to network)",
    "ss_tcp_stopped": "TCP stopped",
    "ss_rest_stopped": "REST stopped",
    "ss_tcp_start": "Start TCP",
    "ss_tcp_stop": "Stop TCP",
    "ss_rest_start": "Start REST",
    "ss_rest_stop": "Stop REST",

    # Live HUD Tab
    "hud_watchers_group": "Watchers",
    "hud_start": "Start HUD",
    "hud_stop": "Stop HUD",
    "hud_clear": "Clear log",
    "hud_recent_log": "Recent log:",
    "hud_mouse_prefix": "Mouse:",
    "hud_pixel_prefix": "Pixel:",

    # Window Manager Tab
    "win_refresh": "Refresh",
    "win_filter_placeholder": "Filter by title substring",
    "win_col_hwnd": "HWND",
    "win_col_title": "Title",
    "win_focus_selected": "Focus selected",
    "win_close_selected": "Close selected",
    "win_status_count": "{n} windows",

    # Recording Editor Tab
    "re_file_label": "File:",
    "re_browse": "Browse",
    "re_load": "Load",
    "re_save_as": "Save As",
    "re_trim_start": "Trim start:",
    "re_trim_end": "end:",
    "re_apply_trim": "Apply trim",
    "re_remove_selected": _REMOVE_SELECTED,
    "re_delay_x": "Delay x",
    "re_floor_ms": "floor ms:",
    "re_apply_delays": "Apply delays",
    "re_scale_x": "Scale x:",
    "re_scale_y": "y:",
    "re_apply_scale": "Apply scale",
    "re_keep_mouse": "Keep mouse only",
    "re_keep_keyboard": "Keep keyboard only",
    "re_preview": "Preview:",
    "re_dialog_open": "Open recording",
    "re_dialog_save": "Save recording",

    # Script Builder Tab
    "sb_delete": "Delete",
    "sb_up": "Up",
    "sb_down": "Down",
    "sb_load_json": "Load JSON",
    "sb_save_json": "Save JSON",
    "sb_run": "Run",
    "sb_add_step": "Add Step",
    "sb_dialog_save": "Save script",
    "sb_dialog_load": "Load script",
    "sb_no_step_selected": "No step selected",

    # Run History Tab
    "rh_filter_label": "Source:",
    "rh_source_all": "All",
    "rh_source_scheduler": "Scheduler",
    "rh_source_trigger": "Trigger",
    "rh_source_hotkey": "Hotkey",
    "rh_source_manual": "Manual",
    "rh_source_rest": "REST",
    "rh_refresh": "Refresh",
    "rh_clear": "Clear",
    "rh_confirm_clear": "Delete all run history? This cannot be undone.",
    "rh_count_label": "{n} runs",
    "rh_col_id": "ID",
    "rh_col_source": "Source",
    "rh_col_target": "Target",
    "rh_col_script": "Script",
    "rh_col_started": "Started",
    "rh_col_duration": "Duration",
    "rh_col_status": "Status",
    "rh_status_ok": "OK",
    "rh_status_error": "Error",
    "rh_status_running": "Running",
    "rh_col_artifact": "Artifact",
    "rh_open_artifact": "Open artifact",
    "rh_no_artifact": "Selected run has no artifact.",
    "rh_artifact_missing": "Artifact file no longer exists.",

    # Accessibility Tab
    "a11y_app_label": "App:",
    "a11y_app_placeholder": "e.g. Calculator",
    "a11y_name_label": "Name contains:",
    "a11y_name_placeholder": "partial match",
    "a11y_refresh": "Refresh",
    "a11y_click_selected": "Click selected",
    "a11y_col_app": "App",
    "a11y_col_role": "Role",
    "a11y_col_name": "Name",
    "a11y_col_bounds": "Bounds",
    "a11y_col_center": "Center",
    "a11y_count_label": "{n} elements",
    "a11y_no_selection": "Select a row first",
    "a11y_click_not_found": "No matching element to click",

    # VLM (AI Locator) Tab
    "vlm_desc_label": "Describe:",
    "vlm_desc_placeholder": "e.g. the green Submit button",
    "vlm_model_label": "Model:",
    "vlm_model_placeholder": "optional override (e.g. claude-opus-4-7)",
    "vlm_locate": "Locate",
    "vlm_click": "Locate & click",
    "vlm_result": "Match at ({x}, {y})",
    "vlm_ok": "OK",
    "vlm_not_found": "No match found",
    "vlm_error": "Error",
    "vlm_desc_required": "Describe the target first",

    # OCR Reader Tab
    "ocr_region_group": "Region",
    "ocr_region_label": "x, y, w, h:",
    "ocr_region_placeholder": "leave blank for full screen",
    "ocr_pick_region": "Pick region...",
    "ocr_lang_label": "Language:",
    "ocr_min_conf_label": "Min confidence:",
    "ocr_regex_label": "Regex pattern:",
    "ocr_regex_placeholder": r"e.g. Order#\d+",
    "ocr_dump_region": "Dump region text",
    "ocr_find_regex": "Find by regex",
    "ocr_results_label": "Matches:",
    "ocr_match_count": "{n} matches",
    "ocr_region_invalid": "Region must be 4 comma-separated integers",
    "ocr_min_conf_invalid": "Min confidence must be a number",
    "ocr_regex_required": "Enter a regex pattern first",
    "ocr_regex_invalid": "Invalid regex",

    # Variables Tab
    "vars_current_group": "Current scope",
    "vars_col_name": "Name",
    "vars_col_value": "Value",
    "vars_count": "{n} variables",
    "vars_refresh": "Refresh",
    "vars_clear": _CLEAR_ALL,
    "vars_clear_confirm": "Clear every runtime variable?",
    "vars_set_group": "Set one",
    "vars_name_label": "Name:",
    "vars_name_placeholder": "variable name",
    "vars_name_required": "Name is required",
    "vars_value_label": "Value:",
    "vars_value_placeholder": "JSON literal (42, \"text\", [1,2]) or raw string",
    "vars_set_btn": "Set",
    "vars_seed_group": "Seed from JSON",
    "vars_seed_placeholder": "{\"counter\": 0, \"items\": [\"a\", \"b\"]}",
    "vars_seed_btn": "Merge JSON into scope",
    "vars_seed_required": "Paste a JSON object first",
    "vars_seed_invalid": "Invalid JSON",
    "vars_seed_not_object": "Seed JSON must be an object",

    # LLM Planner Tab
    "llm_desc_group": "Describe the task",
    "llm_desc_placeholder": (
        "e.g. open Notepad, type 'hello world', save as test.txt"
    ),
    "llm_model_label": "Model:",
    "llm_model_placeholder": "optional override (e.g. claude-opus-4-7)",
    "llm_plan_btn": "Plan",
    "llm_run_btn": "Run plan",
    "llm_plan_group": "Planned actions",
    "llm_result_group": "Execution result",
    "llm_desc_required": "Describe what you want to automate first",
    "llm_planning": "Planning...",
    "llm_plan_count": "Planned {n} actions",
    "llm_no_plan": "Click Plan first",
    "llm_running": "Running...",
    "llm_run_done": "Done",

    # Remote Desktop Tab
    "rd_host_tab": "Host (this machine)",
    "rd_viewer_tab": "Viewer (control another)",
    "rd_host_security_warning": (
        "WARNING: anyone with the host:port and token gets full mouse / "
        "keyboard control of this machine. Default bind is 127.0.0.1; "
        "expose to a network only via SSH tunnel or trusted VPN."
    ),
    "rd_host_config_group": "Host configuration",
    "rd_viewer_config_group": "Connect to a remote host",
    "rd_token_label": _TOKEN_LABEL,
    "rd_token_placeholder": "shared secret (HMAC key)",
    "rd_token_generate": "Generate",
    "rd_bind_label": "Address:",
    "rd_port_label": _PORT_LABEL,
    "rd_fps_label": "FPS:",
    "rd_quality_label": "JPEG quality:",
    "rd_host_start": "Start host",
    "rd_host_stop": _STOP_HOST,
    "rd_host_status_running": "Running on port {port} — {n} viewer(s)",
    "rd_host_status_stopped": "Host is stopped",
    "rd_host_preview_label": "Preview (what viewers see):",
    "rd_host_card_group": "Connection",
    "rd_viewer_card_group": "Connect to a remote host",
    "rd_host_basics_group": "Connection settings",
    "rd_advanced_group": "Advanced",
    "rd_host_copy_share": "Copy share text",
    "rd_host_copy_share_unavailable": "Start the host first to share its details.",
    "rd_host_copy_share_confirm": (
        "Copying will place the address, port, host ID and TOKEN onto your "
        "clipboard. Anyone you paste this to gains full control of this "
        "machine. Continue?"
    ),
    "rd_badge_running": "RUNNING · :{port} · {n} viewer(s)",
    "rd_badge_stopped": "STOPPED",
    "rd_badge_idle": "NOT CONNECTED",
    "rd_badge_live": "LIVE",
    "rd_host_id_group": "Host ID (share with viewers)",
    "rd_host_id_label": "Host ID:",
    "rd_host_id_copy": "Copy",
    "rd_transport_label": "Transport:",
    "rd_tls_cert_label": "TLS cert:",
    "rd_tls_cert_placeholder": "PEM certificate path (optional)",
    "rd_tls_key_label": "TLS key:",
    "rd_tls_key_placeholder": "PEM private key path (optional)",
    "rd_tls_both_required": "TLS cert and key must both be provided",
    "rd_tls_insecure": "Skip cert verification (self-signed)",
    "rd_browse": "Browse...",
    "rd_enable_audio": "Stream system audio (sounddevice)",
    "rd_viewer_audio_play": "Play received audio (sounddevice)",
    "rd_viewer_push_clipboard": "Push my clipboard text to host",
    "rd_viewer_send_file": "Send file...",
    "rd_dest_path_prompt": "Destination path on remote for {name}:",
    "rd_clipboard_empty": "Local clipboard is empty",
    "rd_clipboard_sent": "Clipboard sent to host",
    "rd_viewer_clipboard_received": "Clipboard updated from host",
    "rd_progress_label": "Transfer: {done} / {total} bytes",
    "rd_progress_done": "Transfer complete: {path}",
    "rd_progress_failed": "Transfer failed: {error}",
    "rd_viewer_connect": "Connect",
    "rd_viewer_disconnect": "Disconnect",
    "rd_viewer_required_fields": (
        "Address, port, and token are all required."
    ),
    "rd_viewer_status_connected": "Connected — receiving frames",
    "rd_viewer_status_idle": "Not connected",
    "rd_viewer_error": "Remote desktop error",

    # Menu bar
    "menu_file": "File",
    "menu_file_open_script": "Open Script...",
    "menu_file_exit": "Exit",
    "menu_view": "View",
    "menu_view_tabs": "Tabs",
    "menu_view_cat_core": "Core",
    "menu_view_cat_editing": "Editing",
    "menu_view_cat_detection": "Detection & Vision",
    "menu_view_cat_automation": "Automation Engines",
    "menu_view_cat_system": "System",
    "menu_view_text_size": "Text Size",
    "menu_view_text_auto": "Auto (screen-based)",
    "menu_view_text_small": "Small (10pt)",
    "menu_view_text_normal": "Normal (12pt)",
    "menu_view_text_large": "Large (14pt)",
    "menu_view_text_xlarge": "Extra Large (16pt)",
    "menu_view_text_xxlarge": "Huge (20pt)",
    "menu_tools": "Tools",
    "menu_tools_start_hotkeys": "Start hotkey daemon",
    "menu_tools_start_scheduler": "Start scheduler",
    "menu_tools_start_triggers": "Start trigger engine",
    "menu_language": "Language",
    "menu_help": "Help",
    "menu_help_about": "About AutoControlGUI",
}
