english_word_dict = {
    # Main
    "application_name": "AutoControlGUI",

    # Tabs
    "tab_auto_click": "Auto Click",
    "tab_screenshot": "Screenshot",
    "tab_image_detect": "Image Detection",
    "tab_record": "Record / Playback",
    "tab_script": "Script Executor",
    "tab_script_builder": "Script Builder",
    "tab_recording_editor": "Recording Editor",
    "tab_window_manager": "Windows",
    "tab_scheduler": "Scheduler",
    "tab_socket_server": "Socket Server",
    "tab_live_hud": "Live HUD",
    "tab_hotkeys": "Hotkeys",
    "tab_triggers": "Triggers",
    "tab_plugins": "Plugins",
    "tab_screen_record": "Screen Recording",
    "tab_shell": "Shell Command",
    "tab_report": "Report",
    "tab_run_history": "Run History",
    "tab_accessibility": "Accessibility",
    "tab_vlm": "AI Locator",

    # Auto Click Tab
    "interval_time": "Interval (ms):",
    "cursor_x": "Cursor X:",
    "cursor_y": "Cursor Y:",
    "mouse_button": "Mouse Button:",
    "keyboard_button": "Keyboard Key:",
    "click_type": "Click Type:",
    "single_click": "Single Click",
    "double_click": "Double Click",
    "input_method": "Input Method:",
    "mouse_radio": "Mouse",
    "keyboard_radio": "Keyboard",
    "repeat_until_stopped_radio": "Repeat until stopped",
    "repeat_radio": "Repeat",
    "times": "Times",
    "start": "Start",
    "stop": "Stop",
    "hotkey_label": "Hotkey (comma separated):",
    "hotkey_send": "Send Hotkey",
    "write_label": "Write Text:",
    "write_send": "Write",
    "mouse_scroll_label": "Scroll Value:",
    "scroll_direction_label": "Scroll Direction:",
    "scroll_send": "Scroll",
    "get_position": "Get Mouse Position",
    "current_position": "Current Position:",

    # Screenshot Tab
    "take_screenshot": "Take Screenshot",
    "save_screenshot": "Save Screenshot",
    "file_path_label": "File Path:",
    "browse": "Browse",
    "region_label": "Region (x1, y1, x2, y2):",
    "pick_region": "Pick Region",
    "crop_template": "Crop Template",
    "get_pixel_label": "Get Pixel Color",
    "pixel_x": "X:",
    "pixel_y": "Y:",
    "pixel_result": "Pixel Color:",
    "screen_size_label": "Screen Size:",
    "get_screen_size": "Get Screen Size",

    # Image Detection Tab
    "template_image": "Template Image:",
    "threshold_label": "Threshold (0.0~1.0):",
    "locate_image": "Locate Image",
    "locate_all": "Locate All",
    "locate_click": "Locate & Click",
    "detection_result": "Detection Result:",
    "draw_image_check": "Draw Detection",

    # Record / Playback Tab
    "start_record": "Start Record",
    "stop_record": "Stop Record",
    "playback": "Playback",
    "save_record": "Save to JSON",
    "load_record": "Load JSON",
    "record_status": "Status:",
    "record_idle": "Idle",
    "record_recording": "Recording...",
    "record_list_label": "Recorded Actions:",

    # Script Executor Tab
    "load_script": "Load Script (JSON)",
    "execute_script": "Execute",
    "execute_dir_label": "Execute Directory:",
    "execute_dir": "Execute All",
    "script_content": "Script Content:",
    "execution_result": "Execution Result:",

    # Screen Recording Tab
    "recorder_name": "Recorder Name:",
    "output_file": "Output File:",
    "codec_label": "Codec:",
    "fps_label": "FPS:",
    "resolution_label": "Resolution (WxH):",
    "start_screen_record": "Start Recording",
    "stop_screen_record": "Stop Recording",
    "screen_record_status": "Status:",

    # Shell Tab
    "shell_command_label": "Shell Command:",
    "execute_shell": "Execute",
    "shell_output": "Output:",
    "start_exe_label": "Executable Path:",
    "start_exe": "Start Executable",

    # Report Tab
    "report_name": "Report Name:",
    "generate_html_report": "Generate HTML Report",
    "generate_json_report": "Generate JSON Report",
    "generate_xml_report": "Generate XML Report",
    "enable_test_record": "Enable Test Record",
    "disable_test_record": "Disable Test Record",
    "test_record_status": "Test Record:",
    "report_result": "Result:",

    # Language
    "language_label": "Language:",

    # Hotkeys Tab
    "hk_combo_label": "Combo:",
    "hk_script_label": "Script:",
    "hk_bind": "Bind",
    "hk_remove_selected": "Remove selected",
    "hk_start_daemon": "Start daemon",
    "hk_stop_daemon": "Stop daemon",
    "hk_daemon_stopped": "Daemon stopped",
    "hk_daemon_running": "Daemon running",
    "hk_col_id": "ID",
    "hk_col_combo": "Combo",
    "hk_col_script": "Script",
    "hk_col_fired": "Fired",
    "hk_dialog_select_script": "Select script",

    # Triggers Tab
    "tr_script_label": "Script:",
    "tr_type_label": "Type:",
    "tr_repeat": "Repeat",
    "tr_add": "Add trigger",
    "tr_remove_selected": "Remove selected",
    "tr_start_engine": "Start engine",
    "tr_stop_engine": "Stop engine",
    "tr_engine_stopped": "Engine stopped",
    "tr_engine_running": "Engine running",
    "tr_type_image": "Image appears",
    "tr_type_window": "Window appears",
    "tr_type_pixel": "Pixel matches",
    "tr_type_file": "File changed",
    "tr_image_label": "Image:",
    "tr_threshold_label": "Threshold:",
    "tr_title_contains_label": "Title contains:",
    "tr_watch_label": "Watch path:",
    "tr_col_id": "ID",
    "tr_col_type": "Type",
    "tr_col_detail": "Detail",
    "tr_col_fired": "Fired",
    "tr_col_enabled": "Enabled",
    "tr_yes": "Yes",
    "tr_no": "No",
    "tr_dialog_select_script": "Select script",
    "tr_dialog_select_image": "Select image",
    "tr_dialog_select_file": "Select file to watch",

    # Plugins Tab
    "pl_dir_label": "Plugin dir:",
    "pl_load": "Load + register",
    "pl_no_loaded": "No plugins loaded",
    "pl_registered_label": "Registered commands:",
    "pl_dialog_plugin_dir": "Plugin directory",

    # Scheduler Tab
    "sch_script_label": "Script:",
    "sch_interval_label": "Every (s):",
    "sch_repeat": "Repeat",
    "sch_add": "Add",
    "sch_remove_selected": "Remove selected",
    "sch_start": "Start scheduler",
    "sch_stop": "Stop scheduler",
    "sch_status_running": "Scheduler running",
    "sch_status_stopped": "Scheduler stopped",
    "sch_col_job_id": "Job ID",
    "sch_col_script": "Script",
    "sch_col_interval": "Interval (s)",
    "sch_col_runs": "Runs",
    "sch_col_enabled": "Enabled",
    "sch_dialog_select_script": "Select script",

    # Socket / REST Tab
    "ss_tcp_group": "TCP socket server",
    "ss_rest_group": "REST API server",
    "ss_host_label": "Host:",
    "ss_port_label": "Port:",
    "ss_tcp_any_check": "Bind TCP to 0.0.0.0 (exposes to network)",
    "ss_rest_any_check": "Bind REST to 0.0.0.0 (exposes to network)",
    "ss_tcp_stopped": "TCP stopped",
    "ss_rest_stopped": "REST stopped",
    "ss_tcp_start": "Start TCP",
    "ss_tcp_stop": "Stop TCP",
    "ss_rest_start": "Start REST",
    "ss_rest_stop": "Stop REST",

    # Live HUD Tab
    "hud_watchers_group": "Watchers",
    "hud_start": "Start HUD",
    "hud_stop": "Stop HUD",
    "hud_clear": "Clear log",
    "hud_recent_log": "Recent log:",
    "hud_mouse_prefix": "Mouse:",
    "hud_pixel_prefix": "Pixel:",

    # Window Manager Tab
    "win_refresh": "Refresh",
    "win_filter_placeholder": "Filter by title substring",
    "win_col_hwnd": "HWND",
    "win_col_title": "Title",
    "win_focus_selected": "Focus selected",
    "win_close_selected": "Close selected",
    "win_status_count": "{n} windows",

    # Recording Editor Tab
    "re_file_label": "File:",
    "re_browse": "Browse",
    "re_load": "Load",
    "re_save_as": "Save As",
    "re_trim_start": "Trim start:",
    "re_trim_end": "end:",
    "re_apply_trim": "Apply trim",
    "re_remove_selected": "Remove selected",
    "re_delay_x": "Delay x",
    "re_floor_ms": "floor ms:",
    "re_apply_delays": "Apply delays",
    "re_scale_x": "Scale x:",
    "re_scale_y": "y:",
    "re_apply_scale": "Apply scale",
    "re_keep_mouse": "Keep mouse only",
    "re_keep_keyboard": "Keep keyboard only",
    "re_preview": "Preview:",
    "re_dialog_open": "Open recording",
    "re_dialog_save": "Save recording",

    # Script Builder Tab
    "sb_delete": "Delete",
    "sb_up": "Up",
    "sb_down": "Down",
    "sb_load_json": "Load JSON",
    "sb_save_json": "Save JSON",
    "sb_run": "Run",
    "sb_add_step": "Add Step",
    "sb_dialog_save": "Save script",
    "sb_dialog_load": "Load script",
    "sb_no_step_selected": "No step selected",

    # Run History Tab
    "rh_filter_label": "Source:",
    "rh_source_all": "All",
    "rh_source_scheduler": "Scheduler",
    "rh_source_trigger": "Trigger",
    "rh_source_hotkey": "Hotkey",
    "rh_source_manual": "Manual",
    "rh_source_rest": "REST",
    "rh_refresh": "Refresh",
    "rh_clear": "Clear",
    "rh_confirm_clear": "Delete all run history? This cannot be undone.",
    "rh_count_label": "{n} runs",
    "rh_col_id": "ID",
    "rh_col_source": "Source",
    "rh_col_target": "Target",
    "rh_col_script": "Script",
    "rh_col_started": "Started",
    "rh_col_duration": "Duration",
    "rh_col_status": "Status",
    "rh_status_ok": "OK",
    "rh_status_error": "Error",
    "rh_status_running": "Running",
    "rh_col_artifact": "Artifact",
    "rh_open_artifact": "Open artifact",
    "rh_no_artifact": "Selected run has no artifact.",
    "rh_artifact_missing": "Artifact file no longer exists.",

    # Accessibility Tab
    "a11y_app_label": "App:",
    "a11y_app_placeholder": "e.g. Calculator",
    "a11y_name_label": "Name contains:",
    "a11y_name_placeholder": "partial match",
    "a11y_refresh": "Refresh",
    "a11y_click_selected": "Click selected",
    "a11y_col_app": "App",
    "a11y_col_role": "Role",
    "a11y_col_name": "Name",
    "a11y_col_bounds": "Bounds",
    "a11y_col_center": "Center",
    "a11y_count_label": "{n} elements",
    "a11y_no_selection": "Select a row first",
    "a11y_click_not_found": "No matching element to click",

    # VLM (AI Locator) Tab
    "vlm_desc_label": "Describe:",
    "vlm_desc_placeholder": "e.g. the green Submit button",
    "vlm_model_label": "Model:",
    "vlm_model_placeholder": "optional override (e.g. claude-opus-4-7)",
    "vlm_locate": "Locate",
    "vlm_click": "Locate & click",
    "vlm_result": "Match at ({x}, {y})",
    "vlm_ok": "OK",
    "vlm_not_found": "No match found",
    "vlm_error": "Error",
    "vlm_desc_required": "Describe the target first",

    # Menu bar
    "menu_file": "File",
    "menu_file_open_script": "Open Script...",
    "menu_file_exit": "Exit",
    "menu_view": "View",
    "menu_view_tabs": "Tabs",
    "menu_tools": "Tools",
    "menu_tools_start_hotkeys": "Start hotkey daemon",
    "menu_tools_start_scheduler": "Start scheduler",
    "menu_tools_start_triggers": "Start trigger engine",
    "menu_language": "Language",
    "menu_help": "Help",
    "menu_help_about": "About AutoControlGUI",
}
