_SCRIPT = "スクリプト"
_SCRIPT_LABEL = "スクリプト:"
_REMOVE_SELECTED = "選択項目を削除"
_SELECT_SCRIPT = "スクリプトを選択"
_TOKEN_LABEL = "トークン:"
_STOP_HOST_JA = "ホスト停止"
_CLEAR_ALL_JA = "すべて削除"

japanese_word_dict = {
    "application_name": "AutoControlGUI",

    # Tabs
    "tab_auto_click": "自動クリック",
    "tab_screenshot": "スクリーンショット",
    "tab_image_detect": "画像検出",
    "tab_record": "記録 / 再生",
    "tab_script": "スクリプト実行",
    "tab_script_builder": "スクリプトビルダー",
    "tab_recording_editor": "記録エディタ",
    "tab_window_manager": "ウィンドウ管理",
    "tab_scheduler": "スケジューラー",
    "tab_socket_server": "ソケットサーバー",
    "tab_live_hud": "ライブ HUD",
    "tab_hotkeys": "ホットキー",
    "tab_triggers": "トリガー",
    "tab_webhooks": "Webhook",
    "tab_email_triggers": "Email トリガー",
    "tab_plugins": "プラグイン",
    "tab_screen_record": "画面録画",
    "tab_shell": "シェル",
    "tab_report": "レポート",
    "tab_run_history": "実行履歴",
    "tab_profiler": "プロファイラ",
    "tab_secrets": "シークレット",
    "tab_accessibility": "アクセシビリティ",
    "tab_vlm": "AI ロケーター",
    "tab_ocr_reader": "OCR リーダー",
    "tab_variables": "実行時変数",
    "tab_llm_planner": "LLM プランナー",
    "tab_remote_desktop": "リモートデスクトップ",
    "tab_rest_api": "REST API",
    "tab_admin_console": "管理コンソール",
    "tab_audit_log": "監査ログ",
    "tab_inspector": "パケット監視",
    "tab_usb_devices": "USB デバイス",
    "tab_diagnostics": "診断",

    # 診断タブ
    "diag_run": "診断を実行",
    "diag_summary_ok": "{count} 件すべて合格。",
    "diag_summary_failed": "{count} 件中 {failed} 件失敗。",
    "diag_col_name": "チェック",
    "diag_col_severity": "重大度",
    "diag_col_status": "状態",
    "diag_col_detail": "詳細",
    "diag_status_ok": "OK",
    "diag_status_fail": "失敗",

    # USB デバイスタブ
    "usb_backend_label": "バックエンド:",
    "usb_refresh": "更新",
    "usb_col_vid": "VID",
    "usb_col_pid": "PID",
    "usb_col_manufacturer": "メーカー",
    "usb_col_product": "製品名",
    "usb_col_serial": "シリアル",
    "usb_col_location": "バス / 位置",
    "usb_auto_refresh": "自動更新 + ホットプラグ監視",
    "usb_events_idle": "ホットプラグ監視中：前回更新以降の変化なし。",
    "usb_events_recent": "最近のホットプラグ：{text}",

    # USB passthrough ACL プロンプト ダイアログ
    "usb_prompt_title": "USB デバイス使用要求",
    "usb_prompt_intro": "リモート viewer がこのホストの USB デバイスの占有を要求しています。要求を認識できる場合のみ許可してください。",
    "usb_prompt_vendor": "Vendor ID:",
    "usb_prompt_product": "Product ID:",
    "usb_prompt_serial": "シリアル:",
    "usb_prompt_viewer": "Viewer ID:",
    "usb_prompt_remember": "この決定を記憶する（恒久的な ACL ルールを書き込む）",
    "usb_prompt_allow": "許可",
    "usb_prompt_deny": "拒否",
    "tab_usb_browser": "USB ブラウザ",

    # USB ブラウザ（viewer 側）
    "usb_browser_target_group": "リモートホスト",
    "usb_browser_url": "REST URL:",
    "usb_browser_token": "ベアラートークン:",
    "usb_browser_fetch": "デバイス取得",
    "usb_browser_open": "選択を開く",
    "usb_browser_fetching": "取得中…",
    "usb_browser_fetched": "{count} デバイスを取得しました。",
    "usb_browser_fetch_failed": "取得失敗：{error}",
    "usb_browser_col_vid": "VID",
    "usb_browser_col_pid": "PID",
    "usb_browser_col_manufacturer": "メーカー",
    "usb_browser_col_product": "製品名",
    "usb_browser_col_serial": "シリアル",
    "usb_browser_open_select_first": "先に行を選択してください。",
    "usb_browser_open_unwired": "Open には WebRTC usb DataChannel が必要です。このビルドではまだ接続されていません。",

    # 監視タブ
    "inspector_metrics_group": "集約メトリクス",
    "inspector_summary_text": "{count} サンプル / {window:.1f} 秒",
    "inspector_metric_rtt_ms": "RTT (ms)",
    "inspector_metric_fps": "FPS",
    "inspector_metric_bitrate_kbps": "ビットレート (kbps)",
    "inspector_metric_packet_loss_pct": "パケットロス (%)",
    "inspector_metric_jitter_ms": "ジッタ (ms)",
    "inspector_refresh": "更新",
    "inspector_reset": "リセット",
    "inspector_col_age": "経過",

    # 監査ログタブ
    "audit_filter_group": "フィルター",
    "audit_filter_type": "イベント種別:",
    "audit_filter_host": "ホスト ID:",
    "audit_filter_limit": "件数:",
    "audit_refresh": "更新",
    "audit_verify": "チェーン検証",
    "audit_clear": "ログを消去",
    "audit_clear_confirm": "全ての監査行を削除しますか？元に戻せません。",
    "audit_clear_done": "{count} 行を削除しました。",
    "audit_verify_ok": "チェーン正常 ({total} 行)。",
    "audit_verify_broken": "ID {row_id} で改ざん検出 (全 {total} 行)。",
    "audit_col_ts": "時刻",
    "audit_col_type": "イベント",
    "audit_col_host": "ホスト ID",
    "audit_col_viewer": "ビューア ID",
    "audit_col_detail": "詳細",

    # 管理コンソールタブ
    "admin_add_group": "ホストを登録",
    "admin_add": "追加",
    "admin_remove": "選択を削除",
    "admin_refresh": "全件ポーリング",
    "admin_label": "ラベル:",
    "admin_url": "ベース URL:",
    "admin_token": _TOKEN_LABEL,
    "admin_broadcast_group": "ブロードキャスト",
    "admin_actions_label": "アクション JSON (全ホストへ送信):",
    "admin_broadcast_run": "全ホストで実行",
    "admin_results_label": "ホスト別結果:",
    "admin_col_label": "ラベル",
    "admin_col_url": "URL",
    "admin_col_health": "状態",
    "admin_col_latency": "レイテンシ",
    "admin_col_jobs": "ジョブ",
    "admin_health_ok": "OK",
    "admin_health_down": "停止",

    # REST API tab
    "rest_config_group": "REST API 設定",
    "rest_status_group": "REST API 状態",
    "rest_host": "ホスト:",
    "rest_port": "ポート:",
    "rest_token": _TOKEN_LABEL,
    "rest_token_ph": "空欄で自動生成",
    "rest_enable_audit": "監査ログを記録",
    "rest_start": "開始",
    "rest_stop": "停止",
    "rest_copy_url": "URL をコピー",
    "rest_copy_token": "トークンをコピー",
    "rest_url": "URL:",
    "rest_active_token": "ベアラートークン:",
    "rest_running": "REST API は稼働中です。",
    "rest_stopped": "REST API は停止しています。",
    "rest_config_export": "設定をエクスポート",
    "rest_config_import": "設定をインポート",
    "rest_config_export_done": "{count} ファイルを {path} に書き出しました。",
    "rest_config_import_confirm": "このバンドルでユーザー設定を置き換えますか？既存ファイルは .bak.<時刻> にリネームされます。",
    "rest_config_import_done": "{written} ファイル書き込み、{skipped} スキップ。",

    # Remote Desktop — WebRTC サブタブ
    "rd_webrtc_host_tab": "WebRTC ホスト",
    "rd_webrtc_viewer_tab": "WebRTC ビューア",
    "rd_webrtc_config_group": "WebRTC 設定",
    "rd_webrtc_monitor_label": "モニタ番号:",
    "rd_webrtc_generate_offer": "オファー生成",
    "rd_webrtc_offer_label": "Offer SDP（ビューアに渡す）:",
    "rd_webrtc_answer_input_label": "ビューアの Answer SDP を貼り付け:",
    "rd_webrtc_paste_answer": "Answer SDP をここに貼り付け",
    "rd_webrtc_apply_answer": "Answer 適用",
    "rd_webrtc_stop_host": _STOP_HOST_JA,
    "rd_webrtc_offer_input_label": "ホストの Offer SDP を貼り付け:",
    "rd_webrtc_paste_offer": "Offer SDP をここに貼り付け",
    "rd_webrtc_create_answer": "Answer 生成",
    "rd_webrtc_stop_viewer": "ビューア停止",
    "rd_webrtc_answer_label": "Answer SDP（ホストに渡す）:",
    "rd_webrtc_status_idle": "アイドル",
    "rd_webrtc_state_label": "状態:",
    "rd_webrtc_generating_offer": "オファー生成中...",
    "rd_webrtc_offer_ready": "Offer 準備完了 — コピーしてビューアへ",
    "rd_webrtc_creating_answer": "Answer 生成中...",
    "rd_webrtc_answer_ready": "Answer 準備完了 — コピーしてホストへ",
    "rd_webrtc_answer_applied": "Answer 適用、ビューア認証待ち",
    "rd_webrtc_auth_ok": "認証成功",
    "rd_webrtc_auth_fail": "認証失敗",
    "rd_webrtc_token_required": "トークンが必要",
    "rd_webrtc_no_offer_yet": "先に offer を生成してください",
    "rd_webrtc_no_answer": "先にビューアの answer SDP を貼り付けてください",
    "rd_webrtc_no_offer": "先にホストの offer SDP を貼り付けてください",
    "rd_webrtc_unavailable": (
        "WebRTC が利用不可 — pip install je_auto_control[webrtc] を実行"
    ),
    "rd_webrtc_signaling_group": "シグナリングサーバ経由で接続（推奨）",
    "rd_webrtc_manual_group": "SDP 手動交換（フォールバック）",
    "rd_webrtc_advanced_group": "詳細（STUN / TURN）",
    "rd_webrtc_server_label": "Server URL:",
    "rd_webrtc_host_id_label": "Host ID:",
    "rd_webrtc_host_id_placeholder": "ホストに表示される 8 文字 ID",
    "rd_webrtc_secret_label": "サーバ秘密鍵:",
    "rd_webrtc_regen_id": "新 ID",
    "rd_webrtc_publish_via_server": "公開してビューア接続を待つ",
    "rd_webrtc_connect_via_server": "ホストへ接続",
    "rd_webrtc_stun_label": "STUN URL:",
    "rd_webrtc_turn_label": "TURN URL:",
    "rd_webrtc_turn_placeholder": "turn:turn.example.com:3478 (任意)",
    "rd_webrtc_turn_user_label": "TURN ユーザ:",
    "rd_webrtc_turn_cred_label": "TURN 鍵:",
    "rd_webrtc_publishing_offer": "オファーを公開、ビューアの応答待ち...",
    "rd_webrtc_polling_offer": "ホストのオファーを問い合わせ中...",
    "rd_webrtc_pushing_answer": "Answer をサーバへ送信中...",
    "rd_webrtc_waiting_auth": "Answer 送信、ホスト承認待ち",
    "rd_webrtc_pending_viewer_prompt": (
        "正しいトークンで接続要求がありました。"
        "このマシンの操作を許可しますか？"
    ),
    "rd_webrtc_server_required": "シグナリングサーバ URL が必要",
    "rd_webrtc_host_id_required": "Host ID が必要",
    # 信頼リスト / 受け入れダイアログ
    "rd_webrtc_trusted_group": "信頼済みビューア（自動承認）",
    "rd_webrtc_remove_trusted": "選択を削除",
    "rd_webrtc_clear_trusted": _CLEAR_ALL_JA,
    "rd_webrtc_clear_trust_confirm": "信頼済みビューアをすべて削除しますか？",
    "rd_webrtc_pending_viewer_title": "新規接続要求",
    "rd_webrtc_reject": "拒否",
    "rd_webrtc_accept_once": "今回のみ承認",
    "rd_webrtc_accept_and_trust": "承認＆信頼",
    # アドレス帳
    "rd_webrtc_address_book_group": "保存済みホスト",
    "rd_webrtc_connect_selected": "接続",
    "rd_webrtc_save_current": "現在を保存",
    "rd_webrtc_remove_selected": "削除",
    "rd_webrtc_no_address_selected": "ホストを選択してください",
    "rd_webrtc_save_address_missing_fields": (
        "保存には Server URL と Host ID が必要です"
    ),
    # 詳細
    "rd_webrtc_show_cursor": "ストリームにカーソルを表示",
    "rd_webrtc_blank_screen": "セッション中にローカル画面を覆う",
    "rd_webrtc_blanking_banner": "この画面はリモートで閲覧されています",
    "rd_webrtc_send_cad": "Ctrl+Alt+Del 送信",
    "rd_webrtc_cad_not_connected": "Ctrl+Alt+Del 送信前に接続してください",
    # (A) batch
    "rd_webrtc_read_only": "読み取り専用（ビューア入力を破棄）",
    "rd_webrtc_bandwidth_label": "帯域:",
    "rd_webrtc_wake_on_lan": "Wake on LAN",
    "rd_webrtc_wol_mac_prompt": "対象 MAC (AA:BB:CC:DD:EE:FF):",
    "rd_webrtc_wol_broadcast_prompt": "ブロードキャストアドレス:",
    "rd_webrtc_wol_sent": "マジックパケットを送信しました",
    "rd_webrtc_start_recording": "セッション録画",
    "rd_webrtc_stop_recording": "録画停止",
    "rd_webrtc_recording_save_as": "録画ファイル保存先",
    "rd_webrtc_recording_saved": "録画を保存しました: {path}",
    "rd_webrtc_stats_idle": "（統計データなし）",
    # (B) batch
    "rd_webrtc_hw_codec_label": "ハードウェアコーデック:",
    "rd_webrtc_hw_codec_off": "オフ（libx264 使用）",
    "rd_webrtc_hw_codec_off_status": "ハードウェア無効（libx264 使用中）",
    "rd_webrtc_hw_codec_active": "ハードウェア有効: {codec}",
    "rd_webrtc_hw_codec_failed": "ハードウェア {codec} は利用不可",
    "rd_webrtc_adaptive": "ネットワークに応じて FPS 自動調整",
    "rd_webrtc_sessions_count": "接続中ビューア: {n}",
    "rd_webrtc_send_mic": "マイク送信",
    "rd_webrtc_recv_mic": "ビューアのマイクを再生",
    "rd_webrtc_send_file": "ファイル送信...",
    "rd_webrtc_file_sent": "送信済み: {name}",
    "rd_webrtc_push_file": "ビューアにファイルを送信...",
    "rd_webrtc_no_viewers": "送信先のビューアがありません",
    "rd_webrtc_push_done": "{name} を {n} 人のビューアに送信しました",
    "rd_webrtc_file_received": "受信: {name}",
    # リモートファイル一覧
    "rd_webrtc_remote_files_group": "ホストの受信ファイル",
    "rd_webrtc_browse_refresh": "更新",
    "rd_webrtc_browse_pull": "ダウンロード",
    "rd_webrtc_browse_delete": "削除",
    "rd_webrtc_browse_col_name": "名前",
    "rd_webrtc_browse_col_size": "サイズ (bytes)",
    "rd_webrtc_browse_col_mtime": "更新日時",
    "rd_webrtc_browse_delete_confirm": "ホストの受信箱から '{name}' を削除しますか？",
    "rd_webrtc_browse_op_ok": "{name} 完了",
    "rd_webrtc_browse_op_failed": "{name} 失敗: {error}",
    "rd_webrtc_browse_dnd_hint": "ファイルをここにドロップしてホスト受信箱へアップロード。",
    "rd_webrtc_browse_copy_name": "名前をコピー",
    "rd_webrtc_browse_delete_many_confirm": "ホスト受信箱から {n} 件削除しますか？",
    "rd_webrtc_upload_done": "{n} 件アップロードしました",
    # 逆方向の画面共有
    "rd_webrtc_accept_viewer_video": "ビューアの画面共有を受信",
    "rd_webrtc_share_my_screen": "自分の画面をホストへ共有",
    "rd_webrtc_viewer_screen_title": "ビューアの画面",
    "rd_webrtc_accept_opus_audio": "ビューアの Opus 音声を受信",
    "rd_webrtc_share_opus_mic": "Opus でマイクをホストへ共有",
    # KnownHosts ダイアログ
    "rd_webrtc_manage_known_hosts": "既知ホスト...",
    "rd_webrtc_known_hosts_title": "既知ホスト",
    "rd_webrtc_kh_col_host": "Host ID",
    "rd_webrtc_kh_col_app_fp": "App fingerprint",
    "rd_webrtc_kh_col_dtls_fp": "DTLS fingerprint",
    "rd_webrtc_kh_forget": "選択を忘れる",
    "rd_webrtc_kh_clear_all": _CLEAR_ALL_JA,
    "rd_webrtc_kh_close": "閉じる",
    "rd_webrtc_kh_clear_confirm": "全ての既知ホストを忘れますか？",
    "rd_webrtc_kh_copy_app": "App fp コピー",
    "rd_webrtc_kh_copy_dtls": "DTLS fp コピー",
    "rd_webrtc_kh_add": "手動で追加",
    "rd_webrtc_kh_add_host_ph": "host_id (例: abcd1234)",
    "rd_webrtc_kh_add_app_ph": "app fingerprint (64 hex; 任意)",
    "rd_webrtc_kh_add_dtls_ph": "DTLS fingerprint (AB:CD:...; 任意)",
    "rd_webrtc_auto_reconnect": "切断時に自動再接続",
    "rd_webrtc_reconnecting": "再接続中 ({n}/{max} 回目)...",
    "rd_webrtc_reconnect_giveup": "再接続上限に達しました",
    "rd_webrtc_reconnect_max": "最大回数:",
    "rd_webrtc_reconnect_delay": "初期遅延:",
    "rd_webrtc_kh_import": "インポート...",
    "rd_webrtc_kh_export": "エクスポート...",
    "rd_webrtc_kh_import_bad": "インポートしたファイルが known-hosts JSON ではありません",
    "rd_webrtc_kh_import_overwrite": "'{host}' は既に存在。上書きしますか?",
    "rd_webrtc_kh_import_done": "{added} 件インポート、{skipped} 件スキップ",
    "rd_webrtc_quality_unknown": "品質データなし",
    "rd_webrtc_quality_good": "良好 (RTT < 80ms, 損失 < 1%)",
    "rd_webrtc_quality_fair": "普通 (RTT < 200ms, 損失 < 5%)",
    "rd_webrtc_quality_poor": "悪い (RTT 高 / 損失多)",
    "rd_webrtc_kh_col_last_seen": "最終接続",
    "rd_webrtc_sess_col_id": "Session",
    "rd_webrtc_sess_col_viewer": "Viewer ID",
    "rd_webrtc_sess_col_state": "状態",
    "rd_webrtc_sess_col_connected": "接続時刻",
    "rd_webrtc_disconnect_selected": "選択中のセッションを切断",
    "rd_webrtc_kh_stale_tip": "90 日以上未接続 — 再確認を推奨",
    "rd_webrtc_kh_forget_stale": "古いエントリを削除",
    "rd_webrtc_kh_forget_stale_confirm": "{n} 件の古いエントリを削除しますか？",
    "rd_webrtc_kh_no_stale": "削除対象なし",
    "rd_webrtc_sess_trust_viewer": "このビューアを信頼",
    "rd_webrtc_sess_copy_id": "session id をコピー",
    "rd_webrtc_favorite": "お気に入りに追加 ★",
    "rd_webrtc_unfavorite": "お気に入りから削除",
    "rd_webrtc_trust_import": "インポート...",
    "rd_webrtc_trust_export": "エクスポート...",
    "rd_webrtc_trust_import_done": "{n} 件の信頼ビューアをインポート",
    "rd_webrtc_my_fingerprint": "自分の fingerprint:",
    "rd_webrtc_copy_fingerprint": "コピー",
    "rd_webrtc_ab_export": "アドレス帳エクスポート...",
    "rd_webrtc_ab_import": "アドレス帳インポート...",
    "rd_webrtc_ab_clear": _CLEAR_ALL_JA,
    "rd_webrtc_ab_clear_confirm": "アドレス帳全件削除しますか？",
    "rd_webrtc_ab_import_done": "{n} 件インポート完了",
    "rd_webrtc_tray_idle": "AutoControl host: アイドル",
    "rd_webrtc_tray_running": "AutoControl host: {n} ビューア",
    "rd_webrtc_tray_open": "ウィンドウを開く",
    "rd_webrtc_tray_stop": _STOP_HOST_JA,
    "rd_webrtc_tray_quit": "終了",
    "rd_webrtc_region_label": "領域 (x,y,w,h):",
    "rd_webrtc_region_placeholder": "全画面なら空欄",
    "rd_webrtc_pick_region": "領域を選択...",
    "rd_webrtc_monitor_all": "全モニタ",
    "rd_webrtc_max_bitrate": "最大帯域:",
    "rd_webrtc_ip_whitelist": "自動承認 IP CIDR:",
    "rd_webrtc_ip_whitelist_ph": "1 行 1 CIDR、例 192.168.1.0/24",
    "rd_webrtc_tag_filter": "タグ:",
    "rd_webrtc_tag_all": "すべて",
    "rd_webrtc_edit_tags": "タグ編集...",
    "rd_webrtc_tags_prompt": "カンマ区切りのタグ:",
    "rd_webrtc_view_audit": "監査ログ...",
    "rd_webrtc_audit_title": "監査ログ",
    "rd_webrtc_audit_filter_type": "イベント種別:",
    "rd_webrtc_audit_filter_type_ph": "auth_ok / auth_fail / file_received / ...",
    "rd_webrtc_audit_filter_host": "Host:",
    "rd_webrtc_audit_refresh": "更新",
    "rd_webrtc_audit_col_ts": "タイムスタンプ",
    "rd_webrtc_audit_col_type": "イベント",
    "rd_webrtc_audit_col_host": "Host",
    "rd_webrtc_audit_col_viewer": "Viewer",
    "rd_webrtc_audit_col_detail": "詳細",
    "rd_webrtc_lan_browse": "LAN...",
    "rd_webrtc_lan_title": "LAN 検索",
    "rd_webrtc_lan_help": "ホストは mDNS で _autocontrol._tcp を広告します。",
    "rd_webrtc_lan_col_host": "Host ID",
    "rd_webrtc_lan_col_ip": "IP",
    "rd_webrtc_lan_col_signaling": "Signaling URL",
    "rd_webrtc_lan_col_name": "mDNS 名",
    "rd_webrtc_lan_use": "これを使用",
    "rd_webrtc_host_voice": "自分の声を送る (host → viewers)",
    "rd_webrtc_pen_off": "ペン オフ",
    "rd_webrtc_pen_on": "ペン オン",
    "rd_webrtc_pen_clear": "ペンをクリア",
    "rd_webrtc_sync_group": "フォルダ同期",
    "rd_webrtc_sync_dir": "ローカルフォルダ:",
    "rd_webrtc_sync_dir_ph": "ホストの受信箱にミラーするディレクトリ",
    "rd_webrtc_sync_start": "同期開始",
    "rd_webrtc_sync_stop": "同期停止",
    "rd_webrtc_sync_dir_required": "ローカルフォルダを選択してください",
    "rd_webrtc_browse": "参照...",

    # Auto Click Tab
    "interval_time": "間隔 (ms):",
    "cursor_x": "カーソル X:",
    "cursor_y": "カーソル Y:",
    "mouse_button": "マウスボタン:",
    "keyboard_button": "キーボード:",
    "click_type": "クリックタイプ:",
    "single_click": "シングルクリック",
    "double_click": "ダブルクリック",
    "input_method": "入力方式:",
    "mouse_radio": "マウス",
    "keyboard_radio": "キーボード",
    "repeat_until_stopped_radio": "停止まで繰り返し",
    "repeat_radio": "繰り返し",
    "times": "回数",
    "start": "開始",
    "stop": "停止",
    "hotkey_label": "ホットキー（カンマ区切り）:",
    "hotkey_send": "ホットキー送信",
    "write_label": "テキスト入力:",
    "write_send": "入力",
    "mouse_scroll_label": "スクロール値:",
    "scroll_direction_label": "スクロール方向:",
    "scroll_send": "スクロール",
    "get_position": "マウス位置取得",
    "current_position": "現在位置:",

    # Screenshot Tab
    "take_screenshot": "スクリーンショット撮影",
    "save_screenshot": "スクリーンショット保存",
    "file_path_label": "ファイルパス:",
    "browse": "参照",
    "region_label": "領域 (x1, y1, x2, y2):",
    "pick_region": "領域選択",
    "crop_template": "テンプレート切り抜き",
    "get_pixel_label": "ピクセル色取得",
    "pixel_x": "X:",
    "pixel_y": "Y:",
    "pixel_result": "ピクセル色:",
    "screen_size_label": "画面サイズ:",
    "get_screen_size": "画面サイズ取得",

    # Image Detection Tab
    "template_image": "テンプレート画像:",
    "threshold_label": "閾値 (0.0~1.0):",
    "locate_image": "画像検索",
    "locate_all": "全て検索",
    "locate_click": "検索してクリック",
    "detection_result": "検出結果:",
    "draw_image_check": "検出結果を描画",

    # Record / Playback Tab
    "start_record": "記録開始",
    "stop_record": "記録停止",
    "playback": "再生",
    "save_record": "JSON 保存",
    "load_record": "JSON 読込",
    "record_status": "状態:",
    "record_idle": "待機",
    "record_recording": "記録中...",
    "record_list_label": "記録済みアクション:",

    # Script Executor Tab
    "load_script": "スクリプト読込 (JSON)",
    "execute_script": "実行",
    "execute_dir_label": "実行ディレクトリ:",
    "execute_dir": "全て実行",
    "script_content": "スクリプト内容:",
    "execution_result": "実行結果:",

    # Screen Recording Tab
    "recorder_name": "レコーダー名:",
    "output_file": "出力ファイル:",
    "codec_label": "コーデック:",
    "fps_label": "FPS:",
    "resolution_label": "解像度 (幅x高さ):",
    "start_screen_record": "録画開始",
    "stop_screen_record": "録画停止",
    "screen_record_status": "状態:",

    # Shell Tab
    "shell_command_label": "シェルコマンド:",
    "execute_shell": "実行",
    "shell_output": "出力:",
    "start_exe_label": "実行ファイルパス:",
    "start_exe": "実行ファイル起動",

    # Report Tab
    "report_name": "レポート名:",
    "generate_html_report": "HTML レポート生成",
    "generate_json_report": "JSON レポート生成",
    "generate_xml_report": "XML レポート生成",
    "enable_test_record": "テスト記録を有効化",
    "disable_test_record": "テスト記録を無効化",
    "test_record_status": "テスト記録:",
    "report_result": "結果:",

    # Hotkeys Tab
    "hk_combo_label": "組合せ:",
    "hk_script_label": _SCRIPT_LABEL,
    "hk_bind": "バインド",
    "hk_remove_selected": _REMOVE_SELECTED,
    "hk_start_daemon": "デーモン開始",
    "hk_stop_daemon": "デーモン停止",
    "hk_daemon_stopped": "デーモン停止中",
    "hk_daemon_running": "デーモン実行中",
    "hk_col_id": "ID",
    "hk_col_combo": "組合せ",
    "hk_col_script": _SCRIPT,
    "hk_col_fired": "発火",
    "hk_dialog_select_script": _SELECT_SCRIPT,

    # Triggers Tab
    "tr_script_label": _SCRIPT_LABEL,
    "tr_type_label": "タイプ:",
    "tr_repeat": "繰り返し",
    "tr_add": "トリガー追加",
    "tr_remove_selected": _REMOVE_SELECTED,
    "tr_start_engine": "エンジン開始",
    "tr_stop_engine": "エンジン停止",
    "tr_engine_stopped": "エンジン停止中",
    "tr_engine_running": "エンジン実行中",
    "tr_type_image": "画像出現",
    "tr_type_window": "ウィンドウ出現",
    "tr_type_pixel": "ピクセル一致",
    "tr_type_file": "ファイル変更",
    "tr_image_label": "画像:",
    "tr_threshold_label": "閾値:",
    "tr_title_contains_label": "タイトルに含む:",
    "tr_watch_label": "監視パス:",
    "tr_col_id": "ID",
    "tr_col_type": "タイプ",
    "tr_col_detail": "詳細",
    "tr_col_fired": "発火",
    "tr_col_enabled": "有効",
    "tr_yes": "はい",
    "tr_no": "いいえ",
    "tr_dialog_select_script": _SELECT_SCRIPT,
    "tr_dialog_select_image": "画像を選択",
    "tr_dialog_select_file": "監視するファイルを選択",

    # Plugins Tab
    "pl_dir_label": "プラグインディレクトリ:",
    "pl_load": "読込と登録",
    "pl_no_loaded": "プラグイン未読込",
    "pl_registered_label": "登録済みコマンド:",
    "pl_dialog_plugin_dir": "プラグインディレクトリ",

    # Scheduler Tab
    "sch_script_label": _SCRIPT_LABEL,
    "sch_interval_label": "毎 (秒):",
    "sch_repeat": "繰り返し",
    "sch_add": "追加",
    "sch_remove_selected": _REMOVE_SELECTED,
    "sch_start": "スケジューラー開始",
    "sch_stop": "スケジューラー停止",
    "sch_status_running": "スケジューラー実行中",
    "sch_status_stopped": "スケジューラー停止中",
    "sch_col_job_id": "ジョブ ID",
    "sch_col_script": _SCRIPT,
    "sch_col_interval": "間隔 (秒)",
    "sch_col_runs": "実行回数",
    "sch_col_enabled": "有効",
    "sch_dialog_select_script": _SELECT_SCRIPT,

    # Socket / REST Tab
    "ss_tcp_group": "TCP ソケットサーバー",
    "ss_rest_group": "REST API サーバー",
    "ss_host_label": "ホスト:",
    "ss_port_label": "ポート:",
    "ss_tcp_any_check": "TCP を 0.0.0.0 にバインド（ネットワーク公開）",
    "ss_rest_any_check": "REST を 0.0.0.0 にバインド（ネットワーク公開）",
    "ss_tcp_stopped": "TCP 停止中",
    "ss_rest_stopped": "REST 停止中",
    "ss_tcp_start": "TCP 開始",
    "ss_tcp_stop": "TCP 停止",
    "ss_rest_start": "REST 開始",
    "ss_rest_stop": "REST 停止",

    # Live HUD Tab
    "hud_watchers_group": "ウォッチャー",
    "hud_start": "HUD 開始",
    "hud_stop": "HUD 停止",
    "hud_clear": "ログクリア",
    "hud_recent_log": "最近のログ:",
    "hud_mouse_prefix": "マウス:",
    "hud_pixel_prefix": "ピクセル:",

    # Window Manager Tab
    "win_refresh": "更新",
    "win_filter_placeholder": "タイトル部分文字列でフィルタ",
    "win_col_hwnd": "HWND",
    "win_col_title": "タイトル",
    "win_focus_selected": "選択項目をフォーカス",
    "win_close_selected": "選択項目を閉じる",
    "win_status_count": "{n} ウィンドウ",

    # Recording Editor Tab
    "re_file_label": "ファイル:",
    "re_browse": "参照",
    "re_load": "読込",
    "re_save_as": "名前を付けて保存",
    "re_trim_start": "トリム開始:",
    "re_trim_end": "終了:",
    "re_apply_trim": "トリム適用",
    "re_remove_selected": _REMOVE_SELECTED,
    "re_delay_x": "ディレイ倍率",
    "re_floor_ms": "下限 ms:",
    "re_apply_delays": "ディレイ適用",
    "re_scale_x": "スケール x:",
    "re_scale_y": "y:",
    "re_apply_scale": "スケール適用",
    "re_keep_mouse": "マウスのみ保持",
    "re_keep_keyboard": "キーボードのみ保持",
    "re_preview": "プレビュー:",
    "re_dialog_open": "記録を開く",
    "re_dialog_save": "記録を保存",

    # Script Builder Tab
    "sb_delete": "削除",
    "sb_up": "上へ",
    "sb_down": "下へ",
    "sb_load_json": "JSON 読込",
    "sb_save_json": "JSON 保存",
    "sb_run": "実行",
    "sb_add_step": "ステップ追加",
    "sb_dialog_save": "スクリプト保存",
    "sb_dialog_load": "スクリプト読込",
    "sb_no_step_selected": "ステップ未選択",

    # Language
    "language_label": "言語:",

    # Run History Tab
    "rh_filter_label": "ソース:",
    "rh_source_all": "すべて",
    "rh_source_scheduler": "スケジューラー",
    "rh_source_trigger": "トリガー",
    "rh_source_hotkey": "ホットキー",
    "rh_source_manual": "手動",
    "rh_source_rest": "REST",
    "rh_refresh": "更新",
    "rh_clear": "クリア",
    "rh_confirm_clear": "すべての実行履歴を削除しますか？この操作は取り消せません。",
    "rh_count_label": "{n} 件",
    "rh_col_id": "ID",
    "rh_col_source": "ソース",
    "rh_col_target": "対象",
    "rh_col_script": _SCRIPT,
    "rh_col_started": "開始時刻",
    "rh_col_duration": "所要時間",
    "rh_col_status": "ステータス",
    "rh_status_ok": "成功",
    "rh_status_error": "エラー",
    "rh_status_running": "実行中",
    "rh_col_artifact": "スクリーンショット",
    "rh_open_artifact": "スクリーンショットを開く",
    "rh_no_artifact": "選択した実行にスクリーンショットはありません。",
    "rh_artifact_missing": "スクリーンショットファイルが存在しません。",
    "rh_timeline_heading": "タイムライン（左:古い → 右:新しい）",
    "rh_preview_heading": "プレビュー",
    "rh_preview_empty": "実行を選択するとプレビューが表示されます。",
    "rh_preview_no_artifact": "この実行のスクリーンショットはありません。",

    # Email triggers tab
    "eml_engine_group": "ポーリングエンジン",
    "eml_add_group": "新規 IMAP トリガー",
    "eml_start": "ポーリング開始",
    "eml_stop": "ポーリング停止",
    "eml_poll_now": "今すぐポーリング",
    "eml_poll_done": "今回 {n} 件のメッセージで発火しました。",
    "eml_running": "ポーリング中。",
    "eml_stopped": "ポーリング停止中。",
    "eml_host_label": "ホスト：",
    "eml_port_label": "ポート：",
    "eml_user_label": "ユーザー：",
    "eml_password_label": "パスワード：",
    "eml_password_placeholder": "IMAP パスワード / アプリパスワード",
    "eml_mailbox_label": "メールボックス：",
    "eml_search_label": "検索条件：",
    "eml_poll_label": "ポーリング (秒)：",
    "eml_script_label": "スクリプト：",
    "eml_browse": "参照",
    "eml_register": "トリガーを登録",
    "eml_remove": "選択を削除",
    "eml_ssl": "SSL を使用",
    "eml_mark_seen": "発火後に既読にする",
    "eml_required_fields": "ホスト、ユーザー、パスワード、スクリプトが必要です。",
    "eml_col_id": "ID",
    "eml_col_host": "ホスト",
    "eml_col_user": "ユーザー",
    "eml_col_mailbox": "メールボックス",
    "eml_col_script": "スクリプト",
    "eml_col_fired": "発火回数",
    "eml_col_error": "最近のエラー",

    # Webhooks tab
    "wh_server_group": "HTTP サーバー",
    "wh_add_group": "新規 webhook",
    "wh_host_label": "ホスト：",
    "wh_port_label": "ポート：",
    "wh_start": "開始",
    "wh_stop": "停止",
    "wh_started": "{host}:{port} で待機中",
    "wh_running": "稼働中 {host}:{port}",
    "wh_stopped": "サーバー停止中。",
    "wh_path_label": "パス：",
    "wh_script_label": "スクリプト：",
    "wh_browse": "参照",
    "wh_methods_label": "メソッド：",
    "wh_token_label": "Token：",
    "wh_token_placeholder": "Bearer トークン (任意)",
    "wh_register": "Webhook を登録",
    "wh_remove": "選択を削除",
    "wh_path_and_script_required": "パスとスクリプトファイルが必要です。",
    "wh_col_id": "ID",
    "wh_col_path": "パス",
    "wh_col_methods": "メソッド",
    "wh_col_script": "スクリプト",
    "wh_col_fired": "発火回数",
    "wh_col_token": "認証？",
    "wh_yes": "あり",
    "wh_no": "なし",

    # Secrets tab
    "secret_unlock_group": "ボールト",
    "secret_manage_group": "シークレット",
    "secret_passphrase_label": "パスフレーズ：",
    "secret_passphrase_placeholder": "ボールトパスフレーズ",
    "secret_init": "ボールトを作成",
    "secret_init_done": "ボールトを作成し、解錠しました。",
    "secret_unlock": "解錠",
    "secret_lock": "ロック",
    "secret_add": "シークレットを追加",
    "secret_remove": "削除",
    "secret_change_passphrase": "パスフレーズ変更",
    "secret_change_done": "新しいパスフレーズで再暗号化しました。",
    "secret_status_uninitialized": "ボールト未作成。",
    "secret_status_unlocked": "ボールト解錠中。",
    "secret_status_locked": "ボールトはロック中。",
    "secret_passphrase_required": "パスフレーズを入力してください。",
    "secret_wrong_passphrase": "パスフレーズが違います。",
    "secret_unlock_first": "先にボールトを解錠してください。",
    "secret_name_prompt": "シークレット名 (${secrets.NAME} で参照):",
    "secret_value_prompt": "シークレット値:",
    "secret_old_passphrase_prompt": "現在のパスフレーズ:",
    "secret_new_passphrase_prompt": "新しいパスフレーズ:",

    # Profiler tab
    "prof_enable": "プロファイラを有効化",
    "prof_disable": "プロファイラを無効化",
    "prof_reset": "統計をリセット",
    "prof_refresh": "更新",
    "prof_running": "プロファイラ計測中。",
    "prof_paused": "プロファイラは停止中です。",
    "prof_total_label": "{n} アクションを記録",
    "prof_total_empty": "サンプルがまだありません。",
    "prof_col_name": "アクション",
    "prof_col_calls": "回数",
    "prof_col_total": "合計",
    "prof_col_avg": "平均",
    "prof_col_min": "最小",
    "prof_col_max": "最大",
    "prof_col_share": "割合",

    # Accessibility Tab
    "a11y_app_label": "アプリ:",
    "a11y_app_placeholder": "例: 電卓",
    "a11y_name_label": "名前に含む:",
    "a11y_name_placeholder": "部分一致",
    "a11y_refresh": "更新",
    "a11y_click_selected": "選択項目をクリック",
    "a11y_col_app": "アプリ",
    "a11y_col_role": "ロール",
    "a11y_col_name": "名前",
    "a11y_col_bounds": "境界",
    "a11y_col_center": "中心",
    "a11y_count_label": "{n} 個の要素",
    "a11y_no_selection": "行を選択してください",
    "a11y_click_not_found": "クリック可能な要素が見つかりません",

    # VLM (AI Locator) Tab
    "vlm_desc_label": "説明:",
    "vlm_desc_placeholder": "例: 緑色の送信ボタン",
    "vlm_model_label": "モデル:",
    "vlm_model_placeholder": "任意 (例: claude-opus-4-7)",
    "vlm_locate": "検索",
    "vlm_click": "検索してクリック",
    "vlm_result": "位置: ({x}, {y})",
    "vlm_ok": "完了",
    "vlm_not_found": "一致する要素が見つかりません",
    "vlm_error": "エラー",
    "vlm_desc_required": "まず対象の説明を入力してください",

    # OCR Reader Tab
    "ocr_region_group": "領域",
    "ocr_region_label": "x, y, w, h:",
    "ocr_region_placeholder": "空欄なら画面全体",
    "ocr_pick_region": "領域を選択...",
    "ocr_lang_label": "言語:",
    "ocr_min_conf_label": "最低信頼度:",
    "ocr_regex_label": "正規表現:",
    "ocr_regex_placeholder": r"例: Order#\d+",
    "ocr_dump_region": "領域内の文字を取得",
    "ocr_find_regex": "正規表現で検索",
    "ocr_results_label": "結果:",
    "ocr_match_count": "{n} 件",
    "ocr_region_invalid": "領域はカンマ区切りの整数 4 つ",
    "ocr_min_conf_invalid": "信頼度は数値で入力",
    "ocr_regex_required": "先に正規表現を入力",
    "ocr_regex_invalid": "正規表現が不正",

    # Variables Tab
    "vars_current_group": "現在のスコープ",
    "vars_col_name": "名前",
    "vars_col_value": "値",
    "vars_count": "{n} 個の変数",
    "vars_refresh": "再読み込み",
    "vars_clear": "全消去",
    "vars_clear_confirm": "実行時変数を全て消去しますか？",
    "vars_set_group": "個別に設定",
    "vars_name_label": "名前:",
    "vars_name_placeholder": "変数名",
    "vars_name_required": "名前を入力してください",
    "vars_value_label": "値:",
    "vars_value_placeholder": "JSON リテラル（42、\"text\"、[1,2]）または文字列",
    "vars_set_btn": "設定",
    "vars_seed_group": "JSON から読み込み",
    "vars_seed_placeholder": "{\"counter\": 0, \"items\": [\"a\", \"b\"]}",
    "vars_seed_btn": "JSON をスコープに統合",
    "vars_seed_required": "JSON オブジェクトを貼り付けてください",
    "vars_seed_invalid": "JSON が不正",
    "vars_seed_not_object": "JSON はオブジェクトでなければなりません",

    # LLM Planner Tab
    "llm_desc_group": "タスクの説明",
    "llm_desc_placeholder": (
        "例: メモ帳を開き、'hello world' と入力し、test.txt として保存"
    ),
    "llm_model_label": "モデル:",
    "llm_model_placeholder": "任意（例: claude-opus-4-7）",
    "llm_plan_btn": "プラン作成",
    "llm_run_btn": "プラン実行",
    "llm_plan_group": "計画されたアクション",
    "llm_result_group": "実行結果",
    "llm_desc_required": "まず自動化したいタスクを記述してください",
    "llm_planning": "計画中...",
    "llm_plan_count": "{n} 個のアクションを計画",
    "llm_no_plan": "まず「プラン作成」を押してください",
    "llm_running": "実行中...",
    "llm_run_done": "完了",

    # Remote Desktop Tab
    "rd_host_tab": "ホスト（このマシン）",
    "rd_viewer_tab": "ビューア（他マシンを操作）",
    "rd_host_security_warning": (
        "警告：host:port と token を知る相手は、このマシンのマウス／キーボードを"
        "完全に操作できます。既定は 127.0.0.1。外部公開は SSH トンネルか"
        "信頼できる VPN 経由で行ってください。"
    ),
    "rd_host_config_group": "ホスト設定",
    "rd_viewer_config_group": "リモートホストへ接続",
    "rd_token_label": _TOKEN_LABEL,
    "rd_token_placeholder": "共有シークレット（HMAC キー）",
    "rd_token_generate": "生成",
    "rd_bind_label": "アドレス:",
    "rd_port_label": "ポート:",
    "rd_fps_label": "FPS:",
    "rd_quality_label": "JPEG 品質:",
    "rd_host_start": "ホスト開始",
    "rd_host_stop": _STOP_HOST_JA,
    "rd_host_status_running": "稼働中 ポート {port} — ビューア {n} 名",
    "rd_host_status_stopped": "ホストは停止中",
    "rd_host_preview_label": "プレビュー（ビューアの表示）:",
    "rd_host_card_group": "接続",
    "rd_viewer_card_group": "リモートホストへ接続",
    "rd_host_basics_group": "接続設定",
    "rd_advanced_group": "詳細設定",
    "rd_host_copy_share": "共有情報をコピー",
    "rd_host_copy_share_unavailable": "ホストを起動してから共有してください。",
    "rd_host_copy_share_confirm": (
        "コピーするとアドレス・ポート・ホスト ID・トークンを"
        "クリップボードに置きます。貼り付けた相手はこのマシンを"
        "完全に操作できるようになります。続けますか?"
    ),
    "rd_badge_running": "RUNNING · :{port} · ビューア {n} 名",
    "rd_badge_stopped": "STOPPED",
    "rd_badge_idle": "未接続",
    "rd_badge_live": "接続中",
    "rd_host_id_group": "ホスト ID（ビューアに伝える）",
    "rd_host_id_label": "ホスト ID:",
    "rd_host_id_copy": "コピー",
    "rd_transport_label": "トランスポート:",
    "rd_tls_cert_label": "TLS 証明書:",
    "rd_tls_cert_placeholder": "PEM 証明書パス（任意）",
    "rd_tls_key_label": "TLS キー:",
    "rd_tls_key_placeholder": "PEM 秘密鍵パス（任意）",
    "rd_tls_both_required": "TLS 証明書とキーは両方必要",
    "rd_tls_insecure": "証明書検証をスキップ（自己署名用）",
    "rd_browse": "参照...",
    "rd_enable_audio": "システム音声をストリーム（sounddevice）",
    "rd_viewer_audio_play": "受信音声を再生（sounddevice）",
    "rd_viewer_push_clipboard": "ローカルのクリップボード文字をホストへ送信",
    "rd_viewer_send_file": "ファイル送信...",
    "rd_dest_path_prompt": "{name} のリモート保存先:",
    "rd_clipboard_empty": "ローカルのクリップボードが空です",
    "rd_clipboard_sent": "クリップボードをホストへ送信しました",
    "rd_viewer_clipboard_received": "ホストからクリップボードを同期しました",
    "rd_progress_label": "転送中: {done} / {total} バイト",
    "rd_progress_done": "転送完了: {path}",
    "rd_progress_failed": "転送失敗: {error}",
    "rd_viewer_connect": "接続",
    "rd_viewer_disconnect": "切断",
    "rd_viewer_required_fields": "アドレス・ポート・トークンはすべて必須です。",
    "rd_viewer_status_connected": "接続中 — フレーム受信中",
    "rd_viewer_status_idle": "未接続",
    "rd_viewer_error": "リモートデスクトップエラー",
    "rd_remote_screen_title": "リモートデスクトップ — ライブセッション",
    "rd_remote_screen_title_with_id": "リモートデスクトップ — {host_id}",

    # Menu bar
    "menu_file": "ファイル",
    "menu_file_open_script": "スクリプトを開く...",
    "menu_file_exit": "終了",
    "menu_view": "表示",
    "menu_view_tabs": "タブ",
    "menu_view_cat_core": "コア",
    "menu_view_cat_editing": "編集",
    "menu_view_cat_detection": "検出・ビジョン",
    "menu_view_cat_automation": "自動化エンジン",
    "menu_view_cat_system": "システム",
    "menu_view_text_size": "文字サイズ",
    "menu_view_text_auto": "自動（画面に応じて）",
    "menu_view_text_small": "小 (10pt)",
    "menu_view_text_normal": "標準 (12pt)",
    "menu_view_text_large": "大 (14pt)",
    "menu_view_text_xlarge": "特大 (16pt)",
    "menu_view_text_xxlarge": "超大 (20pt)",
    "menu_tools": "ツール",
    "menu_tools_start_hotkeys": "ホットキーデーモン開始",
    "menu_tools_start_scheduler": "スケジューラー開始",
    "menu_tools_start_triggers": "トリガーエンジン開始",
    "menu_language": "言語",
    "menu_help": "ヘルプ",
    "menu_help_about": "AutoControlGUI について",
}
