japanese_word_dict = {
    "application_name": "AutoControlGUI",

    # Tabs
    "tab_auto_click": "自動クリック",
    "tab_screenshot": "スクリーンショット",
    "tab_image_detect": "画像検出",
    "tab_record": "記録 / 再生",
    "tab_script": "スクリプト実行",
    "tab_script_builder": "スクリプトビルダー",
    "tab_recording_editor": "記録エディタ",
    "tab_window_manager": "ウィンドウ管理",
    "tab_scheduler": "スケジューラー",
    "tab_socket_server": "ソケットサーバー",
    "tab_live_hud": "ライブ HUD",
    "tab_hotkeys": "ホットキー",
    "tab_triggers": "トリガー",
    "tab_plugins": "プラグイン",
    "tab_screen_record": "画面録画",
    "tab_shell": "シェル",
    "tab_report": "レポート",
    "tab_run_history": "実行履歴",

    # Auto Click Tab
    "interval_time": "間隔 (ms):",
    "cursor_x": "カーソル X:",
    "cursor_y": "カーソル Y:",
    "mouse_button": "マウスボタン:",
    "keyboard_button": "キーボード:",
    "click_type": "クリックタイプ:",
    "single_click": "シングルクリック",
    "double_click": "ダブルクリック",
    "input_method": "入力方式:",
    "mouse_radio": "マウス",
    "keyboard_radio": "キーボード",
    "repeat_until_stopped_radio": "停止まで繰り返し",
    "repeat_radio": "繰り返し",
    "times": "回数",
    "start": "開始",
    "stop": "停止",
    "hotkey_label": "ホットキー（カンマ区切り）:",
    "hotkey_send": "ホットキー送信",
    "write_label": "テキスト入力:",
    "write_send": "入力",
    "mouse_scroll_label": "スクロール値:",
    "scroll_direction_label": "スクロール方向:",
    "scroll_send": "スクロール",
    "get_position": "マウス位置取得",
    "current_position": "現在位置:",

    # Screenshot Tab
    "take_screenshot": "スクリーンショット撮影",
    "save_screenshot": "スクリーンショット保存",
    "file_path_label": "ファイルパス:",
    "browse": "参照",
    "region_label": "領域 (x1, y1, x2, y2):",
    "pick_region": "領域選択",
    "crop_template": "テンプレート切り抜き",
    "get_pixel_label": "ピクセル色取得",
    "pixel_x": "X:",
    "pixel_y": "Y:",
    "pixel_result": "ピクセル色:",
    "screen_size_label": "画面サイズ:",
    "get_screen_size": "画面サイズ取得",

    # Image Detection Tab
    "template_image": "テンプレート画像:",
    "threshold_label": "閾値 (0.0~1.0):",
    "locate_image": "画像検索",
    "locate_all": "全て検索",
    "locate_click": "検索してクリック",
    "detection_result": "検出結果:",
    "draw_image_check": "検出結果を描画",

    # Record / Playback Tab
    "start_record": "記録開始",
    "stop_record": "記録停止",
    "playback": "再生",
    "save_record": "JSON 保存",
    "load_record": "JSON 読込",
    "record_status": "状態:",
    "record_idle": "待機",
    "record_recording": "記録中...",
    "record_list_label": "記録済みアクション:",

    # Script Executor Tab
    "load_script": "スクリプト読込 (JSON)",
    "execute_script": "実行",
    "execute_dir_label": "実行ディレクトリ:",
    "execute_dir": "全て実行",
    "script_content": "スクリプト内容:",
    "execution_result": "実行結果:",

    # Screen Recording Tab
    "recorder_name": "レコーダー名:",
    "output_file": "出力ファイル:",
    "codec_label": "コーデック:",
    "fps_label": "FPS:",
    "resolution_label": "解像度 (幅x高さ):",
    "start_screen_record": "録画開始",
    "stop_screen_record": "録画停止",
    "screen_record_status": "状態:",

    # Shell Tab
    "shell_command_label": "シェルコマンド:",
    "execute_shell": "実行",
    "shell_output": "出力:",
    "start_exe_label": "実行ファイルパス:",
    "start_exe": "実行ファイル起動",

    # Report Tab
    "report_name": "レポート名:",
    "generate_html_report": "HTML レポート生成",
    "generate_json_report": "JSON レポート生成",
    "generate_xml_report": "XML レポート生成",
    "enable_test_record": "テスト記録を有効化",
    "disable_test_record": "テスト記録を無効化",
    "test_record_status": "テスト記録:",
    "report_result": "結果:",

    # Hotkeys Tab
    "hk_combo_label": "組合せ:",
    "hk_script_label": "スクリプト:",
    "hk_bind": "バインド",
    "hk_remove_selected": "選択項目を削除",
    "hk_start_daemon": "デーモン開始",
    "hk_stop_daemon": "デーモン停止",
    "hk_daemon_stopped": "デーモン停止中",
    "hk_daemon_running": "デーモン実行中",
    "hk_col_id": "ID",
    "hk_col_combo": "組合せ",
    "hk_col_script": "スクリプト",
    "hk_col_fired": "発火",
    "hk_dialog_select_script": "スクリプトを選択",

    # Triggers Tab
    "tr_script_label": "スクリプト:",
    "tr_type_label": "タイプ:",
    "tr_repeat": "繰り返し",
    "tr_add": "トリガー追加",
    "tr_remove_selected": "選択項目を削除",
    "tr_start_engine": "エンジン開始",
    "tr_stop_engine": "エンジン停止",
    "tr_engine_stopped": "エンジン停止中",
    "tr_engine_running": "エンジン実行中",
    "tr_type_image": "画像出現",
    "tr_type_window": "ウィンドウ出現",
    "tr_type_pixel": "ピクセル一致",
    "tr_type_file": "ファイル変更",
    "tr_image_label": "画像:",
    "tr_threshold_label": "閾値:",
    "tr_title_contains_label": "タイトルに含む:",
    "tr_watch_label": "監視パス:",
    "tr_col_id": "ID",
    "tr_col_type": "タイプ",
    "tr_col_detail": "詳細",
    "tr_col_fired": "発火",
    "tr_col_enabled": "有効",
    "tr_yes": "はい",
    "tr_no": "いいえ",
    "tr_dialog_select_script": "スクリプトを選択",
    "tr_dialog_select_image": "画像を選択",
    "tr_dialog_select_file": "監視するファイルを選択",

    # Plugins Tab
    "pl_dir_label": "プラグインディレクトリ:",
    "pl_load": "読込と登録",
    "pl_no_loaded": "プラグイン未読込",
    "pl_registered_label": "登録済みコマンド:",
    "pl_dialog_plugin_dir": "プラグインディレクトリ",

    # Scheduler Tab
    "sch_script_label": "スクリプト:",
    "sch_interval_label": "毎 (秒):",
    "sch_repeat": "繰り返し",
    "sch_add": "追加",
    "sch_remove_selected": "選択項目を削除",
    "sch_start": "スケジューラー開始",
    "sch_stop": "スケジューラー停止",
    "sch_status_running": "スケジューラー実行中",
    "sch_status_stopped": "スケジューラー停止中",
    "sch_col_job_id": "ジョブ ID",
    "sch_col_script": "スクリプト",
    "sch_col_interval": "間隔 (秒)",
    "sch_col_runs": "実行回数",
    "sch_col_enabled": "有効",
    "sch_dialog_select_script": "スクリプトを選択",

    # Socket / REST Tab
    "ss_tcp_group": "TCP ソケットサーバー",
    "ss_rest_group": "REST API サーバー",
    "ss_host_label": "ホスト:",
    "ss_port_label": "ポート:",
    "ss_tcp_any_check": "TCP を 0.0.0.0 にバインド（ネットワーク公開）",
    "ss_rest_any_check": "REST を 0.0.0.0 にバインド（ネットワーク公開）",
    "ss_tcp_stopped": "TCP 停止中",
    "ss_rest_stopped": "REST 停止中",
    "ss_tcp_start": "TCP 開始",
    "ss_tcp_stop": "TCP 停止",
    "ss_rest_start": "REST 開始",
    "ss_rest_stop": "REST 停止",

    # Live HUD Tab
    "hud_watchers_group": "ウォッチャー",
    "hud_start": "HUD 開始",
    "hud_stop": "HUD 停止",
    "hud_clear": "ログクリア",
    "hud_recent_log": "最近のログ:",
    "hud_mouse_prefix": "マウス:",
    "hud_pixel_prefix": "ピクセル:",

    # Window Manager Tab
    "win_refresh": "更新",
    "win_filter_placeholder": "タイトル部分文字列でフィルタ",
    "win_col_hwnd": "HWND",
    "win_col_title": "タイトル",
    "win_focus_selected": "選択項目をフォーカス",
    "win_close_selected": "選択項目を閉じる",
    "win_status_count": "{n} ウィンドウ",

    # Recording Editor Tab
    "re_file_label": "ファイル:",
    "re_browse": "参照",
    "re_load": "読込",
    "re_save_as": "名前を付けて保存",
    "re_trim_start": "トリム開始:",
    "re_trim_end": "終了:",
    "re_apply_trim": "トリム適用",
    "re_remove_selected": "選択項目を削除",
    "re_delay_x": "ディレイ倍率",
    "re_floor_ms": "下限 ms:",
    "re_apply_delays": "ディレイ適用",
    "re_scale_x": "スケール x:",
    "re_scale_y": "y:",
    "re_apply_scale": "スケール適用",
    "re_keep_mouse": "マウスのみ保持",
    "re_keep_keyboard": "キーボードのみ保持",
    "re_preview": "プレビュー:",
    "re_dialog_open": "記録を開く",
    "re_dialog_save": "記録を保存",

    # Script Builder Tab
    "sb_delete": "削除",
    "sb_up": "上へ",
    "sb_down": "下へ",
    "sb_load_json": "JSON 読込",
    "sb_save_json": "JSON 保存",
    "sb_run": "実行",
    "sb_add_step": "ステップ追加",
    "sb_dialog_save": "スクリプト保存",
    "sb_dialog_load": "スクリプト読込",
    "sb_no_step_selected": "ステップ未選択",

    # Language
    "language_label": "言語:",

    # Run History Tab
    "rh_filter_label": "ソース:",
    "rh_source_all": "すべて",
    "rh_source_scheduler": "スケジューラー",
    "rh_source_trigger": "トリガー",
    "rh_source_hotkey": "ホットキー",
    "rh_source_manual": "手動",
    "rh_source_rest": "REST",
    "rh_refresh": "更新",
    "rh_clear": "クリア",
    "rh_confirm_clear": "すべての実行履歴を削除しますか？この操作は取り消せません。",
    "rh_count_label": "{n} 件",
    "rh_col_id": "ID",
    "rh_col_source": "ソース",
    "rh_col_target": "対象",
    "rh_col_script": "スクリプト",
    "rh_col_started": "開始時刻",
    "rh_col_duration": "所要時間",
    "rh_col_status": "ステータス",
    "rh_status_ok": "成功",
    "rh_status_error": "エラー",
    "rh_status_running": "実行中",

    # Menu bar
    "menu_file": "ファイル",
    "menu_file_open_script": "スクリプトを開く...",
    "menu_file_exit": "終了",
    "menu_view": "表示",
    "menu_view_tabs": "タブ",
    "menu_tools": "ツール",
    "menu_tools_start_hotkeys": "ホットキーデーモン開始",
    "menu_tools_start_scheduler": "スケジューラー開始",
    "menu_tools_start_triggers": "トリガーエンジン開始",
    "menu_language": "言語",
    "menu_help": "ヘルプ",
    "menu_help_about": "AutoControlGUI について",
}
