simplified_chinese_word_dict = {
    "application_name": "AutoControlGUI",

    # Tabs
    "tab_auto_click": "自动点击",
    "tab_screenshot": "屏幕截图",
    "tab_image_detect": "图像检测",
    "tab_record": "录制 / 回放",
    "tab_script": "脚本执行",
    "tab_script_builder": "脚本编辑器",
    "tab_recording_editor": "录制编辑器",
    "tab_window_manager": "窗口管理",
    "tab_scheduler": "调度器",
    "tab_socket_server": "Socket 服务器",
    "tab_live_hud": "实时监看",
    "tab_hotkeys": "全局热键",
    "tab_triggers": "事件触发器",
    "tab_webhooks": "Webhook 触发",
    "tab_plugins": "插件",
    "tab_screen_record": "屏幕录像",
    "tab_shell": "Shell 命令",
    "tab_report": "报告生成",
    "tab_run_history": "执行记录",
    "tab_profiler": "性能分析",
    "tab_secrets": "密钥管理",
    "tab_accessibility": "无障碍树",
    "tab_vlm": "AI 定位",
    "tab_ocr_reader": "OCR 读取",
    "tab_variables": "运行期变量",
    "tab_llm_planner": "LLM 脚本规划",
    "tab_remote_desktop": "远程桌面",
    "tab_rest_api": "REST API",
    "tab_admin_console": "管理控制台",
    "tab_audit_log": "审计日志",
    "tab_inspector": "包监测",
    "tab_usb_devices": "USB 设备",
    "tab_diagnostics": "诊断",

    # 诊断分页
    "diag_run": "运行诊断",
    "diag_summary_ok": "{count} 项检查全部通过。",
    "diag_summary_failed": "{count} 项检查中有 {failed} 项失败。",
    "diag_col_name": "检查项",
    "diag_col_severity": "严重度",
    "diag_col_status": "状态",
    "diag_col_detail": "详情",
    "diag_status_ok": "正常",
    "diag_status_fail": "失败",

    # USB 设备分页
    "usb_backend_label": "后端:",
    "usb_refresh": "刷新",
    "usb_col_vid": "VID",
    "usb_col_pid": "PID",
    "usb_col_manufacturer": "制造商",
    "usb_col_product": "产品",
    "usb_col_serial": "序列号",
    "usb_col_location": "总线 / 位置",
    "usb_auto_refresh": "自动刷新 + hotplug 监测",
    "usb_events_idle": "hotplug 监测中：自上次刷新无变化。",
    "usb_events_recent": "近期 hotplug：{text}",

    # USB passthrough ACL 提示对话框
    "usb_prompt_title": "USB 设备使用请求",
    "usb_prompt_intro": "远程 viewer 正在请求使用本机的 USB 设备。只在你认得这个请求时允许。",
    "usb_prompt_vendor": "Vendor ID:",
    "usb_prompt_product": "Product ID:",
    "usb_prompt_serial": "序列号:",
    "usb_prompt_viewer": "Viewer ID:",
    "usb_prompt_remember": "记住这个决定（写入永久 ACL 规则）",
    "usb_prompt_allow": "允许",
    "usb_prompt_deny": "拒绝",
    "tab_usb_browser": "USB 浏览器",

    # USB 浏览器（viewer 端）
    "usb_browser_target_group": "远程主机",
    "usb_browser_url": "REST URL:",
    "usb_browser_token": "Bearer 令牌:",
    "usb_browser_fetch": "获取设备",
    "usb_browser_open": "打开选中项",
    "usb_browser_fetching": "获取中…",
    "usb_browser_fetched": "已获取 {count} 个设备。",
    "usb_browser_fetch_failed": "获取失败：{error}",
    "usb_browser_col_vid": "VID",
    "usb_browser_col_pid": "PID",
    "usb_browser_col_manufacturer": "制造商",
    "usb_browser_col_product": "产品",
    "usb_browser_col_serial": "序列号",
    "usb_browser_open_select_first": "请先选择一行。",
    "usb_browser_open_unwired": "Open 需要 WebRTC usb DataChannel；当前版本尚未接通。",

    # 包监测分页
    "inspector_metrics_group": "汇总指标",
    "inspector_summary_text": "{count} 个样本 / 窗口 {window:.1f} 秒",
    "inspector_metric_rtt_ms": "RTT (ms)",
    "inspector_metric_fps": "每秒帧数",
    "inspector_metric_bitrate_kbps": "比特率 (kbps)",
    "inspector_metric_packet_loss_pct": "丢包率 (%)",
    "inspector_metric_jitter_ms": "抖动 (ms)",
    "inspector_refresh": "刷新",
    "inspector_reset": "重置",
    "inspector_col_age": "经过",

    # 审计日志分页
    "audit_filter_group": "筛选",
    "audit_filter_type": "事件类型:",
    "audit_filter_host": "主机 ID:",
    "audit_filter_limit": "条数:",
    "audit_refresh": "刷新",
    "audit_verify": "验证哈希链",
    "audit_clear": "清空日志",
    "audit_clear_confirm": "确定清空所有审计日志？此操作不可撤销。",
    "audit_clear_done": "已删除 {count} 条审计日志。",
    "audit_verify_ok": "哈希链正常 ({total} 条)。",
    "audit_verify_broken": "哈希链在 ID {row_id} 中断 (共 {total} 条)。",
    "audit_col_ts": "时间",
    "audit_col_type": "事件",
    "audit_col_host": "主机 ID",
    "audit_col_viewer": "查看端 ID",
    "audit_col_detail": "详情",

    # 管理控制台分页
    "admin_add_group": "注册主机",
    "admin_add": "添加",
    "admin_remove": "移除所选",
    "admin_refresh": "全部轮询",
    "admin_label": "标签:",
    "admin_url": "基础 URL:",
    "admin_token": "令牌:",
    "admin_broadcast_group": "广播",
    "admin_actions_label": "动作 JSON (发送给所有主机):",
    "admin_broadcast_run": "对所有主机执行",
    "admin_results_label": "各主机结果:",
    "admin_col_label": "标签",
    "admin_col_url": "URL",
    "admin_col_health": "健康",
    "admin_col_latency": "延迟",
    "admin_col_jobs": "任务",
    "admin_health_ok": "正常",
    "admin_health_down": "离线",

    # REST API 分页
    "rest_config_group": "REST API 配置",
    "rest_status_group": "REST API 状态",
    "rest_host": "主机:",
    "rest_port": "端口:",
    "rest_token": "令牌:",
    "rest_token_ph": "留空则自动生成",
    "rest_enable_audit": "写入审计日志",
    "rest_start": "启动",
    "rest_stop": "停止",
    "rest_copy_url": "复制 URL",
    "rest_copy_token": "复制令牌",
    "rest_url": "URL:",
    "rest_active_token": "Bearer 令牌:",
    "rest_running": "REST API 运行中。",
    "rest_stopped": "REST API 已停止。",
    "rest_config_export": "导出配置",
    "rest_config_import": "导入配置",
    "rest_config_export_done": "已将 {count} 个文件写入 {path}。",
    "rest_config_import_confirm": "用此配置包覆盖用户配置？既有文件会先被改名为 .bak.<时间戳>。",
    "rest_config_import_done": "已写入 {written} 个文件；跳过 {skipped} 个。",

    # Remote Desktop — WebRTC 子分页
    "rd_webrtc_host_tab": "WebRTC 被远程",
    "rd_webrtc_viewer_tab": "WebRTC 远程他人",
    "rd_webrtc_config_group": "WebRTC 设置",
    "rd_webrtc_monitor_label": "屏幕编号:",
    "rd_webrtc_generate_offer": "生成 offer",
    "rd_webrtc_offer_label": "Offer SDP (传给对方 viewer):",
    "rd_webrtc_answer_input_label": "粘贴 viewer 的 answer SDP:",
    "rd_webrtc_paste_answer": "把 answer SDP 粘贴到这里",
    "rd_webrtc_apply_answer": "应用 answer",
    "rd_webrtc_stop_host": "停止 host",
    "rd_webrtc_offer_input_label": "粘贴 host 的 offer SDP:",
    "rd_webrtc_paste_offer": "把 offer SDP 粘贴到这里",
    "rd_webrtc_create_answer": "生成 answer",
    "rd_webrtc_stop_viewer": "停止 viewer",
    "rd_webrtc_answer_label": "Answer SDP (传给对方 host):",
    "rd_webrtc_status_idle": "空闲",
    "rd_webrtc_state_label": "状态:",
    "rd_webrtc_generating_offer": "生成 offer 中...",
    "rd_webrtc_offer_ready": "Offer 已生成 — 复制传给 viewer",
    "rd_webrtc_creating_answer": "生成 answer 中...",
    "rd_webrtc_answer_ready": "Answer 已生成 — 复制传给 host",
    "rd_webrtc_answer_applied": "Answer 已应用，等待 viewer 认证",
    "rd_webrtc_auth_ok": "已认证",
    "rd_webrtc_auth_fail": "认证失败",
    "rd_webrtc_token_required": "请先输入 token",
    "rd_webrtc_no_offer_yet": "请先生成 offer",
    "rd_webrtc_no_answer": "请先粘贴 viewer 的 answer SDP",
    "rd_webrtc_no_offer": "请先粘贴 host 的 offer SDP",
    "rd_webrtc_unavailable": (
        "WebRTC 模块未安装 — 请运行 pip install je_auto_control[webrtc]"
    ),
    "rd_webrtc_signaling_group": "通过 signaling server 连线（推荐）",
    "rd_webrtc_manual_group": "手动 SDP 粘贴（备用）",
    "rd_webrtc_advanced_group": "高级（STUN / TURN）",
    "rd_webrtc_server_label": "Server URL:",
    "rd_webrtc_host_id_label": "Host ID:",
    "rd_webrtc_host_id_placeholder": "对方 host 显示的 8 位 ID",
    "rd_webrtc_secret_label": "Server 密钥:",
    "rd_webrtc_regen_id": "新 ID",
    "rd_webrtc_publish_via_server": "发布 host 并等待 viewer 连线",
    "rd_webrtc_connect_via_server": "连线到 host",
    "rd_webrtc_stun_label": "STUN URL:",
    "rd_webrtc_turn_label": "TURN URL:",
    "rd_webrtc_turn_placeholder": "turn:turn.example.com:3478 (可选)",
    "rd_webrtc_turn_user_label": "TURN 用户:",
    "rd_webrtc_turn_cred_label": "TURN 密钥:",
    "rd_webrtc_publishing_offer": "已发布 offer，等待 viewer 回应...",
    "rd_webrtc_polling_offer": "向 signaling server 询问 host 的 offer...",
    "rd_webrtc_pushing_answer": "把 answer 送到 signaling server...",
    "rd_webrtc_waiting_auth": "Answer 已发送，等待 host 接受",
    "rd_webrtc_pending_viewer_prompt": (
        "有人用正确的 token 连进来。"
        "确定让对方控制这台机器吗？"
    ),
    "rd_webrtc_server_required": "请填 signaling server URL",
    "rd_webrtc_host_id_required": "请填 Host ID",
    # 信任列表 / 接受对话框
    "rd_webrtc_trusted_group": "受信任的 viewer (自动接受)",
    "rd_webrtc_remove_trusted": "移除所选",
    "rd_webrtc_clear_trusted": "全部清除",
    "rd_webrtc_clear_trust_confirm": "确定移除所有受信任 viewer？",
    "rd_webrtc_pending_viewer_title": "新连入请求",
    "rd_webrtc_reject": "拒绝",
    "rd_webrtc_accept_once": "本次接受",
    "rd_webrtc_accept_and_trust": "接受并信任",
    # 通讯录
    "rd_webrtc_address_book_group": "已保存的 host",
    "rd_webrtc_connect_selected": "连接",
    "rd_webrtc_save_current": "保存当前",
    "rd_webrtc_remove_selected": "移除",
    "rd_webrtc_no_address_selected": "请先选择一个 host",
    "rd_webrtc_save_address_missing_fields": "需要 Server URL 与 Host ID 才能保存",
    # 细节
    "rd_webrtc_show_cursor": "在串流中显示光标",
    "rd_webrtc_blank_screen": "Session 期间遮蔽本机屏幕",
    "rd_webrtc_blanking_banner": "本机屏幕正在被远程观看",
    "rd_webrtc_send_cad": "发送 Ctrl+Alt+Del",
    "rd_webrtc_cad_not_connected": "请先连接再发送 Ctrl+Alt+Del",
    # (A) batch
    "rd_webrtc_read_only": "只读模式 (丢弃 viewer 输入)",
    "rd_webrtc_bandwidth_label": "带宽:",
    "rd_webrtc_wake_on_lan": "Wake on LAN",
    "rd_webrtc_wol_mac_prompt": "目标 MAC (AA:BB:CC:DD:EE:FF):",
    "rd_webrtc_wol_broadcast_prompt": "广播地址:",
    "rd_webrtc_wol_sent": "Magic packet 已发送",
    "rd_webrtc_start_recording": "录制 session",
    "rd_webrtc_stop_recording": "停止录制",
    "rd_webrtc_recording_save_as": "录制保存为",
    "rd_webrtc_recording_saved": "录制已保存: {path}",
    "rd_webrtc_stats_idle": "(暂无统计数据)",
    # (B) batch
    "rd_webrtc_hw_codec_label": "硬件编码器:",
    "rd_webrtc_hw_codec_off": "关闭 (用 libx264)",
    "rd_webrtc_hw_codec_off_status": "硬件编码已关闭 (使用 libx264)",
    "rd_webrtc_hw_codec_active": "硬件编码启用中: {codec}",
    "rd_webrtc_hw_codec_failed": "硬件编码器 {codec} 不可用",
    "rd_webrtc_adaptive": "依网络自动调 FPS",
    "rd_webrtc_sessions_count": "已连接 viewer: {n}",
    "rd_webrtc_send_mic": "发送麦克风",
    "rd_webrtc_recv_mic": "接收 viewer 麦克风 (本机播放)",
    "rd_webrtc_send_file": "发送文件...",
    "rd_webrtc_file_sent": "已发送: {name}",
    "rd_webrtc_push_file": "推送文件到 viewer...",
    "rd_webrtc_no_viewers": "目前没有 viewer 连线可推送",
    "rd_webrtc_push_done": "已把 {name} 推送给 {n} 个 viewer",
    "rd_webrtc_file_received": "已收到: {name}",
    # 远程文件浏览
    "rd_webrtc_remote_files_group": "Host 的 inbox 文件",
    "rd_webrtc_browse_refresh": "刷新",
    "rd_webrtc_browse_pull": "下载",
    "rd_webrtc_browse_delete": "删除",
    "rd_webrtc_browse_col_name": "文件名",
    "rd_webrtc_browse_col_size": "大小 (bytes)",
    "rd_webrtc_browse_col_mtime": "修改时间",
    "rd_webrtc_browse_delete_confirm": "确定要从 host inbox 删除 '{name}' 吗？",
    "rd_webrtc_browse_op_ok": "{name} 完成",
    "rd_webrtc_browse_op_failed": "{name} 失败: {error}",
    "rd_webrtc_browse_dnd_hint": "拖放文件到这里即上传到 host 的 inbox。",
    "rd_webrtc_browse_copy_name": "复制文件名",
    "rd_webrtc_browse_delete_many_confirm": "确定要从 host inbox 删除 {n} 个文件吗？",
    "rd_webrtc_upload_done": "已上传 {n} 个文件",
    # 反向屏幕共享
    "rd_webrtc_accept_viewer_video": "接收 viewer 的屏幕共享",
    "rd_webrtc_share_my_screen": "把我的屏幕共享给 host",
    "rd_webrtc_viewer_screen_title": "Viewer 的屏幕",
    "rd_webrtc_accept_opus_audio": "接收 viewer 的 Opus 音频",
    "rd_webrtc_share_opus_mic": "用 Opus 把我的麦克风发送到 host",
    # KnownHosts 对话框
    "rd_webrtc_manage_known_hosts": "已知 host...",
    "rd_webrtc_known_hosts_title": "已知 host",
    "rd_webrtc_kh_col_host": "Host ID",
    "rd_webrtc_kh_col_app_fp": "App fingerprint",
    "rd_webrtc_kh_col_dtls_fp": "DTLS fingerprint",
    "rd_webrtc_kh_forget": "忘记所选",
    "rd_webrtc_kh_clear_all": "全部清除",
    "rd_webrtc_kh_close": "关闭",
    "rd_webrtc_kh_clear_confirm": "确定忘掉所有已知 host?",
    "rd_webrtc_kh_copy_app": "复制 app fp",
    "rd_webrtc_kh_copy_dtls": "复制 DTLS fp",
    "rd_webrtc_kh_add": "手动添加",
    "rd_webrtc_kh_add_host_ph": "host_id (如 abcd1234)",
    "rd_webrtc_kh_add_app_ph": "app fingerprint (64 个 hex; 可选)",
    "rd_webrtc_kh_add_dtls_ph": "DTLS fingerprint (AB:CD:...; 可选)",
    "rd_webrtc_auto_reconnect": "断线自动重连",
    "rd_webrtc_reconnecting": "重连中 (第 {n}/{max} 次)...",
    "rd_webrtc_reconnect_giveup": "重连次数用尽",
    "rd_webrtc_reconnect_max": "最大次数:",
    "rd_webrtc_reconnect_delay": "起始延迟:",
    "rd_webrtc_kh_import": "导入...",
    "rd_webrtc_kh_export": "导出...",
    "rd_webrtc_kh_import_bad": "导入的文件不是 known-hosts JSON",
    "rd_webrtc_kh_import_overwrite": "'{host}' 已存在，是否覆盖?",
    "rd_webrtc_kh_import_done": "导入 {added}，跳过 {skipped}",
    "rd_webrtc_quality_unknown": "暂无连线品质数据",
    "rd_webrtc_quality_good": "良好 (RTT < 80ms, 丢包 < 1%)",
    "rd_webrtc_quality_fair": "尚可 (RTT < 200ms, 丢包 < 5%)",
    "rd_webrtc_quality_poor": "差 (高 RTT 或高丢包)",
    "rd_webrtc_kh_col_last_seen": "最近连线",
    "rd_webrtc_sess_col_id": "Session",
    "rd_webrtc_sess_col_viewer": "Viewer ID",
    "rd_webrtc_sess_col_state": "状态",
    "rd_webrtc_sess_col_connected": "连接时间",
    "rd_webrtc_disconnect_selected": "断开所选 session",
    "rd_webrtc_kh_stale_tip": "超过 90 天未连接，建议重新验证",
    "rd_webrtc_kh_forget_stale": "清掉所有过期",
    "rd_webrtc_kh_forget_stale_confirm": "确定清掉 {n} 个过期 entry?",
    "rd_webrtc_kh_no_stale": "没有过期 entry 需要清",
    "rd_webrtc_sess_trust_viewer": "信任这个 viewer",
    "rd_webrtc_sess_copy_id": "复制 session id",
    "rd_webrtc_favorite": "加入收藏 ★",
    "rd_webrtc_unfavorite": "移除收藏",
    "rd_webrtc_trust_import": "导入...",
    "rd_webrtc_trust_export": "导出...",
    "rd_webrtc_trust_import_done": "导入 {n} 个信任 viewer",
    "rd_webrtc_my_fingerprint": "本机 fingerprint:",
    "rd_webrtc_copy_fingerprint": "复制",
    "rd_webrtc_ab_export": "导出通讯录...",
    "rd_webrtc_ab_import": "导入通讯录...",
    "rd_webrtc_ab_clear": "全部清空",
    "rd_webrtc_ab_clear_confirm": "确定清空整个通讯录?",
    "rd_webrtc_ab_import_done": "导入 {n} 个 entry",
    "rd_webrtc_tray_idle": "AutoControl host: 空闲",
    "rd_webrtc_tray_running": "AutoControl host: {n} 个 viewer",
    "rd_webrtc_tray_open": "打开窗口",
    "rd_webrtc_tray_stop": "停止 host",
    "rd_webrtc_tray_quit": "退出",
    "rd_webrtc_region_label": "区域 (x,y,w,h):",
    "rd_webrtc_region_placeholder": "留空代表整屏",
    "rd_webrtc_pick_region": "框选区域...",
    "rd_webrtc_monitor_all": "全部屏幕",
    "rd_webrtc_max_bitrate": "最大带宽:",
    "rd_webrtc_ip_whitelist": "自动接受 IP CIDR:",
    "rd_webrtc_ip_whitelist_ph": "每行一个 CIDR, 例如 192.168.1.0/24",
    "rd_webrtc_tag_filter": "标签:",
    "rd_webrtc_tag_all": "全部",
    "rd_webrtc_edit_tags": "编辑标签...",
    "rd_webrtc_tags_prompt": "用逗号分隔的标签:",
    "rd_webrtc_view_audit": "Audit log...",
    "rd_webrtc_audit_title": "Audit log",
    "rd_webrtc_audit_filter_type": "事件类型:",
    "rd_webrtc_audit_filter_type_ph": "auth_ok / auth_fail / file_received / ...",
    "rd_webrtc_audit_filter_host": "Host:",
    "rd_webrtc_audit_refresh": "刷新",
    "rd_webrtc_audit_col_ts": "时间戳",
    "rd_webrtc_audit_col_type": "事件",
    "rd_webrtc_audit_col_host": "Host",
    "rd_webrtc_audit_col_viewer": "Viewer",
    "rd_webrtc_audit_col_detail": "细节",
    "rd_webrtc_lan_browse": "LAN...",
    "rd_webrtc_lan_title": "LAN 探索",
    "rd_webrtc_lan_help": "Host 通过 mDNS 广播 _autocontrol._tcp。",
    "rd_webrtc_lan_col_host": "Host ID",
    "rd_webrtc_lan_col_ip": "IP",
    "rd_webrtc_lan_col_signaling": "Signaling URL",
    "rd_webrtc_lan_col_name": "mDNS 名称",
    "rd_webrtc_lan_use": "使用此条",
    "rd_webrtc_host_voice": "把我的声音发送 (host → viewers)",
    "rd_webrtc_pen_off": "画笔 关",
    "rd_webrtc_pen_on": "画笔 开",
    "rd_webrtc_pen_clear": "清除画笔",
    "rd_webrtc_sync_group": "文件夹同步",
    "rd_webrtc_sync_dir": "本机目录:",
    "rd_webrtc_sync_dir_ph": "要镜像到 host inbox 的目录",
    "rd_webrtc_sync_start": "开始同步",
    "rd_webrtc_sync_stop": "停止同步",
    "rd_webrtc_sync_dir_required": "请先选一个本机目录",
    "rd_webrtc_browse": "浏览...",

    # Auto Click Tab
    "interval_time": "间隔时间 (ms):",
    "cursor_x": "光标 X:",
    "cursor_y": "光标 Y:",
    "mouse_button": "鼠标按键:",
    "keyboard_button": "键盘按键:",
    "click_type": "点击类型:",
    "single_click": "单击",
    "double_click": "双击",
    "input_method": "输入方式:",
    "mouse_radio": "鼠标",
    "keyboard_radio": "键盘",
    "repeat_until_stopped_radio": "重复直到停止",
    "repeat_radio": "重复",
    "times": "次数",
    "start": "开始",
    "stop": "停止",
    "hotkey_label": "组合键（逗号分隔）：",
    "hotkey_send": "发送组合键",
    "write_label": "输入文字:",
    "write_send": "输入",
    "mouse_scroll_label": "滚动值:",
    "scroll_direction_label": "滚动方向:",
    "scroll_send": "滚动",
    "get_position": "获取鼠标位置",
    "current_position": "当前位置:",

    # Screenshot Tab
    "take_screenshot": "截取屏幕",
    "save_screenshot": "保存截图",
    "file_path_label": "文件路径:",
    "browse": "浏览",
    "region_label": "区域 (x1, y1, x2, y2):",
    "pick_region": "框选区域",
    "crop_template": "框选模板",
    "get_pixel_label": "获取像素颜色",
    "pixel_x": "X:",
    "pixel_y": "Y:",
    "pixel_result": "像素颜色:",
    "screen_size_label": "屏幕大小:",
    "get_screen_size": "获取屏幕大小",

    # Image Detection Tab
    "template_image": "模板图像:",
    "threshold_label": "阈值 (0.0~1.0):",
    "locate_image": "定位图像",
    "locate_all": "定位全部",
    "locate_click": "定位并点击",
    "detection_result": "检测结果:",
    "draw_image_check": "标记检测结果",

    # Record / Playback Tab
    "start_record": "开始录制",
    "stop_record": "停止录制",
    "playback": "回放",
    "save_record": "保存为 JSON",
    "load_record": "载入 JSON",
    "record_status": "状态:",
    "record_idle": "闲置",
    "record_recording": "录制中...",
    "record_list_label": "已录制动作:",

    # Script Executor Tab
    "load_script": "载入脚本 (JSON)",
    "execute_script": "执行",
    "execute_dir_label": "执行目录:",
    "execute_dir": "执行全部",
    "script_content": "脚本内容:",
    "execution_result": "执行结果:",

    # Screen Recording Tab
    "recorder_name": "录像器名称:",
    "output_file": "输出文件:",
    "codec_label": "编码器:",
    "fps_label": "FPS:",
    "resolution_label": "分辨率 (宽x高):",
    "start_screen_record": "开始录像",
    "stop_screen_record": "停止录像",
    "screen_record_status": "状态:",

    # Shell Tab
    "shell_command_label": "Shell 命令:",
    "execute_shell": "执行",
    "shell_output": "输出:",
    "start_exe_label": "可执行文件路径:",
    "start_exe": "启动可执行文件",

    # Report Tab
    "report_name": "报告名称:",
    "generate_html_report": "生成 HTML 报告",
    "generate_json_report": "生成 JSON 报告",
    "generate_xml_report": "生成 XML 报告",
    "enable_test_record": "启用测试记录",
    "disable_test_record": "禁用测试记录",
    "test_record_status": "测试记录:",
    "report_result": "结果:",

    # Hotkeys Tab
    "hk_combo_label": "组合键:",
    "hk_script_label": "脚本:",
    "hk_bind": "绑定",
    "hk_remove_selected": "移除所选",
    "hk_start_daemon": "启动服务",
    "hk_stop_daemon": "停止服务",
    "hk_daemon_stopped": "服务已停止",
    "hk_daemon_running": "服务运行中",
    "hk_col_id": "ID",
    "hk_col_combo": "组合键",
    "hk_col_script": "脚本",
    "hk_col_fired": "已触发",
    "hk_dialog_select_script": "选择脚本",

    # Triggers Tab
    "tr_script_label": "脚本:",
    "tr_type_label": "类型:",
    "tr_repeat": "重复",
    "tr_add": "新增触发器",
    "tr_remove_selected": "移除所选",
    "tr_start_engine": "启动引擎",
    "tr_stop_engine": "停止引擎",
    "tr_engine_stopped": "引擎已停止",
    "tr_engine_running": "引擎运行中",
    "tr_type_image": "图像出现",
    "tr_type_window": "窗口出现",
    "tr_type_pixel": "像素匹配",
    "tr_type_file": "文件变更",
    "tr_image_label": "图像:",
    "tr_threshold_label": "阈值:",
    "tr_title_contains_label": "标题包含:",
    "tr_watch_label": "监看路径:",
    "tr_col_id": "ID",
    "tr_col_type": "类型",
    "tr_col_detail": "细节",
    "tr_col_fired": "已触发",
    "tr_col_enabled": "启用",
    "tr_yes": "是",
    "tr_no": "否",
    "tr_dialog_select_script": "选择脚本",
    "tr_dialog_select_image": "选择图像",
    "tr_dialog_select_file": "选择要监看的文件",

    # Plugins Tab
    "pl_dir_label": "插件目录:",
    "pl_load": "载入并注册",
    "pl_no_loaded": "尚未载入插件",
    "pl_registered_label": "已注册命令:",
    "pl_dialog_plugin_dir": "插件目录",

    # Scheduler Tab
    "sch_script_label": "脚本:",
    "sch_interval_label": "每 (秒):",
    "sch_repeat": "重复",
    "sch_add": "新增",
    "sch_remove_selected": "移除所选",
    "sch_start": "启动调度器",
    "sch_stop": "停止调度器",
    "sch_status_running": "调度器运行中",
    "sch_status_stopped": "调度器已停止",
    "sch_col_job_id": "任务 ID",
    "sch_col_script": "脚本",
    "sch_col_interval": "间隔 (秒)",
    "sch_col_runs": "执行次数",
    "sch_col_enabled": "启用",
    "sch_dialog_select_script": "选择脚本",

    # Socket / REST Tab
    "ss_tcp_group": "TCP Socket 服务器",
    "ss_rest_group": "REST API 服务器",
    "ss_host_label": "主机:",
    "ss_port_label": "端口:",
    "ss_tcp_any_check": "绑定 TCP 至 0.0.0.0（暴露于网络）",
    "ss_rest_any_check": "绑定 REST 至 0.0.0.0（暴露于网络）",
    "ss_tcp_stopped": "TCP 已停止",
    "ss_rest_stopped": "REST 已停止",
    "ss_tcp_start": "启动 TCP",
    "ss_tcp_stop": "停止 TCP",
    "ss_rest_start": "启动 REST",
    "ss_rest_stop": "停止 REST",

    # Live HUD Tab
    "hud_watchers_group": "监看器",
    "hud_start": "启动 HUD",
    "hud_stop": "停止 HUD",
    "hud_clear": "清除日志",
    "hud_recent_log": "最近日志:",
    "hud_mouse_prefix": "鼠标:",
    "hud_pixel_prefix": "像素:",

    # Window Manager Tab
    "win_refresh": "刷新",
    "win_filter_placeholder": "以标题子字符串过滤",
    "win_col_hwnd": "HWND",
    "win_col_title": "标题",
    "win_focus_selected": "聚焦所选",
    "win_close_selected": "关闭所选",
    "win_status_count": "{n} 个窗口",

    # Recording Editor Tab
    "re_file_label": "文件:",
    "re_browse": "浏览",
    "re_load": "载入",
    "re_save_as": "另存为",
    "re_trim_start": "裁剪起点:",
    "re_trim_end": "终点:",
    "re_apply_trim": "应用裁剪",
    "re_remove_selected": "移除所选",
    "re_delay_x": "延迟倍数",
    "re_floor_ms": "下限 ms:",
    "re_apply_delays": "应用延迟",
    "re_scale_x": "缩放 x:",
    "re_scale_y": "y:",
    "re_apply_scale": "应用缩放",
    "re_keep_mouse": "仅保留鼠标",
    "re_keep_keyboard": "仅保留键盘",
    "re_preview": "预览:",
    "re_dialog_open": "打开录制",
    "re_dialog_save": "保存录制",

    # Script Builder Tab
    "sb_delete": "删除",
    "sb_up": "上移",
    "sb_down": "下移",
    "sb_load_json": "载入 JSON",
    "sb_save_json": "保存 JSON",
    "sb_run": "执行",
    "sb_add_step": "新增步骤",
    "sb_dialog_save": "保存脚本",
    "sb_dialog_load": "载入脚本",
    "sb_no_step_selected": "尚未选取步骤",

    # Language
    "language_label": "语言:",

    # Run History Tab
    "rh_filter_label": "来源:",
    "rh_source_all": "全部",
    "rh_source_scheduler": "调度器",
    "rh_source_trigger": "触发器",
    "rh_source_hotkey": "热键",
    "rh_source_manual": "手动",
    "rh_source_rest": "REST",
    "rh_refresh": "刷新",
    "rh_clear": "清除",
    "rh_confirm_clear": "要删除全部执行记录吗？此操作无法撤销。",
    "rh_count_label": "{n} 条记录",
    "rh_col_id": "ID",
    "rh_col_source": "来源",
    "rh_col_target": "目标",
    "rh_col_script": "脚本",
    "rh_col_started": "开始时间",
    "rh_col_duration": "耗时",
    "rh_col_status": "状态",
    "rh_status_ok": "成功",
    "rh_status_error": "错误",
    "rh_status_running": "执行中",
    "rh_col_artifact": "截图",
    "rh_open_artifact": "打开截图",
    "rh_no_artifact": "所选记录没有截图。",
    "rh_artifact_missing": "截图文件已不存在。",
    "rh_timeline_heading": "时间轴（左旧右新）",
    "rh_preview_heading": "预览",
    "rh_preview_empty": "请选择一条记录预览。",
    "rh_preview_no_artifact": "此次执行没有截图。",

    # Webhooks tab
    "wh_server_group": "HTTP 服务器",
    "wh_add_group": "新增 webhook",
    "wh_host_label": "主机：",
    "wh_port_label": "端口：",
    "wh_start": "启动",
    "wh_stop": "停止",
    "wh_started": "正在监听 {host}:{port}",
    "wh_running": "运行中 {host}:{port}",
    "wh_stopped": "服务器已停止。",
    "wh_path_label": "路径：",
    "wh_script_label": "脚本：",
    "wh_browse": "浏览",
    "wh_methods_label": "方法：",
    "wh_token_label": "Token：",
    "wh_token_placeholder": "可选 Bearer token",
    "wh_register": "注册 webhook",
    "wh_remove": "删除所选",
    "wh_path_and_script_required": "请输入路径和脚本文件。",
    "wh_col_id": "ID",
    "wh_col_path": "路径",
    "wh_col_methods": "方法",
    "wh_col_script": "脚本",
    "wh_col_fired": "触发次数",
    "wh_col_token": "需验证？",
    "wh_yes": "是",
    "wh_no": "否",

    # Secrets tab
    "secret_unlock_group": "密钥库",
    "secret_manage_group": "密钥",
    "secret_passphrase_label": "通行码：",
    "secret_passphrase_placeholder": "密钥库通行码",
    "secret_init": "创建密钥库",
    "secret_init_done": "密钥库已创建并解锁。",
    "secret_unlock": "解锁",
    "secret_lock": "锁定",
    "secret_add": "添加密钥",
    "secret_remove": "删除",
    "secret_change_passphrase": "修改通行码",
    "secret_change_done": "密钥库已使用新通行码重新加密。",
    "secret_status_uninitialized": "尚未创建密钥库。",
    "secret_status_unlocked": "密钥库已解锁。",
    "secret_status_locked": "密钥库已锁定。",
    "secret_passphrase_required": "请先输入通行码。",
    "secret_wrong_passphrase": "通行码错误。",
    "secret_unlock_first": "请先解锁密钥库再管理密钥。",
    "secret_name_prompt": "密钥名称（脚本以 ${secrets.NAME} 引用）：",
    "secret_value_prompt": "密钥内容：",
    "secret_old_passphrase_prompt": "当前通行码：",
    "secret_new_passphrase_prompt": "新通行码：",

    # Profiler tab
    "prof_enable": "启用性能分析",
    "prof_disable": "停用性能分析",
    "prof_reset": "清除统计",
    "prof_refresh": "刷新",
    "prof_running": "性能分析中。",
    "prof_paused": "尚未启用性能分析。",
    "prof_total_label": "已追踪 {n} 个动作",
    "prof_total_empty": "暂无数据。",
    "prof_col_name": "动作",
    "prof_col_calls": "次数",
    "prof_col_total": "总时间",
    "prof_col_avg": "平均",
    "prof_col_min": "最短",
    "prof_col_max": "最长",
    "prof_col_share": "占比",

    # Accessibility Tab
    "a11y_app_label": "应用:",
    "a11y_app_placeholder": "例如：计算器",
    "a11y_name_label": "名称包含:",
    "a11y_name_placeholder": "部分匹配",
    "a11y_refresh": "刷新",
    "a11y_click_selected": "点击所选",
    "a11y_col_app": "应用",
    "a11y_col_role": "角色",
    "a11y_col_name": "名称",
    "a11y_col_bounds": "边界",
    "a11y_col_center": "中心",
    "a11y_count_label": "{n} 个元素",
    "a11y_no_selection": "请先选择一行",
    "a11y_click_not_found": "找不到可点击的元素",

    # VLM (AI Locator) Tab
    "vlm_desc_label": "描述：",
    "vlm_desc_placeholder": "例如：绿色的提交按钮",
    "vlm_model_label": "模型：",
    "vlm_model_placeholder": "选填（例如 claude-opus-4-7）",
    "vlm_locate": "定位",
    "vlm_click": "定位并点击",
    "vlm_result": "位置：({x}, {y})",
    "vlm_ok": "完成",
    "vlm_not_found": "找不到匹配元素",
    "vlm_error": "错误",
    "vlm_desc_required": "请先输入目标描述",

    # OCR Reader Tab
    "ocr_region_group": "区域",
    "ocr_region_label": "x, y, w, h:",
    "ocr_region_placeholder": "留空代表整个屏幕",
    "ocr_pick_region": "选取区域...",
    "ocr_lang_label": "语言:",
    "ocr_min_conf_label": "最低置信度:",
    "ocr_regex_label": "Regex 表达式:",
    "ocr_regex_placeholder": r"例如 Order#\d+",
    "ocr_dump_region": "抓取区域全部文字",
    "ocr_find_regex": "用 regex 搜索",
    "ocr_results_label": "结果:",
    "ocr_match_count": "{n} 个匹配",
    "ocr_region_invalid": "区域必须为 4 个逗号分隔整数",
    "ocr_min_conf_invalid": "置信度需为数字",
    "ocr_regex_required": "请先输入 regex 表达式",
    "ocr_regex_invalid": "Regex 不正确",

    # Variables Tab
    "vars_current_group": "当前作用域",
    "vars_col_name": "名称",
    "vars_col_value": "值",
    "vars_count": "共 {n} 个变量",
    "vars_refresh": "刷新",
    "vars_clear": "全部清除",
    "vars_clear_confirm": "确定清空所有运行期变量？",
    "vars_set_group": "新增单个变量",
    "vars_name_label": "名称:",
    "vars_name_placeholder": "变量名",
    "vars_name_required": "请输入名称",
    "vars_value_label": "值:",
    "vars_value_placeholder": "JSON 字面量（42、\"text\"、[1,2]）或纯字符串",
    "vars_set_btn": "设定",
    "vars_seed_group": "从 JSON 载入",
    "vars_seed_placeholder": "{\"counter\": 0, \"items\": [\"a\", \"b\"]}",
    "vars_seed_btn": "合并 JSON 到作用域",
    "vars_seed_required": "请先粘贴 JSON 对象",
    "vars_seed_invalid": "JSON 格式错误",
    "vars_seed_not_object": "JSON 必须是对象",

    # LLM Planner Tab
    "llm_desc_group": "描述要做的任务",
    "llm_desc_placeholder": (
        "例如：打开记事本、输入 'hello world'、另存为 test.txt"
    ),
    "llm_model_label": "模型:",
    "llm_model_placeholder": "选填（例如 claude-opus-4-7）",
    "llm_plan_btn": "规划",
    "llm_run_btn": "执行此规划",
    "llm_plan_group": "已规划的指令",
    "llm_result_group": "执行结果",
    "llm_desc_required": "请先描述要自动化的任务",
    "llm_planning": "规划中...",
    "llm_plan_count": "已规划 {n} 个指令",
    "llm_no_plan": "请先按下「规划」",
    "llm_running": "执行中...",
    "llm_run_done": "完成",

    # Remote Desktop Tab
    "rd_host_tab": "被远程（本机）",
    "rd_viewer_tab": "远程他人（控制他机）",
    "rd_host_security_warning": (
        "警告：取得本机 host:port 与 token 的人，可以完全控制本机的鼠标／键盘。"
        "默认仅绑 127.0.0.1；要对外请透过 SSH tunnel 或可信的 VPN。"
    ),
    "rd_host_config_group": "Host 设置",
    "rd_viewer_config_group": "连接到远程 Host",
    "rd_token_label": "Token:",
    "rd_token_placeholder": "共享密钥（HMAC key）",
    "rd_token_generate": "生成",
    "rd_bind_label": "地址:",
    "rd_port_label": "端口:",
    "rd_fps_label": "FPS:",
    "rd_quality_label": "JPEG 质量:",
    "rd_host_start": "启动 Host",
    "rd_host_stop": "停止 Host",
    "rd_host_status_running": "运行中 端口 {port} — {n} 个 viewer",
    "rd_host_status_stopped": "Host 已停止",
    "rd_host_preview_label": "预览（viewer 看到的画面）：",
    "rd_host_card_group": "连线",
    "rd_viewer_card_group": "连接到远程 Host",
    "rd_host_basics_group": "连接设置",
    "rd_advanced_group": "高级",
    "rd_host_copy_share": "复制分享信息",
    "rd_host_copy_share_unavailable": "请先启动 Host 再分享。",
    "rd_host_copy_share_confirm": (
        "复制会把地址、端口、Host ID 与 TOKEN 一起放到剪贴板。"
        "粘贴出去的对象等同取得本机完整控制权，确定?"
    ),
    "rd_badge_running": "RUNNING · :{port} · {n} 个 viewer",
    "rd_badge_stopped": "STOPPED",
    "rd_badge_idle": "未连接",
    "rd_badge_live": "已连接",
    "rd_host_id_group": "Host ID（给远程的人）",
    "rd_host_id_label": "Host ID:",
    "rd_host_id_copy": "复制",
    "rd_transport_label": "传输协议:",
    "rd_tls_cert_label": "TLS 证书:",
    "rd_tls_cert_placeholder": "PEM 证书路径（选填）",
    "rd_tls_key_label": "TLS 密钥:",
    "rd_tls_key_placeholder": "PEM 私钥路径（选填）",
    "rd_tls_both_required": "TLS 证书与密钥必须一并提供",
    "rd_tls_insecure": "忽略证书验证（自签用）",
    "rd_browse": "浏览...",
    "rd_enable_audio": "串流系统音频（sounddevice）",
    "rd_viewer_audio_play": "播放接收的音频（sounddevice）",
    "rd_viewer_push_clipboard": "把本机剪贴板文字发送到 Host",
    "rd_viewer_send_file": "发送文件...",
    "rd_dest_path_prompt": "{name} 在远程的目的路径:",
    "rd_clipboard_empty": "本机剪贴板是空的",
    "rd_clipboard_sent": "剪贴板已发送到 Host",
    "rd_viewer_clipboard_received": "已从 Host 同步剪贴板",
    "rd_progress_label": "传输进度: {done} / {total} bytes",
    "rd_progress_done": "传输完成: {path}",
    "rd_progress_failed": "传输失败: {error}",
    "rd_viewer_connect": "连接",
    "rd_viewer_disconnect": "断开",
    "rd_viewer_required_fields": "地址、端口、token 都必须填写。",
    "rd_viewer_status_connected": "已连接 — 正在接收画面",
    "rd_viewer_status_idle": "未连接",
    "rd_viewer_error": "远程桌面错误",
    "rd_remote_screen_title": "远程桌面 — 实时会话",
    "rd_remote_screen_title_with_id": "远程桌面 — {host_id}",

    # Menu bar
    "menu_file": "文件",
    "menu_file_open_script": "打开脚本...",
    "menu_file_exit": "退出",
    "menu_view": "视图",
    "menu_view_tabs": "分页",
    "menu_view_cat_core": "核心",
    "menu_view_cat_editing": "编辑",
    "menu_view_cat_detection": "检测与视觉",
    "menu_view_cat_automation": "自动化引擎",
    "menu_view_cat_system": "系统",
    "menu_view_text_size": "文字大小",
    "menu_view_text_auto": "自动（依屏幕）",
    "menu_view_text_small": "小 (10pt)",
    "menu_view_text_normal": "标准 (12pt)",
    "menu_view_text_large": "大 (14pt)",
    "menu_view_text_xlarge": "特大 (16pt)",
    "menu_view_text_xxlarge": "超大 (20pt)",
    "menu_tools": "工具",
    "menu_tools_start_hotkeys": "启动热键守护进程",
    "menu_tools_start_scheduler": "启动调度器",
    "menu_tools_start_triggers": "启动触发器引擎",
    "menu_language": "语言",
    "menu_help": "帮助",
    "menu_help_about": "关于 AutoControlGUI",
}
