simplified_chinese_word_dict = {
    "application_name": "AutoControlGUI",

    # Tabs
    "tab_auto_click": "自动点击",
    "tab_screenshot": "屏幕截图",
    "tab_image_detect": "图像检测",
    "tab_record": "录制 / 回放",
    "tab_script": "脚本执行",
    "tab_script_builder": "脚本编辑器",
    "tab_recording_editor": "录制编辑器",
    "tab_window_manager": "窗口管理",
    "tab_scheduler": "调度器",
    "tab_socket_server": "Socket 服务器",
    "tab_live_hud": "实时监看",
    "tab_hotkeys": "全局热键",
    "tab_triggers": "事件触发器",
    "tab_plugins": "插件",
    "tab_screen_record": "屏幕录像",
    "tab_shell": "Shell 命令",
    "tab_report": "报告生成",

    # Auto Click Tab
    "interval_time": "间隔时间 (ms):",
    "cursor_x": "光标 X:",
    "cursor_y": "光标 Y:",
    "mouse_button": "鼠标按键:",
    "keyboard_button": "键盘按键:",
    "click_type": "点击类型:",
    "single_click": "单击",
    "double_click": "双击",
    "input_method": "输入方式:",
    "mouse_radio": "鼠标",
    "keyboard_radio": "键盘",
    "repeat_until_stopped_radio": "重复直到停止",
    "repeat_radio": "重复",
    "times": "次数",
    "start": "开始",
    "stop": "停止",
    "hotkey_label": "组合键（逗号分隔）：",
    "hotkey_send": "发送组合键",
    "write_label": "输入文字:",
    "write_send": "输入",
    "mouse_scroll_label": "滚动值:",
    "scroll_direction_label": "滚动方向:",
    "scroll_send": "滚动",
    "get_position": "获取鼠标位置",
    "current_position": "当前位置:",

    # Screenshot Tab
    "take_screenshot": "截取屏幕",
    "save_screenshot": "保存截图",
    "file_path_label": "文件路径:",
    "browse": "浏览",
    "region_label": "区域 (x1, y1, x2, y2):",
    "pick_region": "框选区域",
    "crop_template": "框选模板",
    "get_pixel_label": "获取像素颜色",
    "pixel_x": "X:",
    "pixel_y": "Y:",
    "pixel_result": "像素颜色:",
    "screen_size_label": "屏幕大小:",
    "get_screen_size": "获取屏幕大小",

    # Image Detection Tab
    "template_image": "模板图像:",
    "threshold_label": "阈值 (0.0~1.0):",
    "locate_image": "定位图像",
    "locate_all": "定位全部",
    "locate_click": "定位并点击",
    "detection_result": "检测结果:",
    "draw_image_check": "标记检测结果",

    # Record / Playback Tab
    "start_record": "开始录制",
    "stop_record": "停止录制",
    "playback": "回放",
    "save_record": "保存为 JSON",
    "load_record": "载入 JSON",
    "record_status": "状态:",
    "record_idle": "闲置",
    "record_recording": "录制中...",
    "record_list_label": "已录制动作:",

    # Script Executor Tab
    "load_script": "载入脚本 (JSON)",
    "execute_script": "执行",
    "execute_dir_label": "执行目录:",
    "execute_dir": "执行全部",
    "script_content": "脚本内容:",
    "execution_result": "执行结果:",

    # Screen Recording Tab
    "recorder_name": "录像器名称:",
    "output_file": "输出文件:",
    "codec_label": "编码器:",
    "fps_label": "FPS:",
    "resolution_label": "分辨率 (宽x高):",
    "start_screen_record": "开始录像",
    "stop_screen_record": "停止录像",
    "screen_record_status": "状态:",

    # Shell Tab
    "shell_command_label": "Shell 命令:",
    "execute_shell": "执行",
    "shell_output": "输出:",
    "start_exe_label": "可执行文件路径:",
    "start_exe": "启动可执行文件",

    # Report Tab
    "report_name": "报告名称:",
    "generate_html_report": "生成 HTML 报告",
    "generate_json_report": "生成 JSON 报告",
    "generate_xml_report": "生成 XML 报告",
    "enable_test_record": "启用测试记录",
    "disable_test_record": "禁用测试记录",
    "test_record_status": "测试记录:",
    "report_result": "结果:",

    # Hotkeys Tab
    "hk_combo_label": "组合键:",
    "hk_script_label": "脚本:",
    "hk_bind": "绑定",
    "hk_remove_selected": "移除所选",
    "hk_start_daemon": "启动服务",
    "hk_stop_daemon": "停止服务",
    "hk_daemon_stopped": "服务已停止",
    "hk_daemon_running": "服务运行中",
    "hk_col_id": "ID",
    "hk_col_combo": "组合键",
    "hk_col_script": "脚本",
    "hk_col_fired": "已触发",
    "hk_dialog_select_script": "选择脚本",

    # Triggers Tab
    "tr_script_label": "脚本:",
    "tr_type_label": "类型:",
    "tr_repeat": "重复",
    "tr_add": "新增触发器",
    "tr_remove_selected": "移除所选",
    "tr_start_engine": "启动引擎",
    "tr_stop_engine": "停止引擎",
    "tr_engine_stopped": "引擎已停止",
    "tr_engine_running": "引擎运行中",
    "tr_type_image": "图像出现",
    "tr_type_window": "窗口出现",
    "tr_type_pixel": "像素匹配",
    "tr_type_file": "文件变更",
    "tr_image_label": "图像:",
    "tr_threshold_label": "阈值:",
    "tr_title_contains_label": "标题包含:",
    "tr_watch_label": "监看路径:",
    "tr_col_id": "ID",
    "tr_col_type": "类型",
    "tr_col_detail": "细节",
    "tr_col_fired": "已触发",
    "tr_col_enabled": "启用",
    "tr_yes": "是",
    "tr_no": "否",
    "tr_dialog_select_script": "选择脚本",
    "tr_dialog_select_image": "选择图像",
    "tr_dialog_select_file": "选择要监看的文件",

    # Plugins Tab
    "pl_dir_label": "插件目录:",
    "pl_load": "载入并注册",
    "pl_no_loaded": "尚未载入插件",
    "pl_registered_label": "已注册命令:",
    "pl_dialog_plugin_dir": "插件目录",

    # Scheduler Tab
    "sch_script_label": "脚本:",
    "sch_interval_label": "每 (秒):",
    "sch_repeat": "重复",
    "sch_add": "新增",
    "sch_remove_selected": "移除所选",
    "sch_start": "启动调度器",
    "sch_stop": "停止调度器",
    "sch_status_running": "调度器运行中",
    "sch_status_stopped": "调度器已停止",
    "sch_col_job_id": "任务 ID",
    "sch_col_script": "脚本",
    "sch_col_interval": "间隔 (秒)",
    "sch_col_runs": "执行次数",
    "sch_col_enabled": "启用",
    "sch_dialog_select_script": "选择脚本",

    # Socket / REST Tab
    "ss_tcp_group": "TCP Socket 服务器",
    "ss_rest_group": "REST API 服务器",
    "ss_host_label": "主机:",
    "ss_port_label": "端口:",
    "ss_tcp_any_check": "绑定 TCP 至 0.0.0.0（暴露于网络）",
    "ss_rest_any_check": "绑定 REST 至 0.0.0.0（暴露于网络）",
    "ss_tcp_stopped": "TCP 已停止",
    "ss_rest_stopped": "REST 已停止",
    "ss_tcp_start": "启动 TCP",
    "ss_tcp_stop": "停止 TCP",
    "ss_rest_start": "启动 REST",
    "ss_rest_stop": "停止 REST",

    # Live HUD Tab
    "hud_watchers_group": "监看器",
    "hud_start": "启动 HUD",
    "hud_stop": "停止 HUD",
    "hud_clear": "清除日志",
    "hud_recent_log": "最近日志:",
    "hud_mouse_prefix": "鼠标:",
    "hud_pixel_prefix": "像素:",

    # Window Manager Tab
    "win_refresh": "刷新",
    "win_filter_placeholder": "以标题子字符串过滤",
    "win_col_hwnd": "HWND",
    "win_col_title": "标题",
    "win_focus_selected": "聚焦所选",
    "win_close_selected": "关闭所选",
    "win_status_count": "{n} 个窗口",

    # Recording Editor Tab
    "re_file_label": "文件:",
    "re_browse": "浏览",
    "re_load": "载入",
    "re_save_as": "另存为",
    "re_trim_start": "裁剪起点:",
    "re_trim_end": "终点:",
    "re_apply_trim": "应用裁剪",
    "re_remove_selected": "移除所选",
    "re_delay_x": "延迟倍数",
    "re_floor_ms": "下限 ms:",
    "re_apply_delays": "应用延迟",
    "re_scale_x": "缩放 x:",
    "re_scale_y": "y:",
    "re_apply_scale": "应用缩放",
    "re_keep_mouse": "仅保留鼠标",
    "re_keep_keyboard": "仅保留键盘",
    "re_preview": "预览:",
    "re_dialog_open": "打开录制",
    "re_dialog_save": "保存录制",

    # Script Builder Tab
    "sb_delete": "删除",
    "sb_up": "上移",
    "sb_down": "下移",
    "sb_load_json": "载入 JSON",
    "sb_save_json": "保存 JSON",
    "sb_run": "执行",
    "sb_add_step": "新增步骤",
    "sb_dialog_save": "保存脚本",
    "sb_dialog_load": "载入脚本",
    "sb_no_step_selected": "尚未选取步骤",

    # Language
    "language_label": "语言:",

    # Menu bar
    "menu_file": "文件",
    "menu_file_open_script": "打开脚本...",
    "menu_file_exit": "退出",
    "menu_view": "视图",
    "menu_view_tabs": "分页",
    "menu_tools": "工具",
    "menu_tools_start_hotkeys": "启动热键守护进程",
    "menu_tools_start_scheduler": "启动调度器",
    "menu_tools_start_triggers": "启动触发器引擎",
    "menu_language": "语言",
    "menu_help": "帮助",
    "menu_help_about": "关于 AutoControlGUI",
}
