traditional_chinese_word_dict = {
    # Main
    "application_name": "AutoControlGUI",

    # Tabs
    "tab_auto_click": "自動點擊",
    "tab_screenshot": "螢幕截圖",
    "tab_image_detect": "影像偵測",
    "tab_record": "錄製 / 回放",
    "tab_script": "腳本執行",
    "tab_script_builder": "腳本編輯器",
    "tab_recording_editor": "錄製後製",
    "tab_window_manager": "視窗管理",
    "tab_scheduler": "排程器",
    "tab_socket_server": "Socket 伺服器",
    "tab_live_hud": "即時監看",
    "tab_hotkeys": "全域熱鍵",
    "tab_triggers": "事件觸發器",
    "tab_plugins": "外掛",
    "tab_screen_record": "螢幕錄影",
    "tab_shell": "Shell 命令",
    "tab_report": "報告產生",
    "tab_run_history": "執行紀錄",
    "tab_accessibility": "無障礙樹",
    "tab_vlm": "AI 定位",
    "tab_ocr_reader": "OCR 讀取",
    "tab_variables": "執行期變數",
    "tab_llm_planner": "LLM 腳本規劃",
    "tab_remote_desktop": "遠端桌面",
    "tab_rest_api": "REST API",
    "tab_admin_console": "管理主控台",
    "tab_audit_log": "稽核紀錄",
    "tab_inspector": "封包監測",
    "tab_usb_devices": "USB 裝置",
    "tab_diagnostics": "診斷",

    # 診斷分頁
    "diag_run": "執行診斷",
    "diag_summary_ok": "{count} 項檢查全部通過。",
    "diag_summary_failed": "{count} 項檢查中有 {failed} 項失敗。",
    "diag_col_name": "檢查項目",
    "diag_col_severity": "嚴重度",
    "diag_col_status": "狀態",
    "diag_col_detail": "詳情",
    "diag_status_ok": "正常",
    "diag_status_fail": "失敗",

    # USB 裝置分頁
    "usb_backend_label": "後端:",
    "usb_refresh": "重新整理",
    "usb_col_vid": "VID",
    "usb_col_pid": "PID",
    "usb_col_manufacturer": "製造商",
    "usb_col_product": "產品",
    "usb_col_serial": "序號",
    "usb_col_location": "匯流排 / 位置",
    "usb_auto_refresh": "自動更新＋hotplug 監測",
    "usb_events_idle": "hotplug 監測中：自上次更新以來無變化。",
    "usb_events_recent": "近期 hotplug：{text}",

    # USB passthrough ACL 提示對話框
    "usb_prompt_title": "USB 裝置使用請求",
    "usb_prompt_intro": "遠端 viewer 正在請求使用本機的 USB 裝置。只在你認得這個請求時允許。",
    "usb_prompt_vendor": "Vendor ID:",
    "usb_prompt_product": "Product ID:",
    "usb_prompt_serial": "序號:",
    "usb_prompt_viewer": "Viewer ID:",
    "usb_prompt_remember": "記住這個決定（寫入永久 ACL 規則）",
    "usb_prompt_allow": "允許",
    "usb_prompt_deny": "拒絕",
    "tab_usb_browser": "USB 瀏覽器",

    # USB 瀏覽器（viewer 端）
    "usb_browser_target_group": "遠端主機",
    "usb_browser_url": "REST URL:",
    "usb_browser_token": "Bearer 權杖:",
    "usb_browser_fetch": "取得裝置",
    "usb_browser_open": "開啟選取項",
    "usb_browser_fetching": "取得中…",
    "usb_browser_fetched": "已取得 {count} 個裝置。",
    "usb_browser_fetch_failed": "取得失敗：{error}",
    "usb_browser_col_vid": "VID",
    "usb_browser_col_pid": "PID",
    "usb_browser_col_manufacturer": "製造商",
    "usb_browser_col_product": "產品",
    "usb_browser_col_serial": "序號",
    "usb_browser_open_select_first": "請先選取一列。",
    "usb_browser_open_unwired": "Open 需要 WebRTC usb DataChannel；本版尚未串接。",

    # 封包監測分頁
    "inspector_metrics_group": "彙整指標",
    "inspector_summary_text": "{count} 筆樣本 / 視窗 {window:.1f} 秒",
    "inspector_metric_rtt_ms": "RTT (ms)",
    "inspector_metric_fps": "每秒影格",
    "inspector_metric_bitrate_kbps": "位元率 (kbps)",
    "inspector_metric_packet_loss_pct": "封包遺失 (%)",
    "inspector_metric_jitter_ms": "抖動 (ms)",
    "inspector_refresh": "重新整理",
    "inspector_reset": "重設",
    "inspector_col_age": "經過",

    # 稽核紀錄分頁
    "audit_filter_group": "篩選",
    "audit_filter_type": "事件類型:",
    "audit_filter_host": "主機 ID:",
    "audit_filter_limit": "筆數:",
    "audit_refresh": "重新整理",
    "audit_verify": "驗證雜湊鏈",
    "audit_clear": "清空紀錄",
    "audit_clear_confirm": "確定清空所有稽核紀錄？此動作無法復原。",
    "audit_clear_done": "已刪除 {count} 筆稽核紀錄。",
    "audit_verify_ok": "雜湊鏈正常 ({total} 筆)。",
    "audit_verify_broken": "雜湊鏈於 ID {row_id} 中斷 (共 {total} 筆)。",
    "audit_col_ts": "時間",
    "audit_col_type": "事件",
    "audit_col_host": "主機 ID",
    "audit_col_viewer": "檢視端 ID",
    "audit_col_detail": "詳情",

    # 管理主控台分頁
    "admin_add_group": "註冊主機",
    "admin_add": "新增",
    "admin_remove": "移除所選",
    "admin_refresh": "全部輪詢",
    "admin_label": "標籤:",
    "admin_url": "基底 URL:",
    "admin_token": "權杖:",
    "admin_broadcast_group": "廣播",
    "admin_actions_label": "動作 JSON (送至所有主機):",
    "admin_broadcast_run": "對所有主機執行",
    "admin_results_label": "各主機結果:",
    "admin_col_label": "標籤",
    "admin_col_url": "URL",
    "admin_col_health": "健康",
    "admin_col_latency": "延遲",
    "admin_col_jobs": "工作",
    "admin_health_ok": "正常",
    "admin_health_down": "離線",

    # REST API 分頁
    "rest_config_group": "REST API 設定",
    "rest_status_group": "REST API 狀態",
    "rest_host": "主機:",
    "rest_port": "連接埠:",
    "rest_token": "權杖:",
    "rest_token_ph": "留白可自動產生",
    "rest_enable_audit": "寫入稽核紀錄",
    "rest_start": "啟動",
    "rest_stop": "停止",
    "rest_copy_url": "複製 URL",
    "rest_copy_token": "複製權杖",
    "rest_url": "URL:",
    "rest_active_token": "Bearer 權杖:",
    "rest_running": "REST API 執行中。",
    "rest_stopped": "REST API 已停止。",
    "rest_config_export": "匯出設定",
    "rest_config_import": "匯入設定",
    "rest_config_export_done": "已將 {count} 個檔案寫入 {path}。",
    "rest_config_import_confirm": "用此設定包覆寫使用者設定？既有檔案會先被改名為 .bak.<時間戳>。",
    "rest_config_import_done": "已寫入 {written} 個檔案；略過 {skipped} 個。",

    # Remote Desktop — WebRTC 子分頁
    "rd_webrtc_host_tab": "WebRTC 被遠端",
    "rd_webrtc_viewer_tab": "WebRTC 遠端他人",
    "rd_webrtc_config_group": "WebRTC 設定",
    "rd_webrtc_monitor_label": "螢幕編號：",
    "rd_webrtc_generate_offer": "產生 offer",
    "rd_webrtc_offer_label": "Offer SDP（傳給對方 viewer）：",
    "rd_webrtc_answer_input_label": "貼上 viewer 的 answer SDP：",
    "rd_webrtc_paste_answer": "把 answer SDP 貼到這裡",
    "rd_webrtc_apply_answer": "套用 answer",
    "rd_webrtc_stop_host": "停止 host",
    "rd_webrtc_offer_input_label": "貼上 host 的 offer SDP：",
    "rd_webrtc_paste_offer": "把 offer SDP 貼到這裡",
    "rd_webrtc_create_answer": "產生 answer",
    "rd_webrtc_stop_viewer": "停止 viewer",
    "rd_webrtc_answer_label": "Answer SDP（傳給對方 host）：",
    "rd_webrtc_status_idle": "閒置",
    "rd_webrtc_state_label": "狀態：",
    "rd_webrtc_generating_offer": "產生 offer 中...",
    "rd_webrtc_offer_ready": "Offer 已產生 — 複製傳給 viewer",
    "rd_webrtc_creating_answer": "產生 answer 中...",
    "rd_webrtc_answer_ready": "Answer 已產生 — 複製傳給 host",
    "rd_webrtc_answer_applied": "Answer 已套用，等待 viewer 認證",
    "rd_webrtc_auth_ok": "已認證",
    "rd_webrtc_auth_fail": "認證失敗",
    "rd_webrtc_token_required": "請先輸入 token",
    "rd_webrtc_no_offer_yet": "請先產生 offer",
    "rd_webrtc_no_answer": "請先貼上 viewer 的 answer SDP",
    "rd_webrtc_no_offer": "請先貼上 host 的 offer SDP",
    "rd_webrtc_unavailable": (
        "WebRTC 模組未安裝 — 請執行 pip install je_auto_control[webrtc]"
    ),
    "rd_webrtc_signaling_group": "用 signaling server 連線（建議）",
    "rd_webrtc_manual_group": "手動 SDP 貼上（備援）",
    "rd_webrtc_advanced_group": "進階（STUN / TURN）",
    "rd_webrtc_server_label": "Server URL：",
    "rd_webrtc_host_id_label": "Host ID：",
    "rd_webrtc_host_id_placeholder": "對方 host 顯示的 8 字元 ID",
    "rd_webrtc_secret_label": "Server 密鑰：",
    "rd_webrtc_regen_id": "新 ID",
    "rd_webrtc_publish_via_server": "發布 host 並等 viewer 連線",
    "rd_webrtc_connect_via_server": "連線到 host",
    "rd_webrtc_stun_label": "STUN URL：",
    "rd_webrtc_turn_label": "TURN URL：",
    "rd_webrtc_turn_placeholder": "turn:turn.example.com:3478（選填）",
    "rd_webrtc_turn_user_label": "TURN 使用者：",
    "rd_webrtc_turn_cred_label": "TURN 密鑰：",
    "rd_webrtc_publishing_offer": "已發布 offer，等待 viewer 回應...",
    "rd_webrtc_polling_offer": "向 signaling server 詢問 host 的 offer...",
    "rd_webrtc_pushing_answer": "把 answer 送到 signaling server...",
    "rd_webrtc_waiting_auth": "Answer 已送出，等待 host 接受",
    "rd_webrtc_pending_viewer_prompt": (
        "有人帶著正確 token 連進來。"
        "確定讓對方控制這台機器嗎？"
    ),
    "rd_webrtc_server_required": "請填 signaling server URL",
    "rd_webrtc_host_id_required": "請填 Host ID",
    # 信任清單 / 接受對話框
    "rd_webrtc_trusted_group": "受信任的 viewer（自動接受）",
    "rd_webrtc_remove_trusted": "移除所選",
    "rd_webrtc_clear_trusted": "全部清除",
    "rd_webrtc_clear_trust_confirm": "確定移除所有受信任 viewer？",
    "rd_webrtc_pending_viewer_title": "新進連線",
    "rd_webrtc_reject": "拒絕",
    "rd_webrtc_accept_once": "本次接受",
    "rd_webrtc_accept_and_trust": "接受並信任",
    # 通訊錄
    "rd_webrtc_address_book_group": "已儲存的 host",
    "rd_webrtc_connect_selected": "連線",
    "rd_webrtc_save_current": "儲存目前",
    "rd_webrtc_remove_selected": "移除",
    "rd_webrtc_no_address_selected": "請先選擇一筆 host",
    "rd_webrtc_save_address_missing_fields": "需要 Server URL 與 Host ID 才能儲存",
    # 細節
    "rd_webrtc_show_cursor": "在串流中顯示游標",
    "rd_webrtc_blank_screen": "Session 期間遮蔽本機螢幕",
    "rd_webrtc_blanking_banner": "本機畫面正被遠端觀看",
    "rd_webrtc_send_cad": "送出 Ctrl+Alt+Del",
    "rd_webrtc_cad_not_connected": "請先連線後再送 Ctrl+Alt+Del",
    # (A) batch
    "rd_webrtc_read_only": "唯讀模式（忽略 viewer 輸入）",
    "rd_webrtc_bandwidth_label": "頻寬：",
    "rd_webrtc_wake_on_lan": "Wake on LAN",
    "rd_webrtc_wol_mac_prompt": "目標 MAC（AA:BB:CC:DD:EE:FF）：",
    "rd_webrtc_wol_broadcast_prompt": "廣播位址：",
    "rd_webrtc_wol_sent": "Magic packet 已送出",
    "rd_webrtc_start_recording": "錄製 session",
    "rd_webrtc_stop_recording": "停止錄製",
    "rd_webrtc_recording_save_as": "錄製存檔為",
    "rd_webrtc_recording_saved": "錄製已儲存：{path}",
    "rd_webrtc_stats_idle": "（尚無統計資料）",
    # (B) batch
    "rd_webrtc_hw_codec_label": "硬體編碼器：",
    "rd_webrtc_hw_codec_off": "關閉（用 libx264）",
    "rd_webrtc_hw_codec_off_status": "硬體編碼已關閉（使用 libx264）",
    "rd_webrtc_hw_codec_active": "硬體編碼啟用中：{codec}",
    "rd_webrtc_hw_codec_failed": "硬體編碼器 {codec} 無法使用",
    "rd_webrtc_adaptive": "依網路自動調 FPS",
    "rd_webrtc_sessions_count": "已連線 viewer：{n}",
    "rd_webrtc_send_mic": "送麥克風",
    "rd_webrtc_recv_mic": "接收 viewer 麥克風（在本機播放）",
    "rd_webrtc_send_file": "送檔案...",
    "rd_webrtc_file_sent": "已送出：{name}",
    "rd_webrtc_push_file": "推送檔案到 viewer...",
    "rd_webrtc_no_viewers": "目前沒有 viewer 連線可推送",
    "rd_webrtc_push_done": "已把 {name} 推送給 {n} 個 viewer",
    "rd_webrtc_file_received": "已收到：{name}",
    # 遠端檔案瀏覽
    "rd_webrtc_remote_files_group": "Host 的 inbox 檔案",
    "rd_webrtc_browse_refresh": "重新整理",
    "rd_webrtc_browse_pull": "下載",
    "rd_webrtc_browse_delete": "刪除",
    "rd_webrtc_browse_col_name": "檔名",
    "rd_webrtc_browse_col_size": "大小 (bytes)",
    "rd_webrtc_browse_col_mtime": "修改時間",
    "rd_webrtc_browse_delete_confirm": "確定要從 host inbox 刪除 '{name}' 嗎？",
    "rd_webrtc_browse_op_ok": "{name} 完成",
    "rd_webrtc_browse_op_failed": "{name} 失敗：{error}",
    "rd_webrtc_browse_dnd_hint": "把檔案拖進來即上傳到 host 的 inbox。",
    "rd_webrtc_browse_copy_name": "複製檔名",
    "rd_webrtc_browse_delete_many_confirm": "確定要從 host inbox 刪除 {n} 個檔案嗎？",
    "rd_webrtc_upload_done": "已上傳 {n} 個檔案",
    # 反向螢幕分享
    "rd_webrtc_accept_viewer_video": "接收 viewer 的螢幕分享",
    "rd_webrtc_share_my_screen": "把我的螢幕分享給 host",
    "rd_webrtc_viewer_screen_title": "Viewer 的螢幕",
    "rd_webrtc_accept_opus_audio": "接收 viewer 的 Opus 音訊",
    "rd_webrtc_share_opus_mic": "用 Opus 把我的麥克風送到 host",
    # KnownHosts 對話框
    "rd_webrtc_manage_known_hosts": "已知 host...",
    "rd_webrtc_known_hosts_title": "已知 host",
    "rd_webrtc_kh_col_host": "Host ID",
    "rd_webrtc_kh_col_app_fp": "App fingerprint",
    "rd_webrtc_kh_col_dtls_fp": "DTLS fingerprint",
    "rd_webrtc_kh_forget": "忘記所選",
    "rd_webrtc_kh_clear_all": "全部清除",
    "rd_webrtc_kh_close": "關閉",
    "rd_webrtc_kh_clear_confirm": "確定忘掉所有已知 host？",
    "rd_webrtc_kh_copy_app": "複製 app fp",
    "rd_webrtc_kh_copy_dtls": "複製 DTLS fp",
    "rd_webrtc_kh_add": "手動加入",
    "rd_webrtc_kh_add_host_ph": "host_id（例如 abcd1234）",
    "rd_webrtc_kh_add_app_ph": "app fingerprint（64 個 hex；選填）",
    "rd_webrtc_kh_add_dtls_ph": "DTLS fingerprint（AB:CD:...；選填）",
    "rd_webrtc_auto_reconnect": "斷線自動重連",
    "rd_webrtc_reconnecting": "重連中（第 {n}/{max} 次）...",
    "rd_webrtc_reconnect_giveup": "重連次數用完",
    "rd_webrtc_reconnect_max": "最大次數：",
    "rd_webrtc_reconnect_delay": "起始延遲：",
    "rd_webrtc_kh_import": "匯入...",
    "rd_webrtc_kh_export": "匯出...",
    "rd_webrtc_kh_import_bad": "匯入的檔案不是 known-hosts JSON",
    "rd_webrtc_kh_import_overwrite": "'{host}' 已存在，要覆寫嗎？",
    "rd_webrtc_kh_import_done": "匯入 {added}，略過 {skipped}",
    "rd_webrtc_quality_unknown": "尚無連線品質資料",
    "rd_webrtc_quality_good": "良好（RTT < 80ms，封包遺失 < 1%）",
    "rd_webrtc_quality_fair": "尚可（RTT < 200ms，封包遺失 < 5%）",
    "rd_webrtc_quality_poor": "不佳（RTT 高或封包遺失多）",
    "rd_webrtc_kh_col_last_seen": "最近連線",
    "rd_webrtc_sess_col_id": "Session",
    "rd_webrtc_sess_col_viewer": "Viewer ID",
    "rd_webrtc_sess_col_state": "狀態",
    "rd_webrtc_sess_col_connected": "連線時間",
    "rd_webrtc_disconnect_selected": "中斷所選 session",
    "rd_webrtc_kh_stale_tip": "超過 90 天未連線，建議重新驗證",
    "rd_webrtc_kh_forget_stale": "清掉所有過期",
    "rd_webrtc_kh_forget_stale_confirm": "確定清掉 {n} 個過期 entry？",
    "rd_webrtc_kh_no_stale": "沒有過期 entry 需要清掉",
    "rd_webrtc_sess_trust_viewer": "信任這個 viewer",
    "rd_webrtc_sess_copy_id": "複製 session id",
    "rd_webrtc_favorite": "加入收藏 ★",
    "rd_webrtc_unfavorite": "移除收藏",
    "rd_webrtc_trust_import": "匯入...",
    "rd_webrtc_trust_export": "匯出...",
    "rd_webrtc_trust_import_done": "匯入 {n} 個信任 viewer",
    "rd_webrtc_my_fingerprint": "本機 fingerprint：",
    "rd_webrtc_copy_fingerprint": "複製",
    "rd_webrtc_ab_export": "匯出通訊錄...",
    "rd_webrtc_ab_import": "匯入通訊錄...",
    "rd_webrtc_ab_clear": "全部清空",
    "rd_webrtc_ab_clear_confirm": "確定清空整個通訊錄？",
    "rd_webrtc_ab_import_done": "匯入 {n} 個 entry",
    "rd_webrtc_tray_idle": "AutoControl host：閒置",
    "rd_webrtc_tray_running": "AutoControl host：{n} 個 viewer",
    "rd_webrtc_tray_open": "開啟視窗",
    "rd_webrtc_tray_stop": "停止 host",
    "rd_webrtc_tray_quit": "退出",
    "rd_webrtc_region_label": "區域 (x,y,w,h)：",
    "rd_webrtc_region_placeholder": "留空代表整螢幕",
    "rd_webrtc_pick_region": "框選區域...",
    "rd_webrtc_monitor_all": "全部螢幕",
    "rd_webrtc_max_bitrate": "最大頻寬：",
    "rd_webrtc_ip_whitelist": "自動接受 IP CIDR：",
    "rd_webrtc_ip_whitelist_ph": "每行一個 CIDR，例如 192.168.1.0/24",
    "rd_webrtc_tag_filter": "標籤：",
    "rd_webrtc_tag_all": "全部",
    "rd_webrtc_edit_tags": "編輯標籤...",
    "rd_webrtc_tags_prompt": "用逗號分隔的標籤：",
    "rd_webrtc_view_audit": "Audit log...",
    "rd_webrtc_audit_title": "Audit log",
    "rd_webrtc_audit_filter_type": "事件類型：",
    "rd_webrtc_audit_filter_type_ph": "auth_ok / auth_fail / file_received / ...",
    "rd_webrtc_audit_filter_host": "Host：",
    "rd_webrtc_audit_refresh": "重新整理",
    "rd_webrtc_audit_col_ts": "時間戳",
    "rd_webrtc_audit_col_type": "事件",
    "rd_webrtc_audit_col_host": "Host",
    "rd_webrtc_audit_col_viewer": "Viewer",
    "rd_webrtc_audit_col_detail": "細節",
    "rd_webrtc_lan_browse": "LAN...",
    "rd_webrtc_lan_title": "LAN 探索",
    "rd_webrtc_lan_help": "Host 透過 mDNS 廣播 _autocontrol._tcp。",
    "rd_webrtc_lan_col_host": "Host ID",
    "rd_webrtc_lan_col_ip": "IP",
    "rd_webrtc_lan_col_signaling": "Signaling URL",
    "rd_webrtc_lan_col_name": "mDNS 名稱",
    "rd_webrtc_lan_use": "使用此筆",
    "rd_webrtc_host_voice": "把我的聲音送出（host → viewers）",
    "rd_webrtc_pen_off": "畫筆 關",
    "rd_webrtc_pen_on": "畫筆 開",
    "rd_webrtc_pen_clear": "清除畫筆",
    "rd_webrtc_sync_group": "資料夾同步",
    "rd_webrtc_sync_dir": "本機資料夾：",
    "rd_webrtc_sync_dir_ph": "要鏡像到 host inbox 的目錄",
    "rd_webrtc_sync_start": "開始同步",
    "rd_webrtc_sync_stop": "停止同步",
    "rd_webrtc_sync_dir_required": "請先選一個本機資料夾",
    "rd_webrtc_browse": "瀏覽...",

    # Auto Click Tab
    "interval_time": "間隔時間 (ms)：",
    "cursor_x": "游標 X：",
    "cursor_y": "游標 Y：",
    "mouse_button": "滑鼠按鍵：",
    "keyboard_button": "鍵盤按鍵：",
    "click_type": "點擊類型：",
    "single_click": "單擊",
    "double_click": "雙擊",
    "input_method": "輸入方式：",
    "mouse_radio": "滑鼠",
    "keyboard_radio": "鍵盤",
    "repeat_until_stopped_radio": "重複直到停止",
    "repeat_radio": "重複",
    "times": "次數",
    "start": "開始",
    "stop": "停止",
    "hotkey_label": "組合鍵（逗號分隔）：",
    "hotkey_send": "送出組合鍵",
    "write_label": "輸入文字：",
    "write_send": "輸入",
    "mouse_scroll_label": "滾動值：",
    "scroll_direction_label": "滾動方向：",
    "scroll_send": "滾動",
    "get_position": "取得滑鼠位置",
    "current_position": "目前位置：",

    # Screenshot Tab
    "take_screenshot": "截取螢幕",
    "save_screenshot": "儲存截圖",
    "file_path_label": "檔案路徑：",
    "browse": "瀏覽",
    "region_label": "區域 (x1, y1, x2, y2)：",
    "pick_region": "框選區域",
    "crop_template": "框選模板",
    "get_pixel_label": "取得像素顏色",
    "pixel_x": "X：",
    "pixel_y": "Y：",
    "pixel_result": "像素顏色：",
    "screen_size_label": "螢幕大小：",
    "get_screen_size": "取得螢幕大小",

    # Image Detection Tab
    "template_image": "模板影像：",
    "threshold_label": "精確度 (0.0~1.0)：",
    "locate_image": "尋找影像",
    "locate_all": "尋找全部",
    "locate_click": "尋找並點擊",
    "detection_result": "偵測結果：",
    "draw_image_check": "標記偵測結果",

    # Record / Playback Tab
    "start_record": "開始錄製",
    "stop_record": "停止錄製",
    "playback": "回放",
    "save_record": "儲存為 JSON",
    "load_record": "載入 JSON",
    "record_status": "狀態：",
    "record_idle": "閒置",
    "record_recording": "錄製中...",
    "record_list_label": "已錄製動作：",

    # Script Executor Tab
    "load_script": "載入腳本 (JSON)",
    "execute_script": "執行",
    "execute_dir_label": "執行目錄：",
    "execute_dir": "執行全部",
    "script_content": "腳本內容：",
    "execution_result": "執行結果：",

    # Screen Recording Tab
    "recorder_name": "錄影器名稱：",
    "output_file": "輸出檔案：",
    "codec_label": "編碼器：",
    "fps_label": "FPS：",
    "resolution_label": "解析度 (寬x高)：",
    "start_screen_record": "開始錄影",
    "stop_screen_record": "停止錄影",
    "screen_record_status": "狀態：",

    # Shell Tab
    "shell_command_label": "Shell 命令：",
    "execute_shell": "執行",
    "shell_output": "輸出：",
    "start_exe_label": "可執行檔路徑：",
    "start_exe": "啟動可執行檔",

    # Report Tab
    "report_name": "報告名稱：",
    "generate_html_report": "產生 HTML 報告",
    "generate_json_report": "產生 JSON 報告",
    "generate_xml_report": "產生 XML 報告",
    "enable_test_record": "啟用測試紀錄",
    "disable_test_record": "停用測試紀錄",
    "test_record_status": "測試紀錄：",
    "report_result": "結果：",

    # Language
    "language_label": "語言：",

    # Hotkeys Tab
    "hk_combo_label": "組合鍵：",
    "hk_script_label": "腳本：",
    "hk_bind": "綁定",
    "hk_remove_selected": "移除所選",
    "hk_start_daemon": "啟動服務",
    "hk_stop_daemon": "停止服務",
    "hk_daemon_stopped": "服務已停止",
    "hk_daemon_running": "服務運行中",
    "hk_col_id": "ID",
    "hk_col_combo": "組合鍵",
    "hk_col_script": "腳本",
    "hk_col_fired": "已觸發",
    "hk_dialog_select_script": "選擇腳本",

    # Triggers Tab
    "tr_script_label": "腳本：",
    "tr_type_label": "類型：",
    "tr_repeat": "重複",
    "tr_add": "新增觸發器",
    "tr_remove_selected": "移除所選",
    "tr_start_engine": "啟動引擎",
    "tr_stop_engine": "停止引擎",
    "tr_engine_stopped": "引擎已停止",
    "tr_engine_running": "引擎運行中",
    "tr_type_image": "影像出現",
    "tr_type_window": "視窗出現",
    "tr_type_pixel": "像素符合",
    "tr_type_file": "檔案變更",
    "tr_image_label": "影像：",
    "tr_threshold_label": "精確度：",
    "tr_title_contains_label": "標題包含：",
    "tr_watch_label": "監看路徑：",
    "tr_col_id": "ID",
    "tr_col_type": "類型",
    "tr_col_detail": "細節",
    "tr_col_fired": "已觸發",
    "tr_col_enabled": "啟用",
    "tr_yes": "是",
    "tr_no": "否",
    "tr_dialog_select_script": "選擇腳本",
    "tr_dialog_select_image": "選擇影像",
    "tr_dialog_select_file": "選擇要監看的檔案",

    # Plugins Tab
    "pl_dir_label": "外掛目錄：",
    "pl_load": "載入並註冊",
    "pl_no_loaded": "尚未載入外掛",
    "pl_registered_label": "已註冊指令：",
    "pl_dialog_plugin_dir": "外掛目錄",

    # Scheduler Tab
    "sch_script_label": "腳本：",
    "sch_interval_label": "每 (秒)：",
    "sch_repeat": "重複",
    "sch_add": "新增",
    "sch_remove_selected": "移除所選",
    "sch_start": "啟動排程器",
    "sch_stop": "停止排程器",
    "sch_status_running": "排程器運行中",
    "sch_status_stopped": "排程器已停止",
    "sch_col_job_id": "任務 ID",
    "sch_col_script": "腳本",
    "sch_col_interval": "間隔 (秒)",
    "sch_col_runs": "執行次數",
    "sch_col_enabled": "啟用",
    "sch_dialog_select_script": "選擇腳本",

    # Socket / REST Tab
    "ss_tcp_group": "TCP Socket 伺服器",
    "ss_rest_group": "REST API 伺服器",
    "ss_host_label": "主機：",
    "ss_port_label": "埠號：",
    "ss_tcp_any_check": "綁定 TCP 至 0.0.0.0（暴露於網路）",
    "ss_rest_any_check": "綁定 REST 至 0.0.0.0（暴露於網路）",
    "ss_tcp_stopped": "TCP 已停止",
    "ss_rest_stopped": "REST 已停止",
    "ss_tcp_start": "啟動 TCP",
    "ss_tcp_stop": "停止 TCP",
    "ss_rest_start": "啟動 REST",
    "ss_rest_stop": "停止 REST",

    # Live HUD Tab
    "hud_watchers_group": "監看器",
    "hud_start": "啟動 HUD",
    "hud_stop": "停止 HUD",
    "hud_clear": "清除日誌",
    "hud_recent_log": "最近日誌：",
    "hud_mouse_prefix": "滑鼠：",
    "hud_pixel_prefix": "像素：",

    # Window Manager Tab
    "win_refresh": "重新整理",
    "win_filter_placeholder": "以標題子字串過濾",
    "win_col_hwnd": "HWND",
    "win_col_title": "標題",
    "win_focus_selected": "聚焦所選",
    "win_close_selected": "關閉所選",
    "win_status_count": "{n} 個視窗",

    # Recording Editor Tab
    "re_file_label": "檔案：",
    "re_browse": "瀏覽",
    "re_load": "載入",
    "re_save_as": "另存為",
    "re_trim_start": "裁剪起點：",
    "re_trim_end": "終點：",
    "re_apply_trim": "套用裁剪",
    "re_remove_selected": "移除所選",
    "re_delay_x": "延遲倍數",
    "re_floor_ms": "下限 ms：",
    "re_apply_delays": "套用延遲",
    "re_scale_x": "縮放 x：",
    "re_scale_y": "y：",
    "re_apply_scale": "套用縮放",
    "re_keep_mouse": "僅保留滑鼠",
    "re_keep_keyboard": "僅保留鍵盤",
    "re_preview": "預覽：",
    "re_dialog_open": "開啟錄製",
    "re_dialog_save": "儲存錄製",

    # Script Builder Tab
    "sb_delete": "刪除",
    "sb_up": "上移",
    "sb_down": "下移",
    "sb_load_json": "載入 JSON",
    "sb_save_json": "儲存 JSON",
    "sb_run": "執行",
    "sb_add_step": "新增步驟",
    "sb_dialog_save": "儲存腳本",
    "sb_dialog_load": "載入腳本",
    "sb_no_step_selected": "尚未選取步驟",

    # Run History Tab
    "rh_filter_label": "來源：",
    "rh_source_all": "全部",
    "rh_source_scheduler": "排程器",
    "rh_source_trigger": "觸發器",
    "rh_source_hotkey": "熱鍵",
    "rh_source_manual": "手動",
    "rh_source_rest": "REST",
    "rh_refresh": "重新整理",
    "rh_clear": "清除",
    "rh_confirm_clear": "要刪除全部執行紀錄嗎？此動作無法復原。",
    "rh_count_label": "{n} 筆紀錄",
    "rh_col_id": "ID",
    "rh_col_source": "來源",
    "rh_col_target": "目標",
    "rh_col_script": "腳本",
    "rh_col_started": "開始時間",
    "rh_col_duration": "耗時",
    "rh_col_status": "狀態",
    "rh_status_ok": "成功",
    "rh_status_error": "錯誤",
    "rh_status_running": "執行中",
    "rh_col_artifact": "截圖",
    "rh_open_artifact": "開啟截圖",
    "rh_no_artifact": "所選紀錄沒有截圖。",
    "rh_artifact_missing": "截圖檔案已不存在。",

    # Accessibility Tab
    "a11y_app_label": "應用程式：",
    "a11y_app_placeholder": "例如：小算盤",
    "a11y_name_label": "名稱包含：",
    "a11y_name_placeholder": "部分比對",
    "a11y_refresh": "重新整理",
    "a11y_click_selected": "點擊所選",
    "a11y_col_app": "應用程式",
    "a11y_col_role": "角色",
    "a11y_col_name": "名稱",
    "a11y_col_bounds": "邊界",
    "a11y_col_center": "中心",
    "a11y_count_label": "{n} 個元素",
    "a11y_no_selection": "請先選擇一列",
    "a11y_click_not_found": "找不到可點擊的元素",

    # VLM (AI Locator) Tab
    "vlm_desc_label": "描述：",
    "vlm_desc_placeholder": "例如：綠色的送出按鈕",
    "vlm_model_label": "模型：",
    "vlm_model_placeholder": "選填（例如 claude-opus-4-7）",
    "vlm_locate": "定位",
    "vlm_click": "定位並點擊",
    "vlm_result": "位置：({x}, {y})",
    "vlm_ok": "完成",
    "vlm_not_found": "找不到符合的元素",
    "vlm_error": "錯誤",
    "vlm_desc_required": "請先輸入目標描述",

    # OCR Reader Tab
    "ocr_region_group": "區域",
    "ocr_region_label": "x, y, w, h：",
    "ocr_region_placeholder": "留空代表整個螢幕",
    "ocr_pick_region": "選取區域...",
    "ocr_lang_label": "語言：",
    "ocr_min_conf_label": "最低信心度：",
    "ocr_regex_label": "Regex 樣式：",
    "ocr_regex_placeholder": r"例如 Order#\d+",
    "ocr_dump_region": "抓取區域全部文字",
    "ocr_find_regex": "用 regex 搜尋",
    "ocr_results_label": "結果：",
    "ocr_match_count": "{n} 個結果",
    "ocr_region_invalid": "區域必須為 4 個逗號分隔整數",
    "ocr_min_conf_invalid": "信心度需為數字",
    "ocr_regex_required": "請先輸入 regex 樣式",
    "ocr_regex_invalid": "Regex 不正確",

    # Variables Tab
    "vars_current_group": "目前作用域",
    "vars_col_name": "名稱",
    "vars_col_value": "值",
    "vars_count": "共 {n} 個變數",
    "vars_refresh": "重新整理",
    "vars_clear": "全部清除",
    "vars_clear_confirm": "確定要清空所有執行期變數嗎？",
    "vars_set_group": "新增單一變數",
    "vars_name_label": "名稱：",
    "vars_name_placeholder": "變數名稱",
    "vars_name_required": "請輸入名稱",
    "vars_value_label": "值：",
    "vars_value_placeholder": "JSON 字面值（42、\"text\"、[1,2]）或純字串",
    "vars_set_btn": "設定",
    "vars_seed_group": "從 JSON 載入",
    "vars_seed_placeholder": "{\"counter\": 0, \"items\": [\"a\", \"b\"]}",
    "vars_seed_btn": "合併 JSON 到作用域",
    "vars_seed_required": "請先貼上 JSON 物件",
    "vars_seed_invalid": "JSON 格式錯誤",
    "vars_seed_not_object": "JSON 必須是物件",

    # LLM Planner Tab
    "llm_desc_group": "描述要做的任務",
    "llm_desc_placeholder": (
        "例如：開啟記事本、輸入 'hello world'、另存為 test.txt"
    ),
    "llm_model_label": "模型：",
    "llm_model_placeholder": "選填（例如 claude-opus-4-7）",
    "llm_plan_btn": "規劃",
    "llm_run_btn": "執行此規劃",
    "llm_plan_group": "已規劃的指令",
    "llm_result_group": "執行結果",
    "llm_desc_required": "請先描述要自動化的任務",
    "llm_planning": "規劃中...",
    "llm_plan_count": "已規劃 {n} 個指令",
    "llm_no_plan": "請先按下「規劃」",
    "llm_running": "執行中...",
    "llm_run_done": "完成",

    # Remote Desktop Tab
    "rd_host_tab": "被遠端（本機）",
    "rd_viewer_tab": "遠端他人（控制他機）",
    "rd_host_security_warning": (
        "警告：取得本機 host:port 與 token 的人，可以完全控制本機的滑鼠／鍵盤。"
        "預設只綁 127.0.0.1；要對外請透過 SSH tunnel 或可信的 VPN。"
    ),
    "rd_host_config_group": "Host 設定",
    "rd_viewer_config_group": "連線到遠端 Host",
    "rd_token_label": "Token：",
    "rd_token_placeholder": "共用密鑰（HMAC key）",
    "rd_token_generate": "產生",
    "rd_bind_label": "位址：",
    "rd_port_label": "Port：",
    "rd_fps_label": "FPS：",
    "rd_quality_label": "JPEG 品質：",
    "rd_host_start": "啟動 Host",
    "rd_host_stop": "停止 Host",
    "rd_host_status_running": "運行中 port {port} — {n} 個 viewer",
    "rd_host_status_stopped": "Host 已停止",
    "rd_host_preview_label": "預覽（viewer 看到的畫面）：",
    "rd_host_card_group": "連線",
    "rd_viewer_card_group": "連線到遠端 Host",
    "rd_host_basics_group": "連線設定",
    "rd_advanced_group": "進階",
    "rd_host_copy_share": "複製分享資訊",
    "rd_host_copy_share_unavailable": "請先啟動 Host 才能分享。",
    "rd_host_copy_share_confirm": (
        "複製會把位址、port、Host ID 跟 TOKEN 一起放到剪貼簿。"
        "貼出去的對象等同取得本機完整控制權，確定？"
    ),
    "rd_badge_running": "RUNNING · :{port} · {n} 個 viewer",
    "rd_badge_stopped": "STOPPED",
    "rd_badge_idle": "尚未連線",
    "rd_badge_live": "連線中",
    "rd_host_id_group": "Host ID（給遠端的人）",
    "rd_host_id_label": "Host ID：",
    "rd_host_id_copy": "複製",
    "rd_transport_label": "傳輸協定：",
    "rd_tls_cert_label": "TLS 憑證：",
    "rd_tls_cert_placeholder": "PEM 憑證路徑（選填）",
    "rd_tls_key_label": "TLS 金鑰：",
    "rd_tls_key_placeholder": "PEM 私鑰路徑（選填）",
    "rd_tls_both_required": "TLS 憑證與金鑰必須一併提供",
    "rd_tls_insecure": "忽略憑證驗證（自簽用）",
    "rd_browse": "瀏覽...",
    "rd_enable_audio": "串流系統音訊（sounddevice）",
    "rd_viewer_audio_play": "播放接收的音訊（sounddevice）",
    "rd_viewer_push_clipboard": "把本機剪貼簿文字送到 Host",
    "rd_viewer_send_file": "傳送檔案...",
    "rd_dest_path_prompt": "{name} 在遠端的目的路徑：",
    "rd_clipboard_empty": "本機剪貼簿是空的",
    "rd_clipboard_sent": "剪貼簿已送到 Host",
    "rd_viewer_clipboard_received": "已從 Host 同步剪貼簿",
    "rd_progress_label": "傳輸進度：{done} / {total} bytes",
    "rd_progress_done": "傳輸完成：{path}",
    "rd_progress_failed": "傳輸失敗：{error}",
    "rd_viewer_connect": "連線",
    "rd_viewer_disconnect": "中斷連線",
    "rd_viewer_required_fields": "位址、port、token 都必須填寫。",
    "rd_viewer_status_connected": "已連線 — 正在接收畫面",
    "rd_viewer_status_idle": "尚未連線",
    "rd_viewer_error": "遠端桌面錯誤",

    # Menu bar
    "menu_file": "檔案",
    "menu_file_open_script": "開啟腳本...",
    "menu_file_exit": "結束",
    "menu_view": "檢視",
    "menu_view_tabs": "分頁",
    "menu_view_cat_core": "核心",
    "menu_view_cat_editing": "編輯",
    "menu_view_cat_detection": "偵測與視覺",
    "menu_view_cat_automation": "自動化引擎",
    "menu_view_cat_system": "系統",
    "menu_view_text_size": "文字大小",
    "menu_view_text_auto": "自動（依螢幕）",
    "menu_view_text_small": "小 (10pt)",
    "menu_view_text_normal": "標準 (12pt)",
    "menu_view_text_large": "大 (14pt)",
    "menu_view_text_xlarge": "特大 (16pt)",
    "menu_view_text_xxlarge": "超大 (20pt)",
    "menu_tools": "工具",
    "menu_tools_start_hotkeys": "啟動熱鍵服務",
    "menu_tools_start_scheduler": "啟動排程器",
    "menu_tools_start_triggers": "啟動觸發引擎",
    "menu_language": "語言",
    "menu_help": "說明",
    "menu_help_about": "關於 AutoControlGUI",
}
