traditional_chinese_word_dict = {
    # Main
    "application_name": "AutoControlGUI",

    # Tabs
    "tab_auto_click": "自動點擊",
    "tab_screenshot": "螢幕截圖",
    "tab_image_detect": "影像偵測",
    "tab_record": "錄製 / 回放",
    "tab_script": "腳本執行",
    "tab_script_builder": "腳本編輯器",
    "tab_recording_editor": "錄製後製",
    "tab_window_manager": "視窗管理",
    "tab_scheduler": "排程器",
    "tab_socket_server": "Socket 伺服器",
    "tab_live_hud": "即時監看",
    "tab_hotkeys": "全域熱鍵",
    "tab_triggers": "事件觸發器",
    "tab_plugins": "外掛",
    "tab_screen_record": "螢幕錄影",
    "tab_shell": "Shell 命令",
    "tab_report": "報告產生",
    "tab_run_history": "執行紀錄",
    "tab_accessibility": "無障礙樹",

    # Auto Click Tab
    "interval_time": "間隔時間 (ms)：",
    "cursor_x": "游標 X：",
    "cursor_y": "游標 Y：",
    "mouse_button": "滑鼠按鍵：",
    "keyboard_button": "鍵盤按鍵：",
    "click_type": "點擊類型：",
    "single_click": "單擊",
    "double_click": "雙擊",
    "input_method": "輸入方式：",
    "mouse_radio": "滑鼠",
    "keyboard_radio": "鍵盤",
    "repeat_until_stopped_radio": "重複直到停止",
    "repeat_radio": "重複",
    "times": "次數",
    "start": "開始",
    "stop": "停止",
    "hotkey_label": "組合鍵（逗號分隔）：",
    "hotkey_send": "送出組合鍵",
    "write_label": "輸入文字：",
    "write_send": "輸入",
    "mouse_scroll_label": "滾動值：",
    "scroll_direction_label": "滾動方向：",
    "scroll_send": "滾動",
    "get_position": "取得滑鼠位置",
    "current_position": "目前位置：",

    # Screenshot Tab
    "take_screenshot": "截取螢幕",
    "save_screenshot": "儲存截圖",
    "file_path_label": "檔案路徑：",
    "browse": "瀏覽",
    "region_label": "區域 (x1, y1, x2, y2)：",
    "pick_region": "框選區域",
    "crop_template": "框選模板",
    "get_pixel_label": "取得像素顏色",
    "pixel_x": "X：",
    "pixel_y": "Y：",
    "pixel_result": "像素顏色：",
    "screen_size_label": "螢幕大小：",
    "get_screen_size": "取得螢幕大小",

    # Image Detection Tab
    "template_image": "模板影像：",
    "threshold_label": "精確度 (0.0~1.0)：",
    "locate_image": "尋找影像",
    "locate_all": "尋找全部",
    "locate_click": "尋找並點擊",
    "detection_result": "偵測結果：",
    "draw_image_check": "標記偵測結果",

    # Record / Playback Tab
    "start_record": "開始錄製",
    "stop_record": "停止錄製",
    "playback": "回放",
    "save_record": "儲存為 JSON",
    "load_record": "載入 JSON",
    "record_status": "狀態：",
    "record_idle": "閒置",
    "record_recording": "錄製中...",
    "record_list_label": "已錄製動作：",

    # Script Executor Tab
    "load_script": "載入腳本 (JSON)",
    "execute_script": "執行",
    "execute_dir_label": "執行目錄：",
    "execute_dir": "執行全部",
    "script_content": "腳本內容：",
    "execution_result": "執行結果：",

    # Screen Recording Tab
    "recorder_name": "錄影器名稱：",
    "output_file": "輸出檔案：",
    "codec_label": "編碼器：",
    "fps_label": "FPS：",
    "resolution_label": "解析度 (寬x高)：",
    "start_screen_record": "開始錄影",
    "stop_screen_record": "停止錄影",
    "screen_record_status": "狀態：",

    # Shell Tab
    "shell_command_label": "Shell 命令：",
    "execute_shell": "執行",
    "shell_output": "輸出：",
    "start_exe_label": "可執行檔路徑：",
    "start_exe": "啟動可執行檔",

    # Report Tab
    "report_name": "報告名稱：",
    "generate_html_report": "產生 HTML 報告",
    "generate_json_report": "產生 JSON 報告",
    "generate_xml_report": "產生 XML 報告",
    "enable_test_record": "啟用測試紀錄",
    "disable_test_record": "停用測試紀錄",
    "test_record_status": "測試紀錄：",
    "report_result": "結果：",

    # Language
    "language_label": "語言：",

    # Hotkeys Tab
    "hk_combo_label": "組合鍵：",
    "hk_script_label": "腳本：",
    "hk_bind": "綁定",
    "hk_remove_selected": "移除所選",
    "hk_start_daemon": "啟動服務",
    "hk_stop_daemon": "停止服務",
    "hk_daemon_stopped": "服務已停止",
    "hk_daemon_running": "服務運行中",
    "hk_col_id": "ID",
    "hk_col_combo": "組合鍵",
    "hk_col_script": "腳本",
    "hk_col_fired": "已觸發",
    "hk_dialog_select_script": "選擇腳本",

    # Triggers Tab
    "tr_script_label": "腳本：",
    "tr_type_label": "類型：",
    "tr_repeat": "重複",
    "tr_add": "新增觸發器",
    "tr_remove_selected": "移除所選",
    "tr_start_engine": "啟動引擎",
    "tr_stop_engine": "停止引擎",
    "tr_engine_stopped": "引擎已停止",
    "tr_engine_running": "引擎運行中",
    "tr_type_image": "影像出現",
    "tr_type_window": "視窗出現",
    "tr_type_pixel": "像素符合",
    "tr_type_file": "檔案變更",
    "tr_image_label": "影像：",
    "tr_threshold_label": "精確度：",
    "tr_title_contains_label": "標題包含：",
    "tr_watch_label": "監看路徑：",
    "tr_col_id": "ID",
    "tr_col_type": "類型",
    "tr_col_detail": "細節",
    "tr_col_fired": "已觸發",
    "tr_col_enabled": "啟用",
    "tr_yes": "是",
    "tr_no": "否",
    "tr_dialog_select_script": "選擇腳本",
    "tr_dialog_select_image": "選擇影像",
    "tr_dialog_select_file": "選擇要監看的檔案",

    # Plugins Tab
    "pl_dir_label": "外掛目錄：",
    "pl_load": "載入並註冊",
    "pl_no_loaded": "尚未載入外掛",
    "pl_registered_label": "已註冊指令：",
    "pl_dialog_plugin_dir": "外掛目錄",

    # Scheduler Tab
    "sch_script_label": "腳本：",
    "sch_interval_label": "每 (秒)：",
    "sch_repeat": "重複",
    "sch_add": "新增",
    "sch_remove_selected": "移除所選",
    "sch_start": "啟動排程器",
    "sch_stop": "停止排程器",
    "sch_status_running": "排程器運行中",
    "sch_status_stopped": "排程器已停止",
    "sch_col_job_id": "任務 ID",
    "sch_col_script": "腳本",
    "sch_col_interval": "間隔 (秒)",
    "sch_col_runs": "執行次數",
    "sch_col_enabled": "啟用",
    "sch_dialog_select_script": "選擇腳本",

    # Socket / REST Tab
    "ss_tcp_group": "TCP Socket 伺服器",
    "ss_rest_group": "REST API 伺服器",
    "ss_host_label": "主機：",
    "ss_port_label": "埠號：",
    "ss_tcp_any_check": "綁定 TCP 至 0.0.0.0（暴露於網路）",
    "ss_rest_any_check": "綁定 REST 至 0.0.0.0（暴露於網路）",
    "ss_tcp_stopped": "TCP 已停止",
    "ss_rest_stopped": "REST 已停止",
    "ss_tcp_start": "啟動 TCP",
    "ss_tcp_stop": "停止 TCP",
    "ss_rest_start": "啟動 REST",
    "ss_rest_stop": "停止 REST",

    # Live HUD Tab
    "hud_watchers_group": "監看器",
    "hud_start": "啟動 HUD",
    "hud_stop": "停止 HUD",
    "hud_clear": "清除日誌",
    "hud_recent_log": "最近日誌：",
    "hud_mouse_prefix": "滑鼠：",
    "hud_pixel_prefix": "像素：",

    # Window Manager Tab
    "win_refresh": "重新整理",
    "win_filter_placeholder": "以標題子字串過濾",
    "win_col_hwnd": "HWND",
    "win_col_title": "標題",
    "win_focus_selected": "聚焦所選",
    "win_close_selected": "關閉所選",
    "win_status_count": "{n} 個視窗",

    # Recording Editor Tab
    "re_file_label": "檔案：",
    "re_browse": "瀏覽",
    "re_load": "載入",
    "re_save_as": "另存為",
    "re_trim_start": "裁剪起點：",
    "re_trim_end": "終點：",
    "re_apply_trim": "套用裁剪",
    "re_remove_selected": "移除所選",
    "re_delay_x": "延遲倍數",
    "re_floor_ms": "下限 ms：",
    "re_apply_delays": "套用延遲",
    "re_scale_x": "縮放 x：",
    "re_scale_y": "y：",
    "re_apply_scale": "套用縮放",
    "re_keep_mouse": "僅保留滑鼠",
    "re_keep_keyboard": "僅保留鍵盤",
    "re_preview": "預覽：",
    "re_dialog_open": "開啟錄製",
    "re_dialog_save": "儲存錄製",

    # Script Builder Tab
    "sb_delete": "刪除",
    "sb_up": "上移",
    "sb_down": "下移",
    "sb_load_json": "載入 JSON",
    "sb_save_json": "儲存 JSON",
    "sb_run": "執行",
    "sb_add_step": "新增步驟",
    "sb_dialog_save": "儲存腳本",
    "sb_dialog_load": "載入腳本",
    "sb_no_step_selected": "尚未選取步驟",

    # Run History Tab
    "rh_filter_label": "來源：",
    "rh_source_all": "全部",
    "rh_source_scheduler": "排程器",
    "rh_source_trigger": "觸發器",
    "rh_source_hotkey": "熱鍵",
    "rh_source_manual": "手動",
    "rh_source_rest": "REST",
    "rh_refresh": "重新整理",
    "rh_clear": "清除",
    "rh_confirm_clear": "要刪除全部執行紀錄嗎？此動作無法復原。",
    "rh_count_label": "{n} 筆紀錄",
    "rh_col_id": "ID",
    "rh_col_source": "來源",
    "rh_col_target": "目標",
    "rh_col_script": "腳本",
    "rh_col_started": "開始時間",
    "rh_col_duration": "耗時",
    "rh_col_status": "狀態",
    "rh_status_ok": "成功",
    "rh_status_error": "錯誤",
    "rh_status_running": "執行中",
    "rh_col_artifact": "截圖",
    "rh_open_artifact": "開啟截圖",
    "rh_no_artifact": "所選紀錄沒有截圖。",
    "rh_artifact_missing": "截圖檔案已不存在。",

    # Accessibility Tab
    "a11y_app_label": "應用程式：",
    "a11y_app_placeholder": "例如：小算盤",
    "a11y_name_label": "名稱包含：",
    "a11y_name_placeholder": "部分比對",
    "a11y_refresh": "重新整理",
    "a11y_click_selected": "點擊所選",
    "a11y_col_app": "應用程式",
    "a11y_col_role": "角色",
    "a11y_col_name": "名稱",
    "a11y_col_bounds": "邊界",
    "a11y_col_center": "中心",
    "a11y_count_label": "{n} 個元素",
    "a11y_no_selection": "請先選擇一列",
    "a11y_click_not_found": "找不到可點擊的元素",

    # Menu bar
    "menu_file": "檔案",
    "menu_file_open_script": "開啟腳本...",
    "menu_file_exit": "結束",
    "menu_view": "檢視",
    "menu_view_tabs": "分頁",
    "menu_tools": "工具",
    "menu_tools_start_hotkeys": "啟動熱鍵服務",
    "menu_tools_start_scheduler": "啟動排程器",
    "menu_tools_start_triggers": "啟動觸發引擎",
    "menu_language": "語言",
    "menu_help": "說明",
    "menu_help_about": "關於 AutoControlGUI",
}
