{{- if .Values.rest.enabled -}}
{{- $component := "rest" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "autocontrol.fullname" (merge (dict "component" $component) .) }}
  labels:
    {{- include "autocontrol.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  replicas: {{ .Values.rest.replicas }}
  selector:
    matchLabels:
      {{- include "autocontrol.selectorLabels" (merge (dict "component" $component) .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "autocontrol.selectorLabels" (merge (dict "component" $component) .) | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: rest
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["rest"]
          ports:
            - name: http
              containerPort: {{ .Values.rest.port }}
          env:
            - name: AC_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-auth
                  key: AC_TOKEN
            - name: XVFB_GEOMETRY
              value: {{ .Values.display.geometry | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
