{{- include "autocontrol.requireToken" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-auth
  labels:
    {{- include "autocontrol.labels" . | nindent 4 }}
type: Opaque
stringData:
  AC_TOKEN: {{ .Values.auth.token | quote }}
