# Rename to build stable version
# This is stable version
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "je_auto_control"
version = "0.0.163"
authors = [
    { name = "JE-Chen", email = "jechenmailman@gmail.com" },
]
description = "GUI Automation Framework"
requires-python = ">=3.9"
license-files = ["LICENSE"]
dependencies = [
    "je_open_cv",
    "pillow",
    "Pyside6==6.8.2.1",
    "pyobjc-core;platform_system=='Darwin'",
    "pyobjc;platform_system=='Darwin'",
    "python-Xlib;platform_system=='Linux'",
    "mss"
]
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Win32 (MS Windows)",
    "Environment :: MacOS X",
    "Environment :: X11 Applications",
    "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/Intergration-Automation-Testing/AutoControl"
Documentation = "https://autocontrol.readthedocs.io/en/latest/"
Code = "https://github.com/Intergration-Automation-Testing/AutoControl"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[tool.setuptools.packages]
find = { namespaces = false }

[project.optional-dependencies]
gui = ["Pyside6", "qt-material"]
