"""Generate runnable test code from AutoControl action lists.

Turns a recording or JSON action file into a committable pytest test, a
standalone Python script, or a Robot Framework suite. The default
``calls`` style emits readable ``ac.<function>(...)`` statements (mapping
each ``AC_*`` command to its facade function via the executor registry),
with a safe fall-back to ``ac.execute_action([...])`` for flow-control
commands and private adapters. The ``actions`` style instead embeds the
whole list and replays it through the executor for exact fidelity.

This module imports no ``PySide6`` so codegen works fully headlessly.
"""
import base64
import json
import keyword
import os
import pprint
import re
import textwrap
from typing import Sequence, Tuple

from je_auto_control.utils.json.json_file import read_action_json

_HEADER = "Generated by AutoControl codegen. Edit freely."


def _slug(name: str) -> str:
    """Return a valid lower_snake identifier derived from ``name``."""
    slug = re.sub(r"\W+", "_", name.strip()).strip("_").lower()
    if not slug:
        return "recorded_flow"
    return f"flow_{slug}" if slug[0].isdigit() else slug


def _call_context() -> Tuple[dict, set]:
    """Return ``(event_dict, public_names)`` for mapping commands to calls."""
    import je_auto_control as ac
    from je_auto_control.utils.executor.action_executor import executor
    return executor.event_dict, set(getattr(ac, "__all__", ()))


def _action_to_call(action: Sequence, event_dict: dict, public: set) -> str:
    """Render one action as a Python statement (call or executor fall-back)."""
    name = action[0]
    params = action[1] if len(action) == 2 else None
    func = event_dict.get(name)
    public_name = getattr(func, "__name__", "") if func is not None else ""
    direct = public_name in public
    if direct and (params is None or _keyword_safe(params)):
        if params:
            kwargs = ", ".join(
                f"{key}={value!r}" for key, value in params.items())
            return f"ac.{public_name}({kwargs})"
        return f"ac.{public_name}()"
    return f"ac.execute_action({[list(action)]!r})"


def _keyword_safe(params: object) -> bool:
    """Whether every key can be emitted as ``key=value`` source text.

    The keys come from the action file and went into the generated code
    as written, so a key such as ``x=1)\\nimport os; os.system(...)`` put
    arbitrary statements into the test. Anything else takes the
    ``execute_action([...])`` fall-back, where the key is a string literal.
    """
    return isinstance(params, dict) and all(
        isinstance(key, str) and key.isidentifier() and not keyword.iskeyword(key)
        for key in params)


def _calls_body(actions: Sequence) -> str:
    event_dict, public = _call_context()
    return "\n".join(
        _action_to_call(action, event_dict, public) for action in actions)


def _actions_body(actions: Sequence) -> str:
    literal = pprint.pformat([list(action) for action in actions],
                             indent=4, width=88)
    return f"actions = {literal}\nac.execute_action(actions)"


def _body(actions: Sequence, style: str) -> str:
    if style == "actions":
        return _actions_body(actions)
    if style == "calls":
        return _calls_body(actions)
    raise ValueError(f"unknown codegen style: {style!r}")


def _render_pytest(actions: Sequence, name: str, style: str,
                   failure_bundle: bool = False) -> str:
    raw_body = _body(actions, style)
    if failure_bundle:
        body = ("    with failure_bundle_on_error(\n"
                f"            {(_slug(name) + '-failure.zip')!r},\n"
                f"            context={{'generated_test': {_slug(name)!r}}}):\n"
                + textwrap.indent(raw_body, "        "))
    else:
        body = textwrap.indent(raw_body, "    ")
    # The facade supplies the ac.<function> calls; failure_bundle_on_error
    # lives in je_auto_control.api, which the facade does not re-export --
    # importing api *as ac* made every generated call an AttributeError.
    imports = "import je_auto_control as ac\n"
    if failure_bundle:
        imports += "from je_auto_control.api import failure_bundle_on_error\n"
    return (f'"""{_HEADER}"""\n' + imports + "\n\n"
            + f"def test_{_slug(name)}():\n{body}\n")


def _render_python(actions: Sequence, name: str, style: str,
                   _failure_bundle: bool = False) -> str:
    slug = _slug(name)
    body = textwrap.indent(_body(actions, style), "    ")
    return (f'"""{_HEADER}"""\n'
            "import je_auto_control as ac\n\n\n"
            f"def {slug}():\n{body}\n\n\n"
            'if __name__ == "__main__":\n'
            f"    {slug}()\n")


def _render_robot(actions: Sequence, name: str, _style: str,
                  _failure_bundle: bool = False) -> str:
    # Base64, not a raw-string literal: ''' in any value closed the literal
    # and the rest ran as Python inside Evaluate, and Robot itself splits
    # cells on two spaces and substitutes ${...} in the text.
    payload = base64.b64encode(json.dumps(
        [list(action) for action in actions], ensure_ascii=False).encode("utf-8")).decode("ascii")
    test_name = " ".join(name.replace("_", " ").split()).title() or "Recorded Flow"
    return "\n".join([
        "*** Settings ***",
        f"Documentation    {_HEADER}",
        "",
        "*** Test Cases ***",
        test_name,
        f"    ${{actions}}=    Evaluate    json.loads(base64.b64decode('{payload}'))    base64,json",
        "    Evaluate    __import__('je_auto_control').execute_action($actions)",
        "",
    ])


_RENDERERS = {
    "pytest": _render_pytest,
    "python": _render_python,
    "robot": _render_robot,
}


def generate_code(actions: Sequence, target: str = "pytest",
                  name: str = "recorded_flow", style: str = "calls",
                  failure_bundle: bool = False) -> str:
    """Render ``actions`` as source code for ``target`` (pytest/python/robot)."""
    if not isinstance(actions, list) or not actions:
        raise ValueError("actions must be a non-empty list")
    renderer = _RENDERERS.get(target)
    if renderer is None:
        raise ValueError(f"unknown codegen target: {target!r}")
    if failure_bundle and target != "pytest":
        raise ValueError("failure_bundle is currently supported for pytest only")
    return renderer(actions, name, style, failure_bundle)


def generate_code_file(source, output_path: str, target: str = "pytest",
                       name: str = "recorded_flow", style: str = "calls",
                       failure_bundle: bool = False) -> str:
    """Generate code from a list or JSON action-file path; write and return it."""
    actions = source if isinstance(source, list) else read_action_json(
        os.path.realpath(source))
    code = generate_code(actions, target=target, name=name, style=style,
                         failure_bundle=failure_bundle)
    with open(os.path.realpath(output_path), "w", encoding="utf-8") as handle:
        handle.write(code)
    return code
