"""Tests for the .pyi stub generator that mirrors Executor.event_dict."""
import re
from pathlib import Path

from je_auto_control.utils.stubs import (
    StubSignature, collect_signatures, render_pyi, write_pyi,
)


def _sig(name: str, params: str = "", ret: str = "Any",
          doc=None) -> StubSignature:
    return StubSignature(name=name, parameters=params,
                          return_annotation=ret, docstring=doc)


# === collect_signatures ===================================================

def test_collect_signatures_returns_sorted_unique_names():
    signatures = collect_signatures()
    names = [s.name for s in signatures]
    assert names == sorted(names)
    assert len(names) == len(set(names))


def test_collect_signatures_includes_known_commands():
    signatures = collect_signatures()
    names = {s.name for s in signatures}
    assert {"AC_screenshot", "AC_click_mouse", "AC_self_heal_locate",
             "AC_anchor_locate", "AC_wait_screen_stable",
             "AC_ocr_read_structure"} <= names


def test_collect_signatures_renders_default_values_as_ellipsis():
    fake = {"AC_x": lambda a, b="default": None}
    signatures = collect_signatures(event_dict=fake)
    rendered = signatures[0].parameters
    assert "a:" in rendered
    assert "b: Any = ..." in rendered


def test_collect_signatures_falls_back_to_var_args_when_signature_unknown():
    """Builtins like ``len`` reject inspect.signature on some interpreters;
    the generator must emit ``*args, **kwargs`` instead of crashing.
    """
    import inspect
    from je_auto_control.utils.stubs import generator as gen

    class _OpaqueCallable:
        def __call__(self, *_args, **_kwargs):
            return None

    def fake_signature(_handler):
        raise ValueError("no signature for opaque builtin")

    opaque = _OpaqueCallable()
    fake_dict = {"AC_opaque": opaque}
    original = inspect.signature

    def patched(target):
        if target is opaque:
            return fake_signature(target)
        return original(target)

    inspect.signature = patched
    try:
        signatures = gen.collect_signatures(event_dict=fake_dict)
    finally:
        inspect.signature = original
    assert signatures[0].parameters == "*args: Any, **kwargs: Any"


# === render_pyi ===========================================================

def test_render_pyi_includes_header_and_signatures():
    out = render_pyi([_sig("AC_x", "a: int = ...", "Tuple[int, int]")])
    assert "AUTOGENERATED" in out
    assert "from typing import" in out
    assert "def AC_x(a: int = ...) -> Tuple[int, int]:" in out


def test_render_pyi_emits_docstring_when_present():
    out = render_pyi([_sig("AC_x", "", "Any", doc="Do thing.")])
    assert '"""Do thing."""' in out


def test_render_pyi_emits_ellipsis_when_no_docstring():
    out = render_pyi([_sig("AC_x", "", "Any")])
    assert "    ...\n" in out


def test_render_pyi_deterministic():
    sigs = collect_signatures()
    first, second = render_pyi(sigs), render_pyi(sigs)
    assert first == second


# === write_pyi ===========================================================

def test_write_pyi_atomically_creates_file(tmp_path: Path):
    target = tmp_path / "stub.pyi"
    write_pyi(target, [_sig("AC_screenshot", "", "Any")])
    assert target.exists()
    body = target.read_text(encoding="utf-8")
    assert "def AC_screenshot()" in body
    # No leftover tmp file.
    leftovers = list(tmp_path.glob("*.tmp"))
    assert leftovers == []


def test_write_pyi_overwrites_existing_file(tmp_path: Path):
    target = tmp_path / "stub.pyi"
    target.write_text("old", encoding="utf-8")
    write_pyi(target, [_sig("AC_screenshot")])
    assert "old" not in target.read_text(encoding="utf-8")


def test_write_pyi_creates_parent_directory(tmp_path: Path):
    target = tmp_path / "nested" / "deeper" / "stub.pyi"
    write_pyi(target, [_sig("AC_screenshot")])
    assert target.exists()


# === CLI =================================================================

def test_cli_prints_to_stdout(capsys):
    from je_auto_control.utils.stubs.generator import _cli
    exit_code = _cli([])
    assert exit_code == 0
    captured = capsys.readouterr()
    assert "AUTOGENERATED" in captured.out
    assert "def AC_screenshot" in captured.out


def test_cli_writes_when_path_given(tmp_path: Path, capsys):
    from je_auto_control.utils.stubs.generator import _cli
    target = tmp_path / "out.pyi"
    exit_code = _cli([str(target)])
    assert exit_code == 0
    assert target.exists()
    output = capsys.readouterr().out
    assert "wrote" in output


# === Facade exports ======================================================

def test_module_re_exports_public_helpers():
    from je_auto_control.utils import stubs
    for name in ("StubSignature", "collect_signatures",
                  "render_pyi", "write_pyi"):
        assert hasattr(stubs, name)


def test_generated_stub_compiles_to_valid_python_syntax(tmp_path: Path):
    """The .pyi we emit must be valid Python source for IDEs to parse."""
    import ast
    target = tmp_path / "actions.pyi"
    write_pyi(target)
    body = target.read_text(encoding="utf-8")
    # Empty docstring guards against the line ending in ``""""``.
    assert not re.search(r'""""', body)
    ast.parse(body)  # raises SyntaxError on bad output


# === line length and the shipped stub =====================================

def test_split_parameters_keeps_annotation_commas_together():
    from je_auto_control.utils.stubs import generator as gen
    assert gen._split_parameters(
        "a: Dict[str, Any], b: Tuple[int, int] = ..., *args: Any") == [
        "a: Dict[str, Any]", "b: Tuple[int, int] = ...", "*args: Any"]


def test_a_long_signature_is_wrapped_one_parameter_per_line():
    from je_auto_control.utils.stubs import generator as gen
    params = ", ".join(f"parameter_{i}: Dict[str, Any] = ..." for i in range(6))
    out = render_pyi([_sig("AC_long", params, "Dict[str, Any]")])
    assert "def AC_long(\n    parameter_0: Dict[str, Any] = ...,\n" in out
    assert ") -> Dict[str, Any]:\n" in out
    assert max(len(line) for line in out.splitlines()) <= gen.MAX_LINE_LENGTH
    import ast
    ast.parse(out)


def test_a_short_signature_stays_on_one_line():
    out = render_pyi([_sig("AC_x", "a: int = ...", "Any")])
    assert "def AC_x(a: int = ...) -> Any:\n" in out


def test_the_shipped_stub_lists_every_executor_command():
    """``je_auto_control/actions.pyi`` had fallen to 199 of 739 commands.

    Only the names are compared: annotations render differently across Python
    versions (3.14 prints ``typing.Union`` as ``X | Y``), so a byte-for-byte
    comparison would depend on which interpreter regenerated the file.
    Regenerate with ``python -m je_auto_control.utils.stubs.generator
    je_auto_control/actions.pyi``.

    A fresh ``Executor()`` rather than the shared ``executor``: other tests
    register commands on the singleton (a plugin test left ``AC_plugin_loaded``
    behind), and the stub describes what the package ships.
    """
    from je_auto_control.utils.executor.action_executor import Executor
    stub = Path(__file__).resolve().parents[3] / "je_auto_control" / "actions.pyi"
    shipped = set(re.findall(r"^def (\w+)\(", stub.read_text(encoding="utf-8"),
                             flags=re.MULTILINE))
    live = {name for name in Executor().event_dict if isinstance(name, str)}
    assert shipped == live, (
        f"missing: {sorted(live - shipped)[:10]} stale: {sorted(shipped - live)[:10]}")
