"""Tests for the .pyi stub generator that mirrors Executor.event_dict."""
import re
from pathlib import Path

from je_auto_control.utils.stubs import (
    StubSignature, collect_signatures, render_pyi, write_pyi,
)


def _sig(name: str, params: str = "", ret: str = "Any",
          doc=None) -> StubSignature:
    return StubSignature(name=name, parameters=params,
                          return_annotation=ret, docstring=doc)


# === collect_signatures ===================================================

def test_collect_signatures_returns_sorted_unique_names():
    signatures = collect_signatures()
    names = [s.name for s in signatures]
    assert names == sorted(names)
    assert len(names) == len(set(names))


def test_collect_signatures_includes_known_commands():
    signatures = collect_signatures()
    names = {s.name for s in signatures}
    assert {"AC_screenshot", "AC_click_mouse", "AC_self_heal_locate",
             "AC_anchor_locate", "AC_wait_screen_stable",
             "AC_ocr_read_structure"} <= names


def test_collect_signatures_renders_default_values_as_ellipsis():
    fake = {"AC_x": lambda a, b="default": None}
    signatures = collect_signatures(event_dict=fake)
    rendered = signatures[0].parameters
    assert "a:" in rendered
    assert "b: Any = ..." in rendered


def test_collect_signatures_falls_back_to_var_args_when_signature_unknown():
    """Builtins like ``len`` reject inspect.signature on some interpreters;
    the generator must emit ``*args, **kwargs`` instead of crashing.
    """
    import inspect
    from je_auto_control.utils.stubs import generator as gen

    class _OpaqueCallable:
        def __call__(self, *_args, **_kwargs):
            return None

    def fake_signature(_handler):
        raise ValueError("no signature for opaque builtin")

    opaque = _OpaqueCallable()
    fake_dict = {"AC_opaque": opaque}
    original = inspect.signature

    def patched(target):
        if target is opaque:
            return fake_signature(target)
        return original(target)

    inspect.signature = patched
    try:
        signatures = gen.collect_signatures(event_dict=fake_dict)
    finally:
        inspect.signature = original
    assert signatures[0].parameters == "*args: Any, **kwargs: Any"


# === render_pyi ===========================================================

def test_render_pyi_includes_header_and_signatures():
    out = render_pyi([_sig("AC_x", "a: int = ...", "Tuple[int, int]")])
    assert "AUTOGENERATED" in out
    assert "from typing import" in out
    assert "def AC_x(a: int = ...) -> Tuple[int, int]:" in out


def test_render_pyi_emits_docstring_when_present():
    out = render_pyi([_sig("AC_x", "", "Any", doc="Do thing.")])
    assert '"""Do thing."""' in out


def test_render_pyi_emits_ellipsis_when_no_docstring():
    out = render_pyi([_sig("AC_x", "", "Any")])
    assert "    ...\n" in out


def test_render_pyi_deterministic():
    sigs = collect_signatures()
    assert render_pyi(sigs) == render_pyi(sigs)


# === write_pyi ===========================================================

def test_write_pyi_atomically_creates_file(tmp_path: Path):
    target = tmp_path / "stub.pyi"
    write_pyi(target, [_sig("AC_screenshot", "", "Any")])
    assert target.exists()
    body = target.read_text(encoding="utf-8")
    assert "def AC_screenshot()" in body
    # No leftover tmp file.
    leftovers = list(tmp_path.glob("*.tmp"))
    assert leftovers == []


def test_write_pyi_overwrites_existing_file(tmp_path: Path):
    target = tmp_path / "stub.pyi"
    target.write_text("old", encoding="utf-8")
    write_pyi(target, [_sig("AC_screenshot")])
    assert "old" not in target.read_text(encoding="utf-8")


def test_write_pyi_creates_parent_directory(tmp_path: Path):
    target = tmp_path / "nested" / "deeper" / "stub.pyi"
    write_pyi(target, [_sig("AC_screenshot")])
    assert target.exists()


# === CLI =================================================================

def test_cli_prints_to_stdout(capsys):
    from je_auto_control.utils.stubs.generator import _cli
    exit_code = _cli([])
    assert exit_code == 0
    captured = capsys.readouterr()
    assert "AUTOGENERATED" in captured.out
    assert "def AC_screenshot" in captured.out


def test_cli_writes_when_path_given(tmp_path: Path, capsys):
    from je_auto_control.utils.stubs.generator import _cli
    target = tmp_path / "out.pyi"
    exit_code = _cli([str(target)])
    assert exit_code == 0
    assert target.exists()
    output = capsys.readouterr().out
    assert "wrote" in output


# === Facade exports ======================================================

def test_module_re_exports_public_helpers():
    from je_auto_control.utils import stubs
    for name in ("StubSignature", "collect_signatures",
                  "render_pyi", "write_pyi"):
        assert hasattr(stubs, name)


def test_generated_stub_compiles_to_valid_python_syntax(tmp_path: Path):
    """The .pyi we emit must be valid Python source for IDEs to parse."""
    import ast
    target = tmp_path / "actions.pyi"
    write_pyi(target)
    body = target.read_text(encoding="utf-8")
    # Empty docstring guards against the line ending in ``""""``.
    assert not re.search(r'""""', body)
    ast.parse(body)  # raises SyntaxError on bad output
