# AUTOGENERATED by je_auto_control.utils.stubs.generator — do not edit.
# Regenerate with: python -m je_auto_control.utils.stubs.generator
# ruff: noqa: F401  # generated stub keeps typing imports for forward use
from typing import (
    Any, Callable, Dict, List, Mapping, Optional,
    Sequence, Tuple, Union,
)

def AC_a11y_click(name: str | None = ..., role: str | None = ..., app_name: str | None = ...) -> bool:
    """Click the center of the first element matching the filters."""

def AC_a11y_dump(app_name: str | None = ..., max_results: int = ...) -> Dict[str, Any]:
    """Executor adapter: dump the accessibility tree as nested dict."""

def AC_a11y_find(name: str | None = ..., role: str | None = ..., app_name: str | None = ...) -> dict | None:
    """Executor adapter: find an accessibility element, return its dict."""

def AC_a11y_list(app_name: str | None = ..., max_results: int = ...) -> List[dict]:
    """Executor adapter: list accessibility elements as plain dicts."""

def AC_a11y_record_events() -> List[Dict[str, Any]]:
    """Executor adapter: peek at events without stopping the recorder."""

def AC_a11y_record_start(app_name: str | None = ..., poll_interval_s: float = ..., min_movement_px: int = ...) -> Dict[str, Any]:
    """Executor adapter: start the singleton accessibility recorder."""

def AC_a11y_record_stop() -> List[Dict[str, Any]]:
    """Executor adapter: stop the recorder and return the captured events."""

def AC_ab_best_strategy(target_id: str) -> Dict[str, Any]:
    ...

def AC_ab_clear() -> Dict[str, Any]:
    ...

def AC_ab_locate(target_id: str, strategies: Dict[str, Dict[str, Any]], max_parallel: int = ..., record: bool = ...) -> Dict[str, Any]:
    """Executor adapter: race N locator strategies for the same target."""

def AC_ab_report(target_id: str) -> Dict[str, Any]:
    ...

def AC_add_package_to_callback_executor(package: str) -> None:
    """將套件成員加入 CallbackExecutor"""

def AC_add_package_to_executor(package: str) -> None:
    """將套件成員加入 Executor"""

def AC_admin_add_host(label: str, base_url: str, token: str, tags: List[str] | None = ...) -> Dict[str, Any]:
    """Executor adapter: register a remote AutoControl REST endpoint."""

def AC_admin_broadcast_execute(actions: List[Any], labels: List[str] | None = ...) -> List[Dict[str, Any]]:
    ...

def AC_admin_list_hosts() -> List[Dict[str, Any]]:
    ...

def AC_admin_poll(labels: List[str] | None = ...) -> List[Dict[str, Any]]:
    ...

def AC_admin_remove_host(label: str) -> Dict[str, Any]:
    ...

def AC_anchor_click(anchor: Dict[str, Any], target: Dict[str, Any], mouse_keycode: str = ..., relation: str = ..., max_distance_px: float = ...) -> Dict[str, Any]:
    """Executor adapter: anchor-locate + click."""

def AC_anchor_locate(anchor: Dict[str, Any], target: Dict[str, Any], relation: str = ..., max_distance_px: float = ...) -> Dict[str, Any]:
    """Executor adapter: anchor-based spatial locator."""

def AC_android_key(key: str, serial: str | None = ..., adb_path: str | None = ...) -> None:
    """Send a keycode (``KEYCODE_HOME`` etc.) via ``input keyevent``."""

def AC_android_list_devices(adb_path: str | None = ...) -> list:
    """Return ``{serial, state, model, …}`` for every adb-attached device."""

def AC_android_screenshot(file_path: str, serial: str | None = ..., adb_path: str | None = ...) -> str:
    """Capture the live Android screen and save it as PNG at ``file_path``."""

def AC_android_shell(command: str, serial: str | None = ..., adb_path: str | None = ...) -> str:
    """Run an ``adb shell`` command and return its stdout."""

def AC_android_swipe(x1: int, y1: int, x2: int, y2: int, duration_ms: int = ..., serial: str | None = ..., adb_path: str | None = ...) -> None:
    """Send a touch swipe via ``input swipe``."""

def AC_android_tap(x: int, y: int, serial: str | None = ..., adb_path: str | None = ...) -> None:
    """Send a single ``input tap`` to an Android device."""

def AC_android_text(text: str, serial: str | None = ..., adb_path: str | None = ...) -> None:
    """Type a string via ``input text``."""

def AC_audit_log_clear() -> Dict[str, Any]:
    ...

def AC_audit_log_list(event_type: str | None = ..., host_id: str | None = ..., limit: int = ...) -> List[Dict[str, Any]]:
    """Executor adapter: query the audit log."""

def AC_audit_log_verify() -> Dict[str, Any]:
    ...

def AC_chatops_dispatch(message: str, context: Dict[str, Any] | None = ..., script_root: str | None = ...) -> Dict[str, Any]:
    """Executor adapter: route one chat message through the default router."""

def AC_check_key_is_press(keycode: int | str) -> bool | None:
    """檢查某個鍵是否正在被按下"""

def AC_click_mouse(mouse_keycode: int | str, x: int = ..., y: int = ...) -> Tuple[int, int, int]:
    """在指定座標按下並放開滑鼠按鍵"""

def AC_click_text(target: str, mouse_keycode: int | str = ..., lang: str = ..., region: Sequence[int] | None = ..., min_confidence: float = ..., case_sensitive: bool = ..., backend: Any = ...) -> Tuple[int, int]:
    """Locate ``target`` text and click its centre."""

def AC_clipboard_get() -> str:
    """Return the current clipboard text (empty string if empty)."""

def AC_clipboard_set(text: str) -> None:
    """Replace clipboard contents with ``text``."""

def AC_close_window(title_substring: str, case_sensitive: bool = ...) -> bool:
    """Minimise the first matching window."""

def AC_computer_use(goal: str, display_width_px: int | None = ..., display_height_px: int | None = ..., display_number: int | None = ..., max_steps: int = ..., wall_seconds: float = ..., model: str = ..., max_tokens: int = ...) -> Dict[str, Any]:
    """Executor adapter: run Anthropic Computer-Use to achieve ``goal``."""

def AC_config_export() -> Dict[str, Any]:
    """Executor adapter: build the config bundle dict in-memory."""

def AC_config_import(bundle: Dict[str, Any], dry_run: bool = ...) -> Dict[str, Any]:
    """Executor adapter: apply a config bundle dict to the user config root."""

def AC_costs_clear() -> Dict[str, Any]:
    ...

def AC_costs_list(limit: int = ...) -> List[Dict[str, Any]]:
    ...

def AC_costs_record(provider: str, model: str, input_tokens: int, output_tokens: int, label: str | None = ..., run_id: str | None = ..., user: str | None = ...) -> Dict[str, Any]:
    """Executor adapter: append one LLM call to the cost-telemetry log."""

def AC_costs_summary(limit: int = ...) -> Dict[str, Any]:
    """Executor adapter: aggregate cost events by model / provider / day."""

def AC_create_project(project_path: str = ..., parent_name: str = ...) -> None:
    """Create project directory structure and templates."""

def AC_diagnose() -> Dict[str, Any]:
    """Executor adapter: run system diagnostics and return the report."""

def AC_email_trigger_add(host: str, username: str, password: str, script_path: str, port: int | None = ..., use_ssl: bool = ..., mailbox: str = ..., search_criteria: str = ..., mark_seen: bool = ..., poll_seconds: float = ...) -> Dict[str, Any]:
    """Executor adapter: register an IMAP poll trigger."""

def AC_email_trigger_list() -> List[Dict[str, Any]]:
    ...

def AC_email_trigger_poll_once() -> Dict[str, Any]:
    ...

def AC_email_trigger_remove(trigger_id: str) -> Dict[str, Any]:
    ...

def AC_email_trigger_start() -> Dict[str, Any]:
    ...

def AC_email_trigger_stop() -> Dict[str, Any]:
    ...

def AC_execute_action(action_list: list | dict, raise_on_error: bool = ..., _validated: bool = ..., dry_run: bool = ..., step_callback: Callable[[list], None] | None = ...) -> Dict[str, str]:
    """執行 action list"""

def AC_execute_files(execute_files_list: list) -> List[Dict[str, str]]:
    """執行 action files"""

def AC_execute_process(exe_path: str) -> None:
    """Start an external executable file."""

def AC_failure_hook_clear() -> Dict[str, Any]:
    ...

def AC_failure_hook_fire(source: str, source_id: str, error_text: str = ..., script_path: str | None = ..., screenshot_path: str | None = ..., log_tail: str = ..., metadata: Dict[str, Any] | None = ...) -> List[Dict[str, Any]]:
    """Executor adapter: file a ticket through every registered backend."""

def AC_failure_hook_list() -> List[Dict[str, Any]]:
    ...

def AC_find_text_regex(pattern: str, lang: str = ..., region: List[int] | None = ..., min_confidence: float = ..., flags: int = ...) -> List[dict]:
    """Executor adapter: regex OCR search returning JSON-friendly dicts."""

def AC_focus_window(title_substring: str, case_sensitive: bool = ...) -> int:
    """Bring the first matching window to the foreground; return its hwnd."""

def AC_gamepad_click(button: str) -> Dict[str, Any]:
    ...

def AC_gamepad_dpad(direction: str) -> Dict[str, Any]:
    ...

def AC_gamepad_left_stick(x: int, y: int) -> Dict[str, Any]:
    ...

def AC_gamepad_left_trigger(value: int) -> Dict[str, Any]:
    ...

def AC_gamepad_press(button: str) -> Dict[str, Any]:
    ...

def AC_gamepad_release(button: str) -> Dict[str, Any]:
    ...

def AC_gamepad_reset() -> Dict[str, Any]:
    ...

def AC_gamepad_right_stick(x: int, y: int) -> Dict[str, Any]:
    ...

def AC_gamepad_right_trigger(value: int) -> Dict[str, Any]:
    ...

def AC_generate_html() -> str:
    """產生完整 HTML 報告字串"""

def AC_generate_html_report(html_name: str = ...) -> None:
    """輸出 HTML 報告檔案"""

def AC_generate_json() -> Tuple[Dict[str, Dict[str, str]], Dict[str, Dict[str, str]]]:
    """Generate JSON data from test records."""

def AC_generate_json_report(json_file_name: str = ...) -> None:
    """Output JSON report files (success and failure)."""

def AC_generate_xml() -> Tuple[str | bytes, str | bytes]:
    """Generate XML strings from test records."""

def AC_generate_xml_report(xml_file_name: str = ...) -> None:
    """Output XML report files (success and failure)."""

def AC_get_keyboard_keys_table() -> dict:
    """取得鍵盤對應表"""

def AC_get_mouse_position() -> tuple[int, int] | None:
    """取得滑鼠目前位置"""

def AC_get_mouse_table() -> dict:
    """取得滑鼠按鍵對應表"""

def AC_history_clear() -> int:
    """Delete every row (and its artifact file); return rows removed."""

def AC_history_list(limit: int = ..., source_type: str | None = ...) -> List[dict]:
    """Executor adapter: list run history as plain dicts (JSON-friendly)."""

def AC_hotkey(key_code_list: list, is_shift: bool = ...) -> Tuple[str, str] | None:
    """模擬組合鍵 (依序按下，再反向放開)"""

def AC_inspector_recent(n: int = ...) -> List[Dict[str, Any]]:
    """Executor adapter: most recent N WebRTC stat samples."""

def AC_inspector_reset() -> Dict[str, Any]:
    ...

def AC_inspector_summary() -> Dict[str, Any]:
    ...

def AC_list_usb_devices() -> Dict[str, Any]:
    """Executor adapter: enumerate USB devices on this host."""

def AC_list_windows() -> List[Tuple[int, str]]:
    """Return a list of ``(hwnd, title)`` for every visible top-level window."""

def AC_llm_plan(description: str, examples: list | None = ..., model: str | None = ..., max_tokens: int = ...) -> list:
    """Executor adapter: plan without executing, using current command set."""

def AC_llm_run(description: str, examples: list | None = ..., model: str | None = ..., max_tokens: int = ...) -> Dict[str, Any]:
    """Executor adapter: plan and execute against the global executor."""

def AC_locate_all_image(image: Any, detect_threshold: float = ..., draw_image: bool = ...) -> List[List[int]]:
    """找出螢幕上所有符合的影像位置"""

def AC_locate_and_click(image: Any, mouse_keycode: int | str, detect_threshold: float = ..., draw_image: bool = ...) -> Tuple[int, int]:
    """找出影像後自動移動滑鼠並點擊"""

def AC_locate_image_center(image: Any, detect_threshold: float = ..., draw_image: bool = ...) -> Tuple[int, int]:
    """找出單一影像並回傳中心座標"""

def AC_locate_text(target: str, lang: str = ..., region: Sequence[int] | None = ..., min_confidence: float = ..., case_sensitive: bool = ..., backend: Any = ...) -> Tuple[int, int]:
    """Return the centre (x, y) of the first match; raise if not found."""

def AC_mouse_left(x: int | None = ..., y: int | None = ...) -> Tuple[int, int, int]:
    """Click the mouse left mouse button at (x, y)."""

def AC_mouse_middle(x: int | None = ..., y: int | None = ...) -> Tuple[int, int, int]:
    """Click the mouse middle mouse button at (x, y)."""

def AC_mouse_right(x: int | None = ..., y: int | None = ...) -> Tuple[int, int, int]:
    """Click the mouse right mouse button at (x, y)."""

def AC_mouse_scroll(scroll_value: int, x: int = ..., y: int = ..., scroll_direction: str = ...) -> Tuple[int, str]:
    """模擬滑鼠滾輪操作"""

def AC_ocr_read_structure(region: List[int] | None = ..., lang: str = ..., min_confidence: float = ...) -> Dict[str, Any]:
    """Executor adapter: structured OCR (rows / tables / form fields)."""

def AC_presence_clear() -> Dict[str, Any]:
    ...

def AC_presence_list() -> List[Dict[str, Any]]:
    ...

def AC_presence_register(viewer_id: str, label: str = ..., role: str = ...) -> Dict[str, Any]:
    ...

def AC_presence_set_role(viewer_id: str, role: str) -> Dict[str, Any]:
    ...

def AC_presence_unregister(viewer_id: str) -> Dict[str, Any]:
    ...

def AC_presence_update_cursor(viewer_id: str, x: int, y: int) -> Dict[str, Any]:
    ...

def AC_press_keyboard_key(keycode: int | str, is_shift: bool = ..., skip_record: bool = ...) -> str | None:
    """按下指定鍵"""

def AC_press_mouse(mouse_keycode: int | str, x: int = ..., y: int = ...) -> tuple[int, int, int] | None:
    """按下滑鼠按鍵"""

def AC_profiler_disable() -> Dict[str, Any]:
    ...

def AC_profiler_enable() -> Dict[str, Any]:
    ...

def AC_profiler_hot_spots(limit: int = ...) -> List[dict]:
    """Executor adapter: top N actions by total time, as dicts."""

def AC_profiler_reset() -> Dict[str, Any]:
    ...

def AC_profiler_stats(limit: int | None = ...) -> List[dict]:
    """Executor adapter: dump profiler stats as JSON-friendly dicts."""

def AC_read_text_in_region(region: List[int] | None = ..., lang: str = ..., min_confidence: float = ...) -> List[dict]:
    """Executor adapter: dump OCR hits in a region as JSON-friendly dicts."""

def AC_record() -> None:
    """start record keyboard and mouse event until stop_record"""

def AC_release_keyboard_key(keycode: int | str, is_shift: bool = ..., skip_record: bool = ...) -> str | None:
    """放開指定鍵"""

def AC_release_mouse(mouse_keycode: int | str, x: int = ..., y: int = ...) -> tuple[int, int, int] | None:
    """放開滑鼠按鍵"""

def AC_remote_connect(host: str, port: int, token: str, timeout: float = ...) -> Dict[str, Any]:
    """Executor adapter: connect the singleton viewer."""

def AC_remote_disconnect() -> Dict[str, Any]:
    ...

def AC_remote_host_status() -> Dict[str, Any]:
    ...

def AC_remote_send_input(action: Dict[str, Any]) -> Dict[str, Any]:
    ...

def AC_remote_viewer_status() -> Dict[str, Any]:
    ...

def AC_rest_api_start(host: str = ..., port: int = ..., token: str | None = ..., enable_audit: bool = ...) -> Dict[str, Any]:
    """Executor adapter: start the singleton REST API server."""

def AC_rest_api_status() -> Dict[str, Any]:
    ...

def AC_rest_api_stop() -> Dict[str, Any]:
    ...

def AC_run_dag(definition: Dict[str, Any], max_parallel: int = ...) -> Dict[str, Any]:
    """Executor adapter: run a cross-host DAG definition."""

def AC_screen_size() -> Tuple[int, int]:
    """get screen size"""

def AC_screenshot(file_path: str = ..., screen_region: list = ...) -> List[int]:
    """use to capture current screen"""

def AC_secret_init(passphrase: str) -> Dict[str, Any]:
    """Executor adapter: create a fresh vault under ``passphrase``."""

def AC_secret_list() -> List[str]:
    ...

def AC_secret_lock() -> Dict[str, Any]:
    ...

def AC_secret_remove(name: str) -> Dict[str, Any]:
    ...

def AC_secret_set(name: str, value: str) -> Dict[str, Any]:
    ...

def AC_secret_status() -> Dict[str, Any]:
    ...

def AC_secret_unlock(passphrase: str) -> Dict[str, Any]:
    ...

def AC_self_heal_click(template_path: str | None = ..., description: str | None = ..., mouse_keycode: str = ..., detect_threshold: float = ..., screen_region: List[int] | None = ..., model: str | None = ..., raise_on_miss: bool = ...) -> Dict[str, Any]:
    """Executor adapter: locate with self-heal, then click."""

def AC_self_heal_locate(template_path: str | None = ..., description: str | None = ..., detect_threshold: float = ..., screen_region: List[int] | None = ..., model: str | None = ..., raise_on_miss: bool = ...) -> Dict[str, Any]:
    """Executor adapter: template-first locate with VLM fallback."""

def AC_self_heal_log_clear() -> Dict[str, Any]:
    ...

def AC_self_heal_log_list(limit: int = ...) -> List[Dict[str, Any]]:
    """Executor adapter: return the recent self-healing events."""

def AC_set_mouse_position(x: int, y: int) -> tuple[int, int] | None:
    """設定滑鼠位置"""

def AC_set_record_enable(set_enable: bool = ...) -> None:
    """設定是否啟用紀錄"""

def AC_shell_command(shell_command: str | List[str]) -> None:
    """Execute shell command with shell=False."""

def AC_start_mcp_http_server(host: str = ..., port: int = ..., mcp: Any = ..., auth_token: str | None = ..., ssl_context: Any = ...) -> Any:
    """Start and return an :class:`HttpMCPServer`; convenience wrapper."""

def AC_start_mcp_server() -> Any:
    """Start a stdio MCP server in the foreground; blocks until EOF."""

def AC_start_remote_host(token: str, bind: str = ..., port: int = ..., fps: float = ..., quality: int = ..., region: List[int] | None = ..., max_clients: int = ...) -> Dict[str, Any]:
    """Executor adapter: start the singleton remote-desktop host."""

def AC_start_webrtc_host(token: str, read_only: bool = ...) -> Dict[str, Any]:
    """Executor adapter: allocate the singleton WebRTC host."""

def AC_start_webrtc_viewer(token: str, viewer_id: str | None = ...) -> Dict[str, Any]:
    """Executor adapter: allocate the singleton WebRTC viewer."""

def AC_start_ws_host(token: str, bind: str = ..., port: int = ..., fps: float = ..., quality: int = ..., region: List[int] | None = ..., max_clients: int = ...) -> Dict[str, Any]:
    """Executor adapter: start the singleton WebSocket-transport host."""

def AC_stop_record() -> list:
    """stop current record"""

def AC_stop_remote_host() -> Dict[str, Any]:
    ...

def AC_stop_webrtc_host() -> Dict[str, Any]:
    ...

def AC_stop_webrtc_viewer() -> Dict[str, Any]:
    ...

def AC_stop_ws_host() -> Dict[str, Any]:
    ...

def AC_type_keyboard(keycode: int | str, is_shift: bool = ..., skip_record: bool = ...) -> str | None:
    """模擬輸入 (按下再放開)"""

def AC_usb_recent_events(since: int = ..., limit: int | None = ...) -> List[Dict[str, Any]]:
    ...

def AC_usb_watch_start(poll_interval_s: float = ...) -> Dict[str, Any]:
    """Executor adapter: start the singleton USB hotplug watcher."""

def AC_usb_watch_stop() -> Dict[str, Any]:
    ...

def AC_vlm_click(description: str, screen_region: List[int] | None = ..., model: str | None = ..., backend: Any = ...) -> bool:
    """Locate by description, then click the center of the match."""

def AC_vlm_locate(description: str, screen_region: List[int] | None = ..., model: str | None = ...) -> List[int] | None:
    """Executor adapter: return VLM-located coords as a JSON-safe list."""

def AC_wait_pixel_changes(x: int, y: int, timeout_s: float = ..., poll_interval_s: float = ..., rgb_tolerance: int = ...) -> Dict[str, Any]:
    """Executor adapter: smart wait for one pixel to change colour."""

def AC_wait_region_idle(region: List[int], timeout_s: float = ..., poll_interval_s: float = ..., stable_for_s: float = ..., max_pixel_diff: int = ...) -> Dict[str, Any]:
    """Executor adapter: smart wait for a sub-region to stop moving."""

def AC_wait_screen_stable(region: List[int] | None = ..., timeout_s: float = ..., poll_interval_s: float = ..., stable_for_s: float = ..., max_pixel_diff: int = ...) -> Dict[str, Any]:
    """Executor adapter: smart wait for the screen to stop moving."""

def AC_wait_text(target: str, lang: str = ..., region: Sequence[int] | None = ..., timeout: float = ..., poll: float = ..., min_confidence: float = ..., case_sensitive: bool = ..., backend: Any = ...) -> Tuple[int, int]:
    """Poll until ``target`` appears on screen; raise on timeout."""

def AC_wait_window(title_substring: str, timeout: float = ..., poll: float = ..., case_sensitive: bool = ...) -> int:
    """Poll until a window with the given title appears; return its hwnd."""

def AC_web_available() -> bool:
    """Return True when ``je_web_runner`` is importable."""

def AC_web_current_url() -> Any:
    """Convenience executor: return the active browser tab's URL."""

def AC_web_list_commands() -> list:
    """Return every WR_* command the local WebRunner install exposes."""

def AC_web_open(url: str, browser: str = ..., **driver_kwargs: Any) -> Any:
    """Convenience executor: start a browser then navigate to ``url``."""

def AC_web_quit() -> Any:
    """Convenience executor: tear down WebRunner driver sessions."""

def AC_web_run(action: Dict[str, Any] | None = ..., **action_kwargs: Any) -> Any:
    """Bridge one WR_* action into the WebRunner executor (Phase 7.7)."""

def AC_web_run_actions(actions: list) -> list:
    """Bridge a list of WR_* actions through the WebRunner executor."""

def AC_web_screenshot(file_path: str) -> Any:
    """Convenience executor: save a screenshot of the active browser."""

def AC_webhook_add(path: str, script_path: str, methods: List[str] | None = ..., token: str | None = ...) -> Dict[str, Any]:
    ...

def AC_webhook_list() -> List[Dict[str, Any]]:
    ...

def AC_webhook_remove(webhook_id: str) -> Dict[str, Any]:
    ...

def AC_webhook_start(host: str = ..., port: int = ...) -> Dict[str, Any]:
    """Executor adapter: start the webhook HTTP server."""

def AC_webhook_status() -> Dict[str, Any]:
    ...

def AC_webhook_stop() -> Dict[str, Any]:
    ...

def AC_webrtc_accept_answer(answer_sdp: str) -> Dict[str, Any]:
    ...

def AC_webrtc_create_offer(peer_label: str = ...) -> Dict[str, Any]:
    ...

def AC_webrtc_host_status() -> Dict[str, Any]:
    ...

def AC_webrtc_process_offer(offer_sdp: str, expected_dtls_fingerprint: str | None = ...) -> Dict[str, Any]:
    ...

def AC_webrtc_send_input(action: Dict[str, Any]) -> Dict[str, Any]:
    ...

def AC_webrtc_viewer_status() -> Dict[str, Any]:
    ...

def AC_write(write_string: str, is_shift: bool = ...) -> str | None:
    """模擬輸入整個字串"""

def AC_ws_connect(host: str, port: int, token: str, path: str = ..., timeout: float = ...) -> Dict[str, Any]:
    """Executor adapter: connect the singleton WS viewer."""

def AC_ws_disconnect() -> Dict[str, Any]:
    ...

def AC_ws_host_status() -> Dict[str, Any]:
    ...

def AC_ws_send_input(action: Dict[str, Any]) -> Dict[str, Any]:
    ...

def AC_ws_viewer_status() -> Dict[str, Any]:
    ...
