from je_auto_control.osx.core.utils.osx_vk import (
    osx_key_a, osx_key_A, osx_key_b, osx_key_B, osx_key_c, osx_key_C,
    osx_key_d, osx_key_D, osx_key_e, osx_key_E, osx_key_f, osx_key_F,
    osx_key_g, osx_key_G, osx_key_h, osx_key_H, osx_key_i, osx_key_I,
    osx_key_j, osx_key_J, osx_key_k, osx_key_K, osx_key_l, osx_key_L,
    osx_key_m, osx_key_M, osx_key_n, osx_key_N, osx_key_o, osx_key_O,
    osx_key_p, osx_key_P, osx_key_q, osx_key_Q, osx_key_r, osx_key_R,
    osx_key_s, osx_key_S, osx_key_t, osx_key_T, osx_key_u, osx_key_U,
    osx_key_v, osx_key_V, osx_key_w, osx_key_W, osx_key_x, osx_key_X,
    osx_key_y, osx_key_Y, osx_key_z, osx_key_Z,
    osx_key_1, osx_key_exclam, osx_key_2, osx_key_at,
    osx_key_3, osx_key_numbersign, osx_key_4, osx_key_money,
    osx_key_5, osx_key_percent, osx_key_6, osx_key_asciicircum,
    osx_key_7, osx_key_ampersand, osx_key_8, osx_key_asterisk,
    osx_key_9, osx_key_parenleft, osx_key_0, osx_key_parenright,
    osx_key_equal, osx_key_plus, osx_key_minus, osx_key_underscore,
    osx_key_bracketright, osx_key_braceright,
    osx_key_bracketleft, osx_key_braceleft,
    osx_key_apostrophe, osx_key_quotedbl,
    osx_key_semicolon, osx_key_colon, osx_key_backslash, osx_key_bar,
    osx_key_comma, osx_key_less, osx_key_slash, osx_key_question,
    osx_key_period, osx_key_greater, osx_key_grave, osx_key_asciitilde,
    osx_key_space, osx_key_return, osx_key_newline, osx_key_enter,
    osx_key_tab, osx_key_backspace, osx_key_esc, osx_key_command,
    osx_key_shift, osx_key_caps_lock, osx_key_option, osx_key_alt,
    osx_key_ctrl, osx_key_shift_right, osx_key_option_right,
    osx_key_control_right, osx_key_fn,
    osx_key_volume_up, osx_key_volume_down, osx_key_volume_mute,
    osx_key_f1, osx_key_f2, osx_key_f3, osx_key_f4, osx_key_f5,
    osx_key_f6, osx_key_f7, osx_key_f8, osx_key_f9, osx_key_f10,
    osx_key_f11, osx_key_f12, osx_key_f13, osx_key_f14, osx_key_f15,
    osx_key_f16, osx_key_f17, osx_key_f18, osx_key_f19, osx_key_f20,
    osx_key_help, osx_key_home, osx_key_pageup, osx_key_end,
    osx_key_pagedown, osx_key_left, osx_key_right, osx_key_down, osx_key_up,
    osx_key_yen, osx_key_eisu, osx_key_kana,
    osx_mouse_left, osx_mouse_middle, osx_mouse_right,
)
from je_auto_control.osx.keyboard import osx_keyboard, osx_keyboard_check
from je_auto_control.osx.mouse import osx_mouse
from je_auto_control.osx.screen import osx_screen
from je_auto_control.utils.exception.exceptions import AutoControlException
from je_auto_control.utils.logging.logging_instance import autocontrol_logger

autocontrol_logger.info("Load MacOS Setting")

keyboard_keys_table = {
    "a": osx_key_a, "A": osx_key_A,
    "b": osx_key_b, "B": osx_key_B,
    "c": osx_key_c, "C": osx_key_C,
    "d": osx_key_d, "D": osx_key_D,
    "e": osx_key_e, "E": osx_key_E,
    "f": osx_key_f, "F": osx_key_F,
    "g": osx_key_g, "G": osx_key_G,
    "h": osx_key_h, "H": osx_key_H,
    "i": osx_key_i, "I": osx_key_I,
    "j": osx_key_j, "J": osx_key_J,
    "k": osx_key_k, "K": osx_key_K,
    "l": osx_key_l, "L": osx_key_L,
    "m": osx_key_m, "M": osx_key_M,
    "n": osx_key_n, "N": osx_key_N,
    "o": osx_key_o, "O": osx_key_O,
    "p": osx_key_p, "P": osx_key_P,
    "q": osx_key_q, "Q": osx_key_Q,
    "r": osx_key_r, "R": osx_key_R,
    "s": osx_key_s, "S": osx_key_S,
    "t": osx_key_t, "T": osx_key_T,
    "u": osx_key_u, "U": osx_key_U,
    "v": osx_key_v, "V": osx_key_V,
    "w": osx_key_w, "W": osx_key_W,
    "x": osx_key_x, "X": osx_key_X,
    "y": osx_key_y, "Y": osx_key_Y,
    "z": osx_key_z, "Z": osx_key_Z,
    "1": osx_key_1, "!": osx_key_exclam,
    "2": osx_key_2, "@": osx_key_at,
    "3": osx_key_3, "#": osx_key_numbersign,
    "4": osx_key_4, "$": osx_key_money,
    "5": osx_key_5, "%": osx_key_percent,
    "6": osx_key_6, "^": osx_key_asciicircum,
    "7": osx_key_7, "&": osx_key_ampersand,
    "8": osx_key_8, "*": osx_key_asterisk,
    "9": osx_key_9, "(": osx_key_parenleft,
    "0": osx_key_0, ")": osx_key_parenright,
    "=": osx_key_equal, "+": osx_key_plus,
    "-": osx_key_minus, "_": osx_key_underscore,
    "]": osx_key_bracketright, "}": osx_key_braceright,
    "[": osx_key_bracketleft, "{": osx_key_braceleft,
    "'": osx_key_apostrophe, '"': osx_key_quotedbl,
    ";": osx_key_semicolon, ":": osx_key_colon,
    "\\": osx_key_backslash, "|": osx_key_bar,
    ",": osx_key_comma, "<": osx_key_less,
    "/": osx_key_slash, "?": osx_key_question,
    ".": osx_key_period, ">": osx_key_greater,
    "`": osx_key_grave, "~": osx_key_asciitilde,
    "space": osx_key_space,
    "return": osx_key_return,
    "newline": osx_key_newline,
    "enter": osx_key_enter,
    "tab": osx_key_tab,
    "backspace": osx_key_backspace,
    "esc": osx_key_esc,
    "command": osx_key_command,
    "shift": osx_key_shift,
    "caps_lock": osx_key_caps_lock,
    "option": osx_key_option,
    "alt": osx_key_alt,
    "ctrl": osx_key_ctrl,
    "shift_right": osx_key_shift_right,
    "option_right": osx_key_option_right,
    "control_right": osx_key_control_right,
    "fn": osx_key_fn,
    "volume_up": osx_key_volume_up,
    "volume_down": osx_key_volume_down,
    "volume_mute": osx_key_volume_mute,
    "f1": osx_key_f1, "f2": osx_key_f2, "f3": osx_key_f3,
    "f4": osx_key_f4, "f5": osx_key_f5, "f6": osx_key_f6,
    "f7": osx_key_f7, "f8": osx_key_f8, "f9": osx_key_f9,
    "f10": osx_key_f10, "f11": osx_key_f11, "f12": osx_key_f12,
    "f13": osx_key_f13, "f14": osx_key_f14, "f15": osx_key_f15,
    "f16": osx_key_f16, "f17": osx_key_f17, "f18": osx_key_f18,
    "f19": osx_key_f19, "f20": osx_key_f20,
    "help": osx_key_help,
    "home": osx_key_home,
    "pageup": osx_key_pageup,
    "end": osx_key_end,
    "pagedown": osx_key_pagedown,
    "left": osx_key_left,
    "right": osx_key_right,
    "down": osx_key_down,
    "up": osx_key_up,
    "yen": osx_key_yen,
    "eisu": osx_key_eisu,
    "kana": osx_key_kana,
}

mouse_keys_table = {
    "mouse_left": osx_mouse_left,
    "mouse_middle": osx_mouse_middle,
    "mouse_right": osx_mouse_right,
}

special_mouse_keys_table = None
keyboard = osx_keyboard
keyboard_check = osx_keyboard_check
mouse = osx_mouse
screen = osx_screen
recorder = None

if None in [keyboard_keys_table, mouse_keys_table, keyboard_check, keyboard, mouse, screen]:
    raise AutoControlException("Can't init auto control")
