"""coturn configuration generator + helper artifacts.

When users need NAT traversal beyond what public STUN can do (mobile
networks, restrictive firewalls), they need a TURN relay. We don't run
one ourselves, but we generate the config files so they can drop them
into a Linux box and ``apt install coturn`` (or use the Docker compose
file).

Run::

    python -m je_auto_control.utils.remote_desktop.turn_config \\
        --realm myhome.example.com \\
        --user alice \\
        --secret SECRET123 \\
        --listen 3478 --tls-cert /etc/letsencrypt/live/...

Outputs:
  * ``turnserver.conf`` — coturn config
  * ``coturn.service`` — systemd unit
  * ``docker-compose.yml`` — single-container deploy
  * ``README.txt`` — quick reference (host:port + cred to feed AutoControl GUI)
"""
from __future__ import annotations

import argparse
import secrets
import sys
from pathlib import Path
from typing import Optional


_DEFAULT_PORT = 3478
_DEFAULT_TLS_PORT = 5349
_DEFAULT_RELAY_LOW = 49152
_DEFAULT_RELAY_HIGH = 65535


def render_turnserver_conf(*, realm: str, listen_port: int,
                            tls_port: int,
                            user: str, secret: str,
                            tls_cert: Optional[str] = None,
                            tls_key: Optional[str] = None,
                            external_ip: Optional[str] = None,
                            relay_low: int = _DEFAULT_RELAY_LOW,
                            relay_high: int = _DEFAULT_RELAY_HIGH) -> str:
    """Build a coturn ``turnserver.conf`` body with the supplied fields."""
    lines = [
        "# Generated by AutoControl turn_config",
        f"realm={realm}",
        f"listening-port={listen_port}",
        f"min-port={relay_low}",
        f"max-port={relay_high}",
        "fingerprint",
        "lt-cred-mech",
        f"user={user}:{secret}",
        "no-cli",
        "no-multicast-peers",
        "no-loopback-peers",
        "stale-nonce=600",
        "log-file=stdout",
        "verbose",
    ]
    if external_ip:
        lines.append(f"external-ip={external_ip}")
    if tls_cert and tls_key:
        lines.extend([
            f"tls-listening-port={tls_port}",
            f"cert={tls_cert}",
            f"pkey={tls_key}",
            "cipher-list=HIGH:!aNULL:!MD5",
        ])
    return "\n".join(lines) + "\n"


def render_systemd_unit(*, conf_path: str) -> str:
    return (
        "[Unit]\n"
        "Description=coturn TURN/STUN server (AutoControl)\n"
        "After=network-online.target\n"
        "\n"
        "[Service]\n"
        "Type=simple\n"
        f"ExecStart=/usr/bin/turnserver -c {conf_path}\n"
        "Restart=on-failure\n"
        "RestartSec=5\n"
        "User=turnserver\n"
        "Group=turnserver\n"
        "\n"
        "[Install]\n"
        "WantedBy=multi-user.target\n"
    )


def render_docker_compose(*, conf_path: str, listen_port: int,
                          tls_port: int,
                          relay_low: int = _DEFAULT_RELAY_LOW,
                          relay_high: int = _DEFAULT_RELAY_HIGH) -> str:
    return (
        "version: '3'\n"
        "services:\n"
        "  coturn:\n"
        "    image: coturn/coturn:latest\n"
        "    network_mode: host\n"
        "    restart: unless-stopped\n"
        "    volumes:\n"
        f"      - {conf_path}:/etc/coturn/turnserver.conf:ro\n"
        "    command: -c /etc/coturn/turnserver.conf\n"
        f"    # Exposed: UDP/TCP {listen_port}, TLS {tls_port}, "
        f"relay UDP {relay_low}-{relay_high}\n"
    )


def render_readme(*, realm: str, listen_port: int, tls_port: int,
                  user: str, secret: str, tls: bool) -> str:
    scheme = "turns" if tls else "turn"
    port = tls_port if tls else listen_port
    return (
        "AutoControl TURN config bundle\n"
        "==============================\n"
        "\n"
        "Drop the artifacts onto a publicly routable Linux box (a $5 VPS\n"
        "is enough). With Debian/Ubuntu:\n"
        "\n"
        "  sudo apt install -y coturn\n"
        "  sudo cp turnserver.conf /etc/turnserver.conf\n"
        "  sudo cp coturn.service /etc/systemd/system/\n"
        "  sudo systemctl daemon-reload\n"
        "  sudo systemctl enable --now coturn\n"
        "\n"
        "Or with Docker:\n"
        "\n"
        "  docker compose up -d\n"
        "\n"
        "In the AutoControl GUI advanced section, fill:\n"
        f"  TURN URL:   {scheme}:{realm}:{port}\n"
        f"  TURN user:  {user}\n"
        f"  TURN cred:  {secret}\n"
    )


def write_bundle(output_dir: Path, *, realm: str, user: str,
                 secret: str, listen_port: int, tls_port: int,
                 tls_cert: Optional[str], tls_key: Optional[str],
                 external_ip: Optional[str]) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    conf_path = output_dir / "turnserver.conf"
    conf_path.write_text(render_turnserver_conf(
        realm=realm, listen_port=listen_port, tls_port=tls_port,
        user=user, secret=secret,
        tls_cert=tls_cert, tls_key=tls_key,
        external_ip=external_ip,
    ), encoding="utf-8")
    (output_dir / "coturn.service").write_text(
        render_systemd_unit(conf_path=str(conf_path)),
        encoding="utf-8",
    )
    (output_dir / "docker-compose.yml").write_text(
        render_docker_compose(
            conf_path=str(conf_path),
            listen_port=listen_port, tls_port=tls_port,
        ),
        encoding="utf-8",
    )
    (output_dir / "README.txt").write_text(
        render_readme(realm=realm, listen_port=listen_port, tls_port=tls_port,
                      user=user, secret=secret,
                      tls=bool(tls_cert and tls_key)),
        encoding="utf-8",
    )


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="je_auto_control.utils.remote_desktop.turn_config",
        description="Generate coturn config + deploy artifacts for AutoControl.",
    )
    parser.add_argument("--realm", required=True,
                        help="public hostname or IP, e.g. turn.example.com")
    parser.add_argument("--user", required=True, help="long-term auth username")
    parser.add_argument("--secret", default=None,
                        help="long-term auth secret (auto-generated if omitted)")
    parser.add_argument("--listen", type=int, default=_DEFAULT_PORT,
                        help=f"plain UDP/TCP port (default {_DEFAULT_PORT})")
    parser.add_argument("--tls-port", type=int, default=_DEFAULT_TLS_PORT,
                        help=f"TLS port (default {_DEFAULT_TLS_PORT})")
    parser.add_argument("--tls-cert", default=None,
                        help="path to TLS cert PEM (enables turns://)")
    parser.add_argument("--tls-key", default=None,
                        help="path to TLS key PEM")
    parser.add_argument("--external-ip", default=None,
                        help="public IP if behind NAT (e.g. EC2 EIP)")
    parser.add_argument("--output-dir", type=Path, default=Path("./turn-bundle"),
                        help="directory to write artifacts into")
    return parser


def main(argv: Optional[list] = None) -> int:
    args = _build_arg_parser().parse_args(argv)
    secret = args.secret or secrets.token_urlsafe(24)
    write_bundle(
        args.output_dir,
        realm=args.realm, user=args.user, secret=secret,
        listen_port=args.listen, tls_port=args.tls_port,
        tls_cert=args.tls_cert, tls_key=args.tls_key,
        external_ip=args.external_ip,
    )
    print(f"Wrote bundle to: {args.output_dir.resolve()}")
    print(f"  Username: {args.user}")
    print(f"  Secret:   {secret}")
    print(f"  Realm:    {args.realm}")
    print(f"  Plain port: {args.listen}")
    if args.tls_cert and args.tls_key:
        print(f"  TLS port:   {args.tls_port}")
    print("\nSee README.txt in the bundle for deployment steps.")
    return 0


if __name__ == "__main__":
    sys.exit(main())


__all__ = [
    "render_turnserver_conf", "render_systemd_unit", "render_docker_compose",
    "render_readme", "write_bundle", "main",
]
