"""Pure tab catalog: stable keys, lazy import targets and action metadata."""

TAB_CATALOG = (('auto_click',
  'tab_auto_click',
  'core',
  False,
  '',
  '_build_auto_click_tab',
  (('start', '_start_auto_click'),
   ('stop', '_stop_auto_click'),
   ('get_position', '_get_mouse_pos'),
   ('hotkey_send', '_send_hotkey'),
   ('write_send', '_send_write'),
   ('scroll_send', '_send_scroll'))),
 ('screenshot',
  'tab_screenshot',
  'core',
  False,
  '',
  '_build_screenshot_tab',
  (('take_screenshot', '_take_screenshot'),
   ('browse', '_browse_ss_path'),
   ('pick_region', '_pick_ss_region'),
   ('get_screen_size', '_get_screen_size'),
   ('get_pixel_label', '_get_pixel_color'),
   ('workspace_cancel_task', '_cancel_capture'))),
 ('image_detect',
  'tab_image_detect',
  'core',
  False,
  '',
  '_build_image_detect_tab',
  (('browse', '_browse_img'),
   ('crop_template', '_crop_template'),
   ('locate_image', '_locate_image'),
   ('locate_all', '_locate_all'),
   ('locate_click', '_locate_click'),
   ('workspace_cancel_task', '_cancel_detection'))),
 ('record',
  'tab_record',
  'core',
  True,
  '',
  '_build_record_tab',
  (('start_record', '_start_record'),
   ('stop_record', '_stop_record'),
   ('playback', '_playback_record'),
   ('save_record', '_save_record'),
   ('load_record', '_load_record'))),
 ('script_builder',
  'tab_script_builder',
  'core',
  True,
  'je_auto_control.gui.script_builder',
  'ScriptBuilderTab',
  ()),
 ('flow_editor',
  'tab_flow_editor',
  'editing',
  False,
  'je_auto_control.gui.flow_editor',
  'FlowEditorTab',
  (('flow_open_btn', '_on_open'),
   ('flow_save_btn', '_on_save'),
   ('flow_zoom_in_btn', '_on_zoom_in'),
   ('flow_zoom_out_btn', '_on_zoom_out'),
   ('flow_fit_btn', '_on_fit'))),
 ('script',
  'tab_script',
  'editing',
  False,
  '',
  '_build_script_tab',
  (('load_script', '_browse_script'),
   ('execute_script', '_execute_script'),
   ('menu_choose_script_dir', '_browse_script_dir'),
   ('execute_dir', '_execute_dir'),
   ('execute_editor_script', '_execute_manual_script'),
   ('workspace_cancel_task', '_cancel_script'))),
 ('recording_editor',
  'tab_recording_editor',
  'editing',
  False,
  'je_auto_control.gui.recording_editor_tab',
  'RecordingEditorTab',
  (('re_browse', '_browse'),
   ('re_load', '_load'),
   ('re_save_as', '_save_as'),
   ('re_export_code', '_export_code'),
   ('re_apply_trim', '_apply_trim'),
   ('re_remove_selected', '_remove_selected'),
   ('re_undo', '_undo'),
   ('re_apply_delays', '_apply_delays'),
   ('re_apply_scale', '_apply_scale'),
   ('re_keep_mouse', '_keep_mouse'),
   ('re_keep_keyboard', '_keep_keyboard'))),
 ('config_sync',
  'tab_config_sync',
  'editing',
  False,
  'je_auto_control.gui.config_sync_tab',
  'ConfigSyncTab',
  (('sync_preview', '_preview'),
   ('sync_exchange', '_exchange'),
   ('sync_apply', '_apply'),
   ('sync_retry', '_retry'),
   ('sync_status', '_status'),
   ('sync_assets', '_assets'),
   ('sync_cancel', '_cancel'))),
 ('variables',
  'tab_variables',
  'editing',
  False,
  'je_auto_control.gui.variables_tab',
  'VariablesTab',
  (('vars_refresh', '_refresh'),
   ('vars_set_btn', '_on_set_one'),
   ('vars_seed_btn', '_on_seed_json'),
   ('vars_clear', '_on_clear'))),
 ('secrets',
  'tab_secrets',
  'editing',
  False,
  'je_auto_control.gui.secrets_tab',
  'SecretsTab',
  (('secret_unlock', '_on_unlock'),
   ('secret_lock', '_on_lock'),
   ('secret_add', '_on_add'),
   ('secret_remove', '_on_remove'),
   ('secret_init', '_on_init'),
   ('secret_change_passphrase', '_on_change_passphrase'))),
 ('vlm',
  'tab_vlm',
  'detection',
  False,
  'je_auto_control.gui.vlm_tab',
  'VLMTab',
  (('vlm_locate', '_on_locate'), ('vlm_click', '_on_click'))),
 ('self_healing',
  'tab_self_healing',
  'detection',
  False,
  'je_auto_control.gui.self_healing_tab',
  'SelfHealingTab',
  (('self_heal_browse', '_on_browse_template'),
   ('self_heal_locate_btn', '_on_locate'),
   ('self_heal_click_btn', '_on_click'),
   ('self_heal_refresh', 'refresh_log'),
   ('self_heal_clear', '_on_clear_log'))),
 ('ocr_reader',
  'tab_ocr_reader',
  'detection',
  False,
  'je_auto_control.gui.ocr_tab',
  'OCRReaderTab',
  (('ocr_pick_region', '_on_pick_region'),
   ('ocr_dump_region', '_on_dump'),
   ('ocr_find_regex', '_on_find_regex'))),
 ('accessibility',
  'tab_accessibility',
  'detection',
  False,
  'je_auto_control.gui.accessibility_tab',
  'AccessibilityTab',
  (('a11y_refresh', '_refresh'),
   ('a11y_click_selected', '_click_selected'),
   ('a11y_show_focused', '_show_focused'))),
 ('live_hud',
  'tab_live_hud',
  'detection',
  False,
  'je_auto_control.gui.live_hud_tab',
  'LiveHUDTab',
  (('hud_start', '_start'), ('hud_stop', '_stop'), ('hud_clear', 'clear'))),
 ('llm_planner',
  'tab_llm_planner',
  'detection',
  False,
  'je_auto_control.gui.llm_planner_tab',
  'LLMPlannerTab',
  (('llm_plan_btn', '_on_plan'), ('llm_run_btn', '_on_run'))),
 ('computer_use',
  'tab_computer_use',
  'detection',
  False,
  'je_auto_control.gui.computer_use_tab',
  'ComputerUseTab',
  (('computer_use_run_btn', '_on_run'), ('computer_use_stop_btn', '_on_stop'))),
 ('scheduler',
  'tab_scheduler',
  'automation',
  False,
  'je_auto_control.gui.scheduler_tab',
  'SchedulerTab',
  (('browse', '_browse'),
   ('sch_add', '_on_add'),
   ('sch_remove_selected', '_on_remove'),
   ('sch_start', '_on_start'),
   ('sch_stop', '_on_stop'))),
 ('hotkeys',
  'tab_hotkeys',
  'automation',
  False,
  'je_auto_control.gui.hotkeys_tab',
  'HotkeysTab',
  (('browse', '_browse'),
   ('hk_bind', '_on_bind'),
   ('hk_remove_selected', '_on_remove'),
   ('hk_start_daemon', '_on_start'),
   ('hk_stop_daemon', '_on_stop'))),
 ('triggers',
  'tab_triggers',
  'automation',
  False,
  'je_auto_control.gui.triggers_tab',
  'TriggersTab',
  (('browse', '_browse_script'),
   ('tr_add', '_on_add'),
   ('tr_remove_selected', '_on_remove'),
   ('tr_start_engine', '_on_start'),
   ('tr_stop_engine', '_on_stop'))),
 ('webhooks',
  'tab_webhooks',
  'automation',
  False,
  'je_auto_control.gui.webhooks_tab',
  'WebhooksTab',
  (('wh_start', '_on_start'),
   ('wh_stop', '_on_stop'),
   ('wh_browse', '_on_browse'),
   ('wh_register', '_on_register'),
   ('wh_remove', '_on_remove'))),
 ('email_triggers',
  'tab_email_triggers',
  'automation',
  False,
  'je_auto_control.gui.email_triggers_tab',
  'EmailTriggersTab',
  (('eml_start', '_on_start'),
   ('eml_stop', '_on_stop'),
   ('eml_poll_now', '_on_poll_now'),
   ('eml_browse', '_on_browse'),
   ('eml_register', '_on_register'),
   ('eml_remove', '_on_remove'))),
 ('test_suite',
  'tab_test_suite',
  'core',
  False,
  'je_auto_control.gui.test_suite_tab',
  'TestSuiteTab',
  (('suite_load_file', '_on_load_file'),
   ('suite_run', '_on_run'),
   ('suite_junit', '_on_junit'),
   ('suite_allure', '_on_allure'),
   ('suite_q_auto', '_on_auto_quarantine'),
   ('suite_q_remove', '_on_release_selected'),
   ('suite_q_clear', '_on_clear_quarantine'))),
 ('assertions',
  'tab_assertions',
  'core',
  False,
  'je_auto_control.gui.assertions_tab',
  'AssertionsTab',
  (('assert_run', '_on_run'),)),
 ('data_source',
  'tab_data_source',
  'core',
  False,
  'je_auto_control.gui.data_source_tab',
  'DataSourceTab',
  (('ds_load', '_on_load'),)),
 ('flakiness',
  'tab_flakiness',
  'system',
  False,
  'je_auto_control.gui.flakiness_tab',
  'FlakinessTab',
  (('flaky_refresh', '_refresh'),)),
 ('a11y_audit',
  'tab_a11y_audit',
  'core',
  False,
  'je_auto_control.gui.a11y_audit_tab',
  'A11yAuditTab',
  (('audit_run', '_on_run'), ('audit_contrast_run', '_on_contrast'))),
 ('mobile',
  'tab_mobile',
  'core',
  False,
  'je_auto_control.gui.mobile_tab',
  'MobileTab',
  (('mobile_open', '_on_open'),
   ('mobile_probe', '_on_probe'),
   ('mobile_diagnose', '_on_diagnose'),
   ('mobile_run_operation', '_on_operation'),
   ('mobile_run_actions', '_on_actions'),
   ('mobile_close', '_on_close_owner'))),
 ('device_matrix',
  'tab_device_matrix',
  'core',
  False,
  'je_auto_control.gui.device_matrix_tab',
  'DeviceMatrixTab',
  (('dm_run', '_on_run'), ('dm_probe', '_on_probe'))),
 ('media_checks',
  'tab_media_checks',
  'core',
  False,
  'je_auto_control.gui.media_checks_tab',
  'MediaChecksTab',
  (('media_audio_run', '_on_audio'), ('media_video_browse', '_on_browse'), ('media_video_run', '_on_video'))),
 ('run_history',
  'tab_run_history',
  'automation',
  False,
  'je_auto_control.gui.run_history_tab',
  'RunHistoryTab',
  (('rh_refresh', '_refresh'),
   ('rh_clear', '_on_clear'),
   ('rh_open_artifact', '_open_selected_artifact'),
   ('journal_record', '_record_journal'),
   ('journal_preview', '_preview_journal'))),
 ('profiler',
  'tab_profiler',
  'automation',
  False,
  'je_auto_control.gui.profiler_tab',
  'ProfilerTab',
  (('prof_enable', '_toggle_enable'), ('prof_reset', '_on_reset'), ('prof_refresh', '_refresh'))),
 ('window_manager',
  'tab_window_manager',
  'system',
  False,
  'je_auto_control.gui.window_tab',
  'WindowManagerTab',
  (('win_refresh', 'refresh'), ('win_focus_selected', '_on_focus'), ('win_close_selected', '_on_close'))),
 ('plugins',
  'tab_plugins',
  'system',
  False,
  'je_auto_control.gui.plugins_tab',
  'PluginsTab',
  (('browse', '_browse'), ('pl_load', '_on_load'))),
 ('webrunner',
  'tab_webrunner',
  'automation',
  False,
  'je_auto_control.gui.webrunner_tab',
  'WebRunnerTab',
  (('web_browse', '_on_browse_screenshot'),
   ('web_open_btn', '_on_open'),
   ('web_quit_btn', '_on_quit'),
   ('web_screenshot_btn', '_on_screenshot'),
   ('web_run_btn', '_on_run_freeform'),
   ('web_refresh_btn', '_on_refresh_commands'))),
 ('dag_runner',
  'tab_dag_runner',
  'automation',
  False,
  'je_auto_control.gui.dag_tab',
  'DagTab',
  (('dag_load_btn', '_on_load'),
   ('dag_validate_btn', '_on_validate'),
   ('dag_run_btn', '_on_run'),
   ('dag_stop_btn', '_on_stop'))),
 ('chatops',
  'tab_chatops',
  'automation',
  False,
  'je_auto_control.gui.chatops_tab',
  'ChatOpsTab',
  (('chatops_browse_btn', '_on_browse'), ('chatops_send_btn', '_on_send'))),
 ('trace_replay',
  'tab_trace_replay',
  'automation',
  False,
  'je_auto_control.gui.trace_replay_tab',
  'TraceReplayTab',
  (('trace_open_btn', '_on_open'),
   ('trace_first_btn', '_on_first'),
   ('trace_prev_btn', '_on_prev'),
   ('trace_next_btn', '_on_next'),
   ('trace_last_btn', '_on_last'))),
 ('remote_desktop', 'tab_remote_desktop', 'system', True, '', '_build_remote_desktop_tab', ()),
 ('presence',
  'tab_presence',
  'system',
  False,
  'je_auto_control.gui.presence_tab',
  'PresenceTab',
  (('presence_refresh_btn', 'refresh'),
   ('presence_promote_btn', '_on_promote'),
   ('presence_demote_btn', '_on_demote'),
   ('presence_kick_btn', '_on_kick'))),
 ('rest_api',
  'tab_rest_api',
  'system',
  False,
  'je_auto_control.gui.rest_api_tab',
  'RestApiTab',
  (('rest_start', '_on_start'),
   ('rest_stop', '_on_stop'),
   ('rest_copy_url', '_on_copy_url'),
   ('rest_copy_token', '_on_copy_token'),
   ('rest_config_export', '_on_config_export'),
   ('rest_config_import', '_on_config_import'))),
 ('admin_console',
  'tab_admin_console',
  'system',
  False,
  'je_auto_control.gui.admin_console_tab',
  'AdminConsoleTab',
  (('admin_add', '_on_add'),
   ('admin_remove', '_on_remove'),
   ('admin_refresh', '_on_refresh'),
   ('admin_thumb_refresh_now', '_refresh_thumbnails'),
   ('admin_broadcast_run', '_on_broadcast'))),
 ('audit_log',
  'tab_audit_log',
  'system',
  False,
  'je_auto_control.gui.audit_log_tab',
  'AuditLogTab',
  (('audit_refresh', '_refresh'), ('audit_verify', '_verify'), ('audit_clear', '_clear'))),
 ('inspector',
  'tab_inspector',
  'system',
  False,
  'je_auto_control.gui.inspector_tab',
  'InspectorTab',
  (('inspector_refresh', '_refresh'), ('inspector_reset', '_reset'))),
 ('usb_devices',
  'tab_usb_devices',
  'system',
  False,
  'je_auto_control.gui.usb_devices_tab',
  'UsbDevicesTab',
  (('usb_refresh', '_refresh'),)),
 ('usb_browser',
  'tab_usb_browser',
  'system',
  False,
  'je_auto_control.gui.usb_browser_tab',
  'UsbBrowserTab',
  (('usb_browser_fetch', '_on_fetch'), ('usb_browser_open', '_on_open_selected'))),
 ('usb_share',
  'tab_usb_share',
  'system',
  False,
  'je_auto_control.gui.usb_passthrough_panel',
  'UsbPassthroughPanel',
  (('usb_share_enable', '_enable_sharing'),
   ('usb_share_disable', '_disable_sharing'),
   ('usb_share_refresh_local', '_refresh_local_devices'),
   ('usb_share_allow', '_allow_selected'),
   ('usb_share_block', '_block_selected'),
   ('usb_share_export_acl', '_export_acl'),
   ('usb_share_import_acl', '_import_acl'),
   ('usb_share_fetch_shared', '_list_shared'),
   ('usb_share_open_selected', '_open_selected'),
   ('usb_share_remote_fetch', '_fetch_remote'))),
 ('diagnostics',
  'tab_diagnostics',
  'system',
  False,
  'je_auto_control.gui.diagnostics_tab',
  'DiagnosticsTab',
  (('diag_run', '_refresh'), ('diag_stop_input', '_stop_input'), ('diag_retry_input', '_retry_input'))),
 ('report',
  'tab_report',
  'system',
  False,
  '',
  '_build_report_tab',
  (('enable_test_record', '_enable_test_record'),
   ('disable_test_record', '_disable_test_record'),
   ('generate_html_report', '_gen_html'),
   ('generate_json_report', '_gen_json'),
   ('generate_xml_report', '_gen_xml'),
   ('workspace_cancel_task', '_cancel_report'))))
