"""Generate a ``.pyi`` typing stub from the live ``Executor.event_dict``.

The IDE story for AutoControl has historically been "import ``ac`` and
guess at parameters". Running this generator emits a typed stub that
mirrors every ``AC_*`` command — IDEs (PyCharm, VS Code via Pylance,
Pyright) pick it up via the standard ``__init__.pyi`` lookup so users
get autocomplete + signature help with zero per-script effort.

Usage::

    python -m je_auto_control.utils.stubs.generator        # print to stdout
    python -m je_auto_control.utils.stubs.generator path   # write to ``path``

The generator is deterministic — same executor state → same stub —
so the test suite can re-run it and assert the checked-in stub is up
to date.
"""
from __future__ import annotations

import argparse
import inspect
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

_HEADER = (
    "# AUTOGENERATED by je_auto_control.utils.stubs.generator — do not edit.\n"
    "# Regenerate with: python -m je_auto_control.utils.stubs.generator\n"
    "# ruff: noqa: F401  # generated stub keeps typing imports for forward use\n"
    "from typing import (\n"
    "    Any, Callable, Dict, List, Mapping, Optional,\n"
    "    Sequence, Tuple, Union,\n"
    ")\n"
    "\n"
)


@dataclass(frozen=True)
class StubSignature:
    """One ``def AC_foo(...) -> ...`` line we will emit into the stub."""

    name: str
    parameters: str
    return_annotation: str
    docstring: Optional[str] = None


def collect_signatures(event_dict: Optional[Dict[str, Callable[..., Any]]] = None,
                       ) -> List[StubSignature]:
    """Read the live ``Executor.event_dict`` and convert each entry."""
    if event_dict is None:
        from je_auto_control.utils.executor.action_executor import executor
        event_dict = executor.event_dict
    signatures: List[StubSignature] = []
    for name, handler in sorted(event_dict.items()):
        if not isinstance(name, str):
            continue
        try:
            sig = inspect.signature(handler)
        except (TypeError, ValueError):
            sig = None
        signatures.append(
            StubSignature(
                name=name,
                parameters=_render_parameters(sig),
                return_annotation=_render_return(sig),
                docstring=_first_doc_line(handler),
            )
        )
    return signatures


def render_pyi(signatures: List[StubSignature]) -> str:
    """Format a list of :class:`StubSignature` into a complete .pyi file."""
    lines = [_HEADER]
    for sig in signatures:
        lines.append(_render_signature(sig))
    return "".join(lines).rstrip() + "\n"


def write_pyi(target: Path,
              signatures: Optional[List[StubSignature]] = None) -> Path:
    """Render and atomically write the stub file. Returns the path."""
    sigs = signatures if signatures is not None else collect_signatures()
    body = render_pyi(sigs)
    target = Path(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(target.suffix + ".tmp")
    tmp.write_text(body, encoding="utf-8")
    tmp.replace(target)
    return target


# --- internals ----------------------------------------------------

def _render_parameters(sig: Optional[inspect.Signature]) -> str:
    if sig is None:
        return "*args: Any, **kwargs: Any"
    parts: List[str] = []
    for param in sig.parameters.values():
        parts.append(_render_param(param))
    return ", ".join(parts)


def _render_param(param: inspect.Parameter) -> str:
    annotation = _annotation_str(param.annotation, default="Any")
    prefix = ""
    if param.kind == inspect.Parameter.VAR_POSITIONAL:
        prefix = "*"
    elif param.kind == inspect.Parameter.VAR_KEYWORD:
        prefix = "**"
    if param.default is inspect.Parameter.empty:
        return f"{prefix}{param.name}: {annotation}"
    return f"{prefix}{param.name}: {annotation} = ..."


def _render_return(sig: Optional[inspect.Signature]) -> str:
    if sig is None:
        return "Any"
    return _annotation_str(sig.return_annotation, default="Any")


_BUILTIN_TYPES = frozenset({
    "bool", "bytes", "bytearray", "complex", "dict", "float", "frozenset",
    "int", "list", "memoryview", "object", "range", "set", "str", "tuple",
    "type", "None",
})


def _annotation_str(annotation: Any, *, default: str) -> str:
    if annotation is inspect.Parameter.empty:
        return default
    if isinstance(annotation, type):
        name = annotation.__name__
        # Project-owned classes aren't imported into the stub, so fall
        # back to ``Any`` rather than emit a bare name that won't
        # resolve. Builtins keep their names.
        return name if name in _BUILTIN_TYPES else "Any"
    text = str(annotation)
    # ``typing`` is re-exported at the top of the stub, so strip the
    # prefix from both leading and embedded uses (``List[typing.Dict[…]]``).
    text = text.replace("typing.", "")
    # ``inspect.signature`` renders ``type(None)`` as ``NoneType``; the
    # name only resolves if ``types.NoneType`` is imported. ``None``
    # works as a type annotation everywhere and reads cleaner.
    text = text.replace("NoneType", "None")
    # Any dotted reference that isn't a typing builtin would need the
    # owning module imported into the stub. Rather than transitively
    # import the world, fall back to ``Any``; the function name still
    # autocompletes, the precise type just shows as Any.
    if _has_module_reference(text):
        return "Any"
    return text


def _has_module_reference(text: str) -> bool:
    """True iff ``text`` still references a non-typing dotted name."""
    if "." not in text:
        return False
    # Allow ellipsis-style forward refs that survive the typing.strip
    # without an actual module reference (e.g. ``Callable[..., int]``).
    sanitised = text.replace("...", "")
    return "." in sanitised


def _first_doc_line(handler: Callable[..., Any]) -> Optional[str]:
    doc = inspect.getdoc(handler)
    if not doc:
        return None
    return doc.splitlines()[0].strip() or None


def _render_signature(sig: StubSignature) -> str:
    head = f"def {sig.name}({sig.parameters}) -> {sig.return_annotation}:\n"
    if sig.docstring:
        body = f'    """{sig.docstring}"""\n'
    else:
        body = "    ...\n"
    return head + body + "\n"


def _cli(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "path", nargs="?",
        help="Output path (omit to print to stdout).",
    )
    args = parser.parse_args(argv)
    signatures = collect_signatures()
    body = render_pyi(signatures)
    if args.path:
        write_pyi(Path(args.path), signatures)
        print(f"wrote {len(signatures)} signatures to {args.path}")
        return 0
    import sys
    sys.stdout.write(body)
    return 0


__all__ = [
    "StubSignature", "collect_signatures", "render_pyi", "write_pyi",
]


if __name__ == "__main__":
    raise SystemExit(_cli())
