name: AutoControl Stable Python3.10

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: read

jobs:
  build_stable_version:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Test Screen Module
        run: python ./test/unit_test/screen/screen_test.py
      - name: Test Screenshot
        run: python ./test/unit_test/screen/screenshot_test.py
      - name: Save Screenshot Image
        uses: actions/upload-artifact@v4
        with:
          name: screenshot_png
          path: test.png

      - name: Test Keyboard type Function
        run: python ./test/unit_test/keyboard/keyboard_type_test.py
      - name: Test Keyboard write Function
        run: |
          python ./test/unit_test/keyboard/keyboard_write_test.py
      - name: Test Keyboard is_press Function
        run: python ./test/unit_test/keyboard/keyboard_is_press_test.py
      - name: Test Keyboard hotkey Function
        run: python ./test/unit_test/keyboard/hotkey_test.py

      - name: Test Mouse Module
        run: python ./test/unit_test/mouse/mouse_test.py
      - name: Test Scroll Module
        run: python ./test/unit_test/exception/auto_control_exception_test.py

      - name: Test Exceptions
        run: python ./test/unit_test/exception/auto_control_exception_test.py

      - name: Test Critical Exit
        run: python ./test/unit_test/critical_exit/critical_exit_test.py
      - name: Test Real Critical Situation
        run: |
          python ./test/unit_test/critical_exit/real_critical_test.py
          exit 0

      - name: Test Record Module
        run: python ./test/unit_test/record/record_test.py
      - name: Test Total Record
        run: python ./test/unit_test/total_record/total_record_test.py

      - name: Test Execute Action
        run: python ./test/unit_test/execute_action/execute_action_test.py

      - name: Test Json Module
        run: python ./test/unit_test/json/json_test.py
      - name: Test Generate Json Report
        run: python ./test/unit_test/generate_report/json_report.py
      - name: Test Timeout Module
        run: python ./test/unit_test/timeout/timeout_test.py
      - name: Test Generate HTML Report
        run: python ./test/unit_test/generate_report/html_report_test.py

      - name: Test Argparse
        run: python ./test/unit_test/argparse/argparse_test.py

      - name: Test Callback Module
        run: python ./test/unit_test/callback/callback_test.py

      - name: Test Create Project Function
        run: python ./test/unit_test/create_project_file/create_project_test.py

      - name: Test Get Mouse Info
        run: python ./test/unit_test/get_info/mouse_info.py
      - name: Test Get Special Info
        run: python ./test/unit_test/get_info/special_info.py
      - name: Test Get Keyboard Info
        run: python ./test/unit_test/get_info/keyboard_info.py
